INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1005, 'Thành Cổ Loa', 'thanh-co-loa', '<p>Thành Cổ Loa là kinh đô của nhà nước Âu Lạc do <a href="https://huynhhieutravel.com/an-duong-vuong/">An Dương Vương</a> thành lập. Thành Cổ Loa được thành lập vào thế kỷ thứ 3 TCN. Hiện nay, thành Cổ Loa nằm ở xã Cổ Loa, Đông Anh, Hà Nội. Vào năm 1962 thành Cổ Loa được đưa vào danh sách di sản văn hóa quốc gia của Việt Nam. Thành gắn liền với nhiều truyền thuyết xưa, mà điển hình là truyền thuyết Trọng Thủy &#8211; Mị Châu. Ngoài ra, xét về mặt lịch sử, thành Cổ Loa mang ý nghĩa to lớn. Nơi này đánh dấu cột mốc dân tộc ta bắt đầu chuyển sang định cư và đóng đô từ vùng núi sang vùng đồng bằng. Hãy cùng Huynh Hieu Travel tìm hiểu về thành Cổ Loa nhé!</p>
<h2>Thành Cổ Loa</h2>
<p>Dời đô từ vùng núi đến đây và xây dựng nên một thành trì to lớn. <a href="https://huynhhieutravel.com/an-duong-vuong/">An Dương Vương</a> đã tìm hiểu những thuận lợi về mặt địa lý để kiến tạo nên một ngôi thành lịch sử.</p>
<p><figure id="attachment_1007" aria-describedby="caption-attachment-1007" style="width: 660px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1007" src="https://media.huynhhieutravel.com/thanh-co-loa.jpg" alt="Thành Cổ Loa" width="660" height="495"><figcaption id="caption-attachment-1007" class="wp-caption-text">Thành Cổ Loa</figcaption></figure></p>
<h3>Vị trí địa lý</h3>
<p>Thời xưa, Cổ Loa nằm ở vị trí đỉnh tam giác châu thổ sông Hồng. Nơi đây giao thương dễ dàng khi giao tiếp cả đường thủy và đường bộ. Khi nắm giữ nơi đây, người Âu Lạc sẽ bao quát cả vùng đồng bằng và kiểm soát cả vùng núi.</p>
<p>Thành Cổ Loa nằm bên con sông Hoành. Nơi giao thoa nối liền sông Hồng và sông Cầu (Con sông lớn nhất trong hệ thống sông rạch chằng chịt Thái Bình). Việc nắm giữ đường thủy cả hai con sông Hồng và sông Thái Bình mang đến lợi thế thông thương to lớn cho thành Cổ Loa. Hai con sông này gần như chiếm toàn bộ hệ thống đường thủy Bắc bộ thời bấy giờ. Nếu muốn ra biển lớn chỉ cần xuôi theo con sông Hồng. Nếu muốn đi ngược lại vùng đồng bằng Tây Bắc thì xuôi theo con sông Thái Bình.</p>
<p><figure id="attachment_1009" aria-describedby="caption-attachment-1009" style="width: 900px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1009" src="https://media.huynhhieutravel.com/thanh-co-loa3.jpg" alt="Thành Cổ Loa" width="900" height="369" srcset="https://media.huynhhieutravel.com/thanh-co-loa3.jpg 900w, https://media.huynhhieutravel.com/thanh-co-loa3-768x315.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" /><figcaption id="caption-attachment-1009" class="wp-caption-text">Thành Cổ Loa</figcaption></figure></p>
<p>Mặt còn lại của thành Cổ Loa là vùng đồng bằng rộng lớn. Nơi đây bắt đầu xuất hiện nhiều xóm làng, dân chúng sống đông đúc. Kinh tế phát triển vượt bậc với đủ các loại nghề: Trồng lúa, thủ công nghiệp, đánh bắt cá,&#8230; Tuy giai đoạn trị vì của An Dương Vương chỉ khoảng 30-50 năm. Nhưng đây là giai đoạn đánh dấu sự chuyển mình của dân tộc Việt cổ. Địa lý từ vùng núi sang vùng đất đồng bằng trù phú. Không những là kinh tế tăng trưởng vượt bậc mà nền văn hóa Đông Sơn cũng rực rỡ nhất vào giai đoạn này.</p>
<h3>Giai đoạn xây dựng thành Cổ Loa</h3>
<p>Thành Cổ Loa xưa và nay có sự khác biệt. Thời gian trôi qua, với sự tác động của thiên nhiên và con người đã làm thành Cổ Loa thay đổi.</p>
<h4>Thành Cổ Loa xưa</h4>
<p>Theo sử sách xưa,&nbsp;thành được xây quanh co chín lớp, chu vi chín dặm, sâu nghìn trượng, xoáy tròn như hình ốc. Nên được gọi là Loa Thành (&#8220;loa&#8221; có nghĩa là con ốc). Thành còn có tên nôm là Chạ Chủ và nhiều tên khác như Khả Lũ (&#8220;Lũ&#8221; có nghĩa là quanh co nhiều lớp), Côn Lôn thành (ý nói thành cao như núi Côn Lôn bên Trung Quốc) hoặc Việt Vương thành (thành của vua xứ Việt), dân địa phương gọi bằng tên tiếng nôm là thành Chủ.</p>
<p>Để có đất xây thành, An Dương Vương phải cho dời dân tại chỗ đi nơi khác. Theo truyền thuyết thì làng Quậy hiện nay nguyên vốn ở tại Cổ Loa đã phải dời xuống vùng đất trũng cuối dòng sông Hoàng để An Dương Vương xây thành.</p>
<p><figure id="attachment_1010" aria-describedby="caption-attachment-1010" style="width: 556px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1010" src="https://media.huynhhieutravel.com/thanh-co-loa4.jpg" alt="Thành Cổ Loa" width="556" height="396"><figcaption id="caption-attachment-1010" class="wp-caption-text">Thành Cổ Loa</figcaption></figure></p>
<p>Thành Cổ Loa được các nhà khảo cổ học đánh giá là &#8220;tòa thành cổ nhất, quy mô lớn vào bậc nhất, cấu trúc cũng thuộc loại độc đáo nhất trong lịch sử xây dựng thành lũy của nước ta&#8221;</p>
<p>Vào thời Âu Lạc, con người chỉ mới làm quen với một ít kỹ thuật sơ khai, công cụ lao động còn rất thô thiển, ít hiệu quả, tất cả công việc đều do bàn tay người mà ra. Muốn xây được công trình với &#8220;quy mô lớn vào bậc nhất&#8221; này, phải có một số lượng khổng lồ đất đào đắp, đá kè và gốm rải. Nhà nước Âu Lạc hẳn đã phải điều động một số nhân công rất lớn để lao động trong một thời gian rất dài mới có thể hoàn thành được. Các nhà khảo cổ học cho rằng đã phải có đến hàng vạn người làm việc hàng năm cho công trình này.</p>
<p>Khi xây thành, người xưa đã biết lợi dụng tối đa và khéo léo các địa hình tự nhiên. Họ tận dụng chiều cao của các đồi, gò, đắp thêm đất cho cao hơn để xây nên hai bức tường thành phía ngoài, vì thế hai bức tường thành này có đường nét uốn lượn theo địa hình chứ không băng theo đường thẳng như bức tường thành trung tâm. Người xưa lại xây thành bên cạnh con sông Hoàng để dùng sông này vừa làm hào bảo vệ thành vừa là nguồn cung cấp nước cho toàn bộ hệ thống hào vừa là đường thủy quan trọng. Chiếc Đầm Cả rộng lớn nằm ở phía Đông cũng được tận dụng biến thành bến cảng làm nơi tụ họp cho đến cả hàng trăm thuyền bè.</p>
<p>Chất liệu chủ yếu dùng để xây thành là đất, sau đó là đá và gốm vỡ. Đá được dùng để kè cho chân thành được vững chắc. Các đoạn thành ven sông, ven đầm được kè nhiều đá hơn các đoạn khác. Đá kè là loại đá tảng lớn và đá cuội được chở tới từ các miền núi. Xen giữa đám đất đá là những lớp gốm được rải dày mỏng khác nhau, nhiều nhất là ở chân thành và rìa thành để chống sụt lở. Các cuộc khai quật khảo cổ học đã tìm thấy một số lượng gốm khổng lồ gồm ngói ống, ngói bản, đầu ngói, đinh ngói. Ngói có nhiều loại với độ nung khác nhau. Có cái được nung ở nhiệt độ thấp, có cái được nung rất cao gần như sành. Ngói được trang trí nhiều loại hoa văn ở một mặt hay hai mặt.</p>
<p>Tường thành phía ngoài được xây dựng đứng để gây khó khăn cho đối phương, còn mặt trong thì được xây thoai thoải để dễ dàng lên xuống.</p>
<h4>Thành Cổ Loa từ đời Ngô Quyền đến hiện nay.</h4>
<p>Ngô Quyền cho đóng đô ở thành Cổ Loa. Ngô Quyền đã tiến hành nhiều cải cánh khác nhau. Mà điển hình là việc tu sửa lại thành Cổ Loa thành nơi trung tâm về quân sự, kinh tế và văn hóa của cả nước. Tuy vậy&nbsp;Ngô Quyền chỉ tại vị được 6 năm, một tòa thành Cổ Loa hoàn toàn mới của triều đại nhà Ngô như ý kiến của một số nhà nghiên cứu, thật khó có điều kiện khả thi. Thành Cổ Loa trong thời gian ngắn này có lẽ chỉ được đắp thêm từng phần trên cơ sở tòa thành cũ của An Dương Vương đã được gia cố nhiều lần trong thời kỳ Bắc thuộc.</p>
<p><figure id="attachment_1011" aria-describedby="caption-attachment-1011" style="width: 1600px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1011" src="https://media.huynhhieutravel.com/thanh-co-loa5.jpg" alt="Thành Cổ Loa" width="1600" height="1060" srcset="https://media.huynhhieutravel.com/thanh-co-loa5.jpg 1600w, https://media.huynhhieutravel.com/thanh-co-loa5-768x509.jpg 768w" sizes="(max-width: 1600px) 100vw, 1600px" /><figcaption id="caption-attachment-1011" class="wp-caption-text">Thành Cổ Loa</figcaption></figure></p>
<p>Từ thời của Ngô Quyền đến nay, thành Cổ Loa đã được tu sửa và xây dựng thêm. Thành lúc ấy có 3 vòng chính, chia thành: Thành nội, thành trung và thành ngoại.</p>
<p>Chu vi vòng ngoài 8&nbsp;km, vòng giữa 6,5&nbsp;km, vòng trong 1,6&nbsp;km, diện tích trung tâm lên tới 2&nbsp;km². Thành được xây theo phương pháp đào đất đến đâu, khoét hào đến đó, thành đắp đến đâu, lũy xây đến đó. Mặt ngoài lũy, dốc thẳng đứng, mặt trong xoải để đánh vào thì khó, trong đánh ra thì dễ. Lũy cao trung bình từ 4 m-5 m, có chỗ cao đến 8 m-12 m. Chân lũy rộng 20 m-30 m, mặt lũy rộng 6 m-12 m. Khối lượng đất đào đắp ước tính 2,2 triệu mét khối.</p>
<p><strong>Thành nội</strong> hình chữ nhật, cao trung bình 5 m so với mặt đất, mặt thành rộng từ 6 m-12 m, chân rộng từ 20 m-30 m, chu vi 1.650 m và có một cửa nhìn vào tòa kiến trúc Ngự triều di quy.</p>
<p><strong>Thành trung</strong> là một vòng thành không có khuôn hình cân xứng, dài 6.500 m, nơi cao nhất là 10 m, mặt thành rộng trung bình 10 m, có bốn cửa ở các hướng cống song, bắc, tây bắc và tây nam, trong đó cửa đông ăn thông với sông Hồng.</p>
<p><strong>Thành ngoại</strong> cũng không có hình dáng rõ ràng, dài hơn 8.000m, cao trung bình 3 m-4 m (có chỗ tới hơn 8 m).</p>
<p>Mỗi vòng thành đều có hào nước bao quanh bên ngoài, hào rộng trung bình từ 10m đến 30m, có chỗ còn rộng hơn. Các vòng hào đều thông với nhau và thông với sông Hoàng. Sự kết hợp của sông, hào và tường thành không có hình dạng nhất định, khiến thành như một mê cung, là một khu quân sự vừa thuận lợi cho tấn công vừa tốt cho phòng thủ.</p>
<p>Sông Hoàng được dùng làm hào thiên nhiên cho thành Ngoại ở về phía Tây Nam và Nam. Phần hào còn lại được đào sát chân tường thành từ gò Cột Cờ đến Đầm Cả. Con hào này nối với hào của thành Trung ở Đầm Cả và Xóm Mít, chảy qua cửa Cống Song nối với năm con lạch có hình dáng như bàn tay xòe, và với một nhánh của con lạch này, nước chảy thông vào vòng hào của thành Nội.</p>
<p>Thuyền bè đi lại dễ dàng trên ba vòng hào để đến trú đậu ở Đầm Cả hoặc ra sông Hoàng và từ đó có thể tỏa đi khắp nơi. Theo truyền thuyết,Thục Phán An Dương Vương thường dùng thuyền đi khắp các hào rồi ra sông Hồng.</p>
<h3>Những giá trị thành Cổ Loa mang lại</h3>
<p>Trong cấu trúc thành Cổ Loa khi xây dưng, thành Cổ Loa tận dụng lợi thế thiên nhiên khá nhiều. Vì vậy, trên những gò đất cao và dài là những ụ, lũy được xây dựng để canh gác. Một số lũy như vậy được dân đặt tên như Đống Dân, Đống Chuông, Đống Bắn&#8230;</p>
<p>Về mặt quân sự, thành Cổ Loa thể hiện sự sáng tạo độc đáo của người Việt cổ trong công cuộc giữ nước và chống ngoại xâm. Với các bức thành kiên cố, với hào sâu rộng cùng các ụ, lũy, Cổ Loa là một căn cứ phòng thủ vững chắc để bảo vệ nhà vua, triều đình và kinh đô. Đồng thời là một căn cứ kết hợp hài hòa thủy binh cùng bộ binh. Nhờ ba vòng hào thông nhau dễ dàng, thủy binh có thể phối hợp cùng bộ binh để vận động trên bộ cũng như trên nước khi tác chiến.</p>
<p><figure id="attachment_1008" aria-describedby="caption-attachment-1008" style="width: 450px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1008" src="https://media.huynhhieutravel.com/thanh-co-loa2.jpg" alt="Thành Cổ Loa" width="450" height="338"><figcaption id="caption-attachment-1008" class="wp-caption-text">Thành Cổ Loa</figcaption></figure></p>
<p>Về mặt xã hội, với sự phân bố từng khu cư trú cho vua, quan, binh lính, thành Cổ Loa là một chứng cứ về sự phân hóa của xã hội thời ấy. Thời kỳ này, vua quan không những đã tách khỏi dân chúng mà còn phải được bảo vệ chặt chẽ, sống gần như cô lập hẳn với cuộc sống bình thường. Xã hội đã có giai cấp rõ ràng và xã hội có sự phân hóa giàu nghèo rõ ràng hơn thời Vua Hùng.</p>
<p>Về mặt văn hóa, là một tòa thành cổ nhất còn để lại dấu tích, Cổ Loa trở thành một di sản văn hóa, một bằng chứng về sự sáng tạo, về trình độ kỹ thuật cũng như văn hóa của người Việt Cổ. Đá kè chân thành, gốm rải rìa thành, hào nước quanh co, ụ lũy phức tạp, hỏa hồi chắc chắn và nhất là địa hình hiểm trở ngoằn ngoèo, tất cả những điều làm chứng nghệ thuật và văn hóa thời An Dương Vương. Hàng năm, vào ngày 6 tháng giêng âm lịch, cư dân Cổ Loa tổ chức một lễ trang trọng để tưởng nhớ đến những người xưa đã có công xây thành, và nhất là để ghi ơn An Dương Vương.</p>
<p>Hiện nay Cổ Loa là một trong 21 khu du lịch quốc gia Việt Nam, và vào ngày 27/9/2012 di tích lịch sử kiến trúc nghệ thuật và khảo cổ Cổ Loa được Thủ tướng Chính phủ quyết định xếp hạng di tích quốc gia đặc biệt.</p>
<h3>Thành Cổ Loa hiện nay và quy hoạch tương lai</h3>
<p>Trong những năm gần đây thành Cổ Loa bắt đầu khoác lên mình một diện mạo mới hơn. Các dự án quy hoạch và tu sửa thành Cổ Loa đang được phát triển thêm nhiều hơn.&nbsp;Một số dự án tu bổ tôn tạo trong khu vực Cổ Loa như: Am Mỵ Châu, đình Ngự triều di quy, đền An Dương Vương, đình-chùa Mạch Tràng, Giếng Ngọc, khảo cổ học Mắt Rồng, Bãi Mèn, Đồng Vông… cùng một số công trình giao thông đã hoàn thành như đường vào cửa Tây, cầu qua sông Hoàng, bãi để xe và một số hạng mục phụ trợ.</p>
<p>Xã Cổ Loa hiện có 14 thôn, xóm trong đó 11 xóm ở trên, trong hoặc giữa các vòng thành. Điều này đã tạo nên sự khác biệt của Cổ Loa so với các khu di tích khác. Khu di tích này vẫn cộng động cho người dân sống xen kẻ bên trong. Cũng từ đây nảy sinh những khó khăn trong công tác bảo tồn. Theo thống kê năm 1997, số hộ dân trên mặt thành và hào là 330 hộ. Theo thống kê năm 2005 của Văn phòng Tư vấn và Chuyển giao công nghệ xây dựng – trường Đại học Kiến trúc Hà Nội(đơn vị lập báo cáo đầu tư tu bổ tôn tạo khu di tích Cổ Loa) thì tổng số dân trên đất thành là 394 hộ, trong đó khu thành Nội có 119 hộ. Sự tăng hộ này là do dân số tăng tự nhiên trong các xóm, làng (tỉ lệ tăng tự nhiên ở Cổ Loa là 1,33%/năm). Số nhà mới xây dựng vì thế cũng tăng lên, hầu hết là xây dựng trên đất thổ cư đã được cấp giấy phép quyền sử dụng đất.</p>
<p>Những việc đó tạo nên nhiều tổn hại cho di tích Thành Cổ Loa. Nhưng hiện đang được khắc phục dần. Những kế hoạch bảo tồn chi tiết đã được thông qua. Hy vọng thành Cổ Loa sẽ giữ lại những nét cổ xưa độc đáo làm nên một di tích cấp quốc gia.</p>
', 'Thành Cổ Loa là kinh đô của nhà nước Âu Lạc do An Dương Vương thành lập. Thành Cổ Loa được thành lập vào thế kỷ thứ 3 TCN. Hiện nay, thành Cổ Loa nằm ở xã Cổ Loa, Đông Anh, Hà Nội. Vào năm 1962 thành Cổ Loa được đưa vào danh sách di [&hellip;]', 1007, 'post', '2018-06-24 07:56:02', '2023-04-23 12:33:55');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1005, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1005, 64);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1006, 'Sự tích thành Cổ Loa', 'su-tich-thanh-co-loa', '<p>Thành Cổ Loa được xây dựng dưới thời <a href="https://huynhhieutravel.com/an-duong-vuong/">An Dương Vương</a>. Ngôi thành mang ý nghĩa lịch sử to lớn về mặt quân sự cũng như văn hóa. Nó đánh dấu cột mốc quan trọng khi tộc Việt cổ chuyển từ thói quen sống ở miền núi sang ở đồng bằng. Sự tích xây dựng thành Cổ Loa có nhiều dị bản khác nhau. Nhưng đây là một bản được xem là đầy đủ và chân thật nhất trong góc độ truyền thuyết.</p>
<h2>Sự Tích Thành Cổ Loa Trong Dân Gian</h2>
<p>Khi đã chiếm được đất Văn Lang, <a href="https://huynhhieutravel.com/an-duong-vuong/">An Dương Vương</a> đổi tên nước là Âu Lạc, đóng đô ở Phong Khê.</p>
<p>Khu đất chọn để đắp thành là một quả đồi đất rắn như đá. Ðám đông người hì hục đào đất, khuân đất hết ngày nọ sang ngày kia, tòa thành cao dần.</p>
<p><a href="https://huynhhieutravel.com/an-duong-vuong/">An Dương Vương</a> cùng đoàn tùy tùng đến xem rất lấy làm hài lòng, cho là một tòa thành có thể đứng vững muôn đời, sấm sét không lay chuyển, mưa bão không làm sạt được, và quân giặc cũng không thể phá nổi.</p>
<h3>Gian nan xây tường thành</h3>
<p>Nhưng một đêm cả bức tường thành quanh co đều đổ sập xuống như đất bằng. Vua An Dương Vương đến xem rất lấy làm tức giận. Ngài hỏi dò dân chúng gần đó, họ kể lại: Ban đêm họ nghe thấy những bước chân rầm rập ở các khắp ngã kéo đến với những tiếng xì xào có thể là ma quỉ. Người đâu mà lại đông đến thế ! Họ sợ quá nên không dám nhìn ra. Rồi họ lại nghe những tiếng đổ ầm ầm như sấm dậy.</p>
<p>An Dương Vương sai các tướng lãnh đốc thúc đắp lại thành cho kỳ được. Ðám người hăng hái đắp lại không ngừng. Tường thành mỗi ngày một cao dần và lại cao như tường thành cũ. Nhưng rồi một đêm cả dãy tường thành lại sập xuống như đất bằng. An Dương Vương sai người đi hỏi dân chúng ở gần đó thì họ lại nói như trước. Ban đêm họ cũng nghe thấy những bước chân rầm rập như thiên binh vạn mã trẩy qua rồi lại những tiềng huỳnh huỵch tiếp đến những tiếng ầm ầm như sấm động.</p>
<p><figure id="attachment_1007" aria-describedby="caption-attachment-1007" style="width: 660px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1007" src="https://media.huynhhieutravel.com/thanh-co-loa.jpg" alt="Thành Cổ Loa" width="660" height="495"><figcaption id="caption-attachment-1007" class="wp-caption-text">Thành Cổ Loa nhìn từ trên cao</figcaption></figure></p>
<p>An Dương Vương lại xem chỗ địa thành để cầu trời phù hộ mình đắp cho xong tòa thành. Vua đi vòng quanh chân tường vừa đi vừa suy nghĩ. Ðột nhiên vua thấy một ông già râu tóc bạc từ phía xa đi lại. Ðến gần An Dương Vương ông tự xưng mình là thổ thần của vùng đất này, nói với vua rằng:</p>
<p>– Nhà vua đừng lo, sáng mai nhà vua ra đợi ở bờ sông sẽ có sứ giả Thanh Giang đến giúp nhà vua đắp thành.</p>
<p>Nói xong ông già biến mất.</p>
<h3>Thần Kim Qui xuất hiện</h3>
<p>Hôm sau mới tờ mờ sáng, An Dương Vương đã ra tận bờ sông để đợi Giang sứ. Vừa bắt đầu tan sương thì có một con rùa vàng rất lớn nổi lên mặt sông từ phía Ðông bơi vào bờ đến gần nhà vua, rùa tự xưng mình là thần Kim Quy sứ giả của vua Thủy Tề. An Dương Vương sai đặt Giang sứ lên một chiếc mâm vàng và khiêng vào cung.</p>
<p>Vua hỏi kế đắp thành, thần Kim Quy bảo rằng:</p>
<p>&#8211; Ở núi Thất Diệu có một con gà trắng sống lâu năm thành tinh có phép biến hoá khôn lường. Nó thường hãm hại khách qua đường và khách ngủ ở quán trọ trong vùng này. Các vua thời trước cùng bọn nhạc công chết đi đều chôn ở núi Thất Diệu, những u hồn ấy từ lâu không tan lẩn khuất trong khe đá ở hang sâu. Những u hồn ấy có thù với nhà vua nên đêm thanh vắng họp thành từng đàn từng lũ đến xúi dục con tinh gà trắng phá thành đang xây của nhà vua. Con tinh gà trắng đã dẫn những u hồn ấy đến chân thành dùng phép ma phá đổ tường thành rồi gần sáng lại bay về núi. Con tinh gà trắng có tiền duyên với con gái lão chủ quán gần chân núi nên hay hiện hình làm khách bộ hành ghé vào nhà lão khi thì nhập vào con gái lão khi thì nhập vào con gà trắng của lão. Muốn đắp cho được thành, trước hết phải trừ cho tiệt giống yêu ma và giết đứa con gái cùng con gà trắng của lão chủ quán kia đi.</p>
<p><figure id="attachment_1010" aria-describedby="caption-attachment-1010" style="width: 556px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1010 size-full" src="https://media.huynhhieutravel.com/thanh-co-loa4.jpg" alt="Thành Cổ Loa thời xưa" width="556" height="396"><figcaption id="caption-attachment-1010" class="wp-caption-text">Thành Cổ Loa thời xưa</figcaption></figure></p>
<p>Nghe lời thần mách bảo, Vua sai mấy viên tướng đem quân vào rừng mai phục rồi vua cải trang cùng thần Kim Quy giả làm khách bộ hành đến quán xin ngủ trọ. Chủ quán từ chối lấy cớ là trong núi có nhiều yêu quái hay làm hại khách đi đường. Nhưng An Dương Vương và thần Kim Quy nhất định xin ở. Chủ quán phải chiều theo ý hai người.</p>
<p>Ðêm đêm An Dương Vương nghe thấy những bước chân rầm rập ở ngoài. Những bước chân từ khắp các ngả đi lại rộn ràng rồi thốt nhiên có bàn tay rất mạnh đập vào cái phên nhà lão chủ quán tiếp đến tiếng gọi người con gái lão. Thần Kim Quy lên tiếng nạt nộ, tiếng ngoài im ngay. Những tiếng chân bước cũng xa dần.</p>
<p><figure id="attachment_1008" aria-describedby="caption-attachment-1008" style="width: 450px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1008" src="https://media.huynhhieutravel.com/thanh-co-loa2.jpg" alt="Thành Cổ Loa" width="450" height="338"><figcaption id="caption-attachment-1008" class="wp-caption-text">Thành Cổ Loa</figcaption></figure></p>
<p>Gần sáng lại có những tiếng chân rầm rập ở ngoài, thần Kim Quy bảo An Dương Vương mở cửa phên ra gọi quân mai phuc đuổi theo đám yêu tinh đang rút lui về Thất Diệu, quân lính vừa đuổi vừa giương nỏ bắn theo. Cứ một loạt tên bay đi là lại nổi lên những tiếng ma kêu quỷ khóc rùng rợn.</p>
<p>Tiếng rên rỉ khóc than mỗi lúc một thưa dần. Ðến khi mặt trời mọc thì yêu khí tan. Quân lính của An Dương Vương đào được rất nhiều hài cốt và nhạc khí cổ trong các hang núi, họ chất thành từng đống cao đốt đi rồi tro than đổ xuống suối cho tan hẳn oan hồn.</p>
<h3>Thành công trừ yêu</h3>
<p>An Dương Vương và thần Kim Quy trở về quán trọ bảo chủ quán hiến cho mình con gà trắng để tạ trời đất. Gà vừa bị cắt tiết thì con gái chủ quán cũng lăn ra chết. Giữa lúc ấy có một con chim tứ trong nhà bay vụt ra, thần Kim Quy biết đó là con yêu tinh đã tìm đường chạy trốn, liền tung phép giết chết.</p>
<p><figure id="attachment_1009" aria-describedby="caption-attachment-1009" style="width: 900px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1009 size-full" src="https://media.huynhhieutravel.com/thanh-co-loa3.jpg" alt="Thành Cổ Loa ngày nay" width="900" height="369" srcset="https://media.huynhhieutravel.com/thanh-co-loa3.jpg 900w, https://media.huynhhieutravel.com/thanh-co-loa3-768x315.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" /><figcaption id="caption-attachment-1009" class="wp-caption-text">Thành Cổ Loa ngày nay</figcaption></figure></p>
<p>Yêu ma đã trừ xong, thần Kim Quy lại hiện nguyên hình là con rùa vàng rất lớn. Thần rút một cái móng của mình trao cho An Dương Vương, dặn rằng:</p>
<p>&#8211; Nhà vua giữ lấy móng chân này để làm lẫy nỏ. Khi có giặc thì đem ra bắn, một phát có thể giết được hàng nghìn quân giặc.</p>
<p>Nói xong, thần biến mất, nhờ có thần Kim Quy trừ hết yêu ma. An Dương Vương ra lệnh cho quân lính và nhân dân xây lại thành. Chẳng bao lâu tòa thành đắp xong, rộng tới ngàn trượng, vừa dầy vừa cao xoáy vòng như hình con ốc, nên gọi là Loa thành.</p>
', 'Thành Cổ Loa được xây dựng dưới thời An Dương Vương. Ngôi thành mang ý nghĩa lịch sử to lớn về mặt quân sự cũng như văn hóa. Nó đánh dấu cột mốc quan trọng khi tộc Việt cổ chuyển từ thói quen sống ở miền núi sang ở đồng bằng. Sự tích xây dựng [&hellip;]', 1011, 'post', '2018-06-24 07:29:30', '2023-04-23 12:33:56');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1006, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1006, 64);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1006, 299);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1001, 'An Dương Vương Và Nhà Nước Âu Lạc', 'an-duong-vuong', '<p><strong>An Dương Vương</strong> tên thật là Thục Phán. Ông là vị vua duy nhất của triều đại Âu Lạc. Niên đại trị vì của An Dương Vương theo nhiều sử sách ghi lại là khác nhau. Trong Đại Việt Sử Kỳ Toàn Thư cho rằng thời gian ông làm vua kéo dài trong 50 năm từ năm 257 TCN đến 208 TCN. Trong Sử Ký Tư Mã Thiên lại cho rằng ông làm vua từ 208 TCN đến năm 179 TCN trong 30 năm. Những nghiên cứu này đều có sự sai lệch nhất định. Nhưng ta chắc chắn rằng thời kỳ Âu Lạc và An Dương Vương là có thật. Nó hiện diện rõ ràng trong những di tích và sách lịch sử ghi nhận lại. Không hoàn toàn là truyền thuyết như thời Hùng Vương.</p>
<h2>An Dương Vương</h2>
<p><figure id="attachment_1002" aria-describedby="caption-attachment-1002" style="width: 300px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-1002" src="https://media.huynhhieutravel.com/an-duong-vuong.jpg" alt="an dương vương" width="300" height="400"><figcaption id="caption-attachment-1002" class="wp-caption-text">Tượng An Dương Vương</figcaption></figure></p>
<h3>Nguồn gốc của Âu Lạc</h3>
<p>Trong thời kỳ Lạc Việt của Hùng Vương, có các bộ tôc gọi là Âu Việt. Họ sống xen kẻ cùng người Lạc Việt. Hai bộ tộc đã sống chung từ lâu đời và gần gũi nhau. Sau này khi An Dương Vương lên làm vua đã đổi quốc hiệu thành Âu Lạc.</p>
<h3>Nghi vấn về sự hình thành của Âu Lạc &#8211; Kẻ xâm lược hay sự đồng hóa?</h3>
<p>Sự hình thành của Âu Lạc được đặt dưới sự nghi ngờ và nhiều giả thuyết khác nhau. Âu Lạc đã xâm chiếm Lạc Việt hay là sau những biến cố lịch sử. Đất nước Lạc Việt đã bị Âu Lạc đồng hóa dần?</p>
<h4>Nghi vấn về nguồn gốc của Thục Phán</h4>
<p>Nguồn gốc của Thục Phán, tức An Dương Vương cũng có nhiều tranh cãi. Một số nhà sử học đã cho rằng Thục Phán là hậu duệ của Trung Quốc. Thời nhà Tần thống nhất các quốc gia. Thục Phán là hậu duệ của nhà Thục đã chạy thoát và xuôi Nam. Hình thành nên Âu Việt và sống xen kẻ cùng tộc Lạc Việt.</p>
<p>Tuy nhiên giả thuyết này bị nghi ngờ về độ chính xác. Xét về mặt không gian, từ đất Thục lúc bấy giờ đến miền Bắc Việt Nam cách xa đến 3000km. Và nên nhớ, lúc bấy giờ &#8220;rừng thiêng nước độc&#8221; và những ngọn đồi cao là cản lực rất lớn. Khó có thể di dân 3000km để thành lập nên bộ tộc. Xét về mặt thời gian, An Dương Vương lên ngôi khoảng 200 đến 250 TCN. Nước Thục bị diệt là vào năm 316 TCN. Nên khó có thể Thục Phán &#8211; An Dương Vương là hậu duệ nhà Thục.</p>
<p><strong>Thuyết nước Nam Cương và người Tày Cao Bằng</strong></p>
<p>Thuyết này lấy căn cứ chủ yếu là truyền thuyết “Chín chúa tranh vua” của đồng bào Tày ở Cao Bằng. Truyền thuyết này đã được Rômanê đuy Caiô nêu từ năm 1880, nhưng trong tay chúng ta không còn tài liệu đó của học giả người Pháp này. Câu chuyện được Lã Văn Lô dịch thành thơ tiếng Việt đăng lại trên tạp chí Nghiên cứu Lịch sử số 50 và số 51 năm 1963 . Đây là tài liệu thu thập được của Sở Văn hóa Việt Bắc.</p>
<p>Từ khi truyền thuyết được công bố, một số người nghiên cứu đã hướng về Cao Bằng để tìm quê hương vua Thục. Truyền thuyết áo lông chim của người Tày – Nùng, tục thờ rùa, truyền thuyết rùa dạy làm nhà, phù hộ người, chống ma quỷ của người Tày – Thái. Một vài địa danh tiếng Tày bắt gặp ở khu gần Cổ Loa như làng Viềng (tức Thành) càng tiếp sức cho thuyết vua Thục vốn người Tày làm chúa nước Nam Cương. Mà trung tâm là huyện Hòa An, tỉnh Cao Bằng ngày nay.</p>
<p>Tới nay, vẫn có người tiếp tục đi sâu nghiên cứu. Và suy đoán rằng tộc đảng Thục Vương đó đã định cư miền gần phía nam Tả Giang, lưu vực Hữu Giang cùng miền thượng lưu các sông Lô, sông Gâm, sông Cầu.</p>
<p>Sau cuộc điều tra ở Cao Bằng hồi tháng 7 và 8 năm 1969, các đồng chí Đỗ Đình Truật và Phạm Như Hồ, viện Khảo cổ học, đã cung cấp những tư liệu có phần khác. Người sưu tầm và viết lại truyền thuyết này là ông Lê Bỉnh Sư (còn có tên là Lê Đình Sự). Người Kinh vốn ở Nghĩa Lộ, sau năm 1947 mới dời về ở tại huyện Hòa An (Cao Bằng). Chính ông Lê Bỉnh Sư kể lại rằng chuyện do ông sắp xếp lại, có sửa ít nhiều cho các chi tiết được hợp lý. Gốc chuyện là do ông chú ngày trước kể, nay nhớ lại mà viết để dự cuộc thi văn nghệ do Sở Văn hóa Việt Bắc tổ chức.</p>
<p>Câu chuyện của truyền thuyết dân gian là những phần nào. Và chi tiết nào là thuộc phần sửa chữa của ông Sư? Chưa có chi tiết để làm sáng tỏ. Đỗ Đình Truật và Phạm Như Hồ đã tìm gặp một số cụ già địa phương để xác minh truyền thuyết. Nhưng không một ai biết chút nào. Vấn đề còn ở tình trạng chưa được sáng tỏ. Như vậy, truyền thuyết này không thể đã được coi là căn cứ đáng tin cho một kết luận khoa học. Và công việc phải tiến hành tức là tiếp tục điều tra lại để xác minh truyền thuyết.</p>
<p><strong>Thuyết Ai Lao Di</strong></p>
<p>Tác giả đã căn cứ vào truyền thuyết Sơn Tinh – Thủy Tinh, nghiên cứu một khối lượng khá lớn thần phả, ngọc phả, tục hèm có liên quan. Thấy rằng Sơn Tinh (tức Thánh Tản viên) là một nhân thần, là người đã có công giúp vua Hùng đánh Thục trong cuộc chiến tranh chống Thục. Đã “được phản ánh một cách rất đậm nét, rất cụ thể trong những truyền thuyết về thời Hùng Vương”. Và “giặc Thục ở đây còn được gọi là giặc Ai Lao, Thục Phán đã từ Ai Lao đến xâm lược Văn Lang”.</p>
<p>Từ truyền thuyết đối chiếu qua thư tịch, đặc biệt Nam Man Tây Nam di truyện trong bộ Hậu hán thư và Thuật dị ký. Tác giả đã tìm ra Tây Thục tức Ai Lao Di, tức nước Thục của thục Phán. “Đó là một nước đã tồn tại thật sự trong lịch sử: nước Tây Thục (tức Ai Lao)… ở phía Tây Bắc nước ta ngày nay”. “Cuối đời vua Hùng, Thục Phán đã từ đây mà xuống xâm lược nước ta. Đó là một cuộc chiến tranh dai dẳng và khốc liệt, cuối cùng nước Văn Lang bị diệt”. “Nước Tây Thục (Ai Lao) ở sát nước ta về phía tây bắc.</p>
<p>Nó nằm trên trục giao thông chủ yếu của nước ta với miền Tây Nam Di là thung lũng sông Hồng, sông Lô. Tây Thục cũng là một trạm trung gian trên con đường giao thông quốc tế thời cổ giữa Trung Quốc với các nước phía tây như Ấn Độ cổ đại”. Tác giả còn có phần chỉ cụ thể: “Đến đời Hán Minh Đế (58), Ai Lao thuộc hẳn nhà Hán. Nhà Hán lấy đất đó phân làm hai huyện Ai Lao và Bắc Nam, sau đổi thành Vĩnh Xương, nay là châu tự trị Đức Hoằng thuộc tỉnh Vân Nam (Trung Quốc) hiện nay”.</p>
<p><strong>Thuyết người Lạc Việt nói chung</strong></p>
<p>Từ chỗ chứng minh rằng Tây Âu, Tây Âu Lạc hay Âu Lạc là một nước có địa bàn chủ yếu nằm ở lưu vực sông Hồng ngày nay, trùng với bộ phận của địa bàn rộng lớn của Lạc Việt. Nó bao gồm từ lưu vực sông Hồng tới lưu vực Tây Giang ngày nay, tác giả chủ trương nước Tây Âu của người Lạc Việt,.“Trong Lạc Việt có nhiều dân tộc (theo đúng nghĩa dân tộc học ngày nay) có quan hệ lịch sử, huyết thống nào đó với nhau”.</p>
<p>Đối với thuyết Ai Lao Di, tác giả cho rằng “những thần tích ghi về việc Thục Phán cai trị ở Ai Lao là những tài liệu do người sau viết”. Về việc giao lưu giữa Giao Châu và Ích Châu thì “chỉ hạn chế đến Điền, không vượt qua khỏi Điền đến Ai Lao Di bao giờ. Ai Lao Di cũng chưa từng trở thành một nước hùng mạnh và có xu thế phát triển về phía Giao Châu bao giờ”.</p>
<p>“Văn hóa phương Bắc vào Giao Chỉ không phải qua con đường Ai Lao Di. Con đường qua Ai Lao Di là một con đường đi Thân Độc Quốc (Ấn Độ), nhưng con đường cũng chỉ đánh thông được rất muộn về sau. Thời Tần – Hán, Điền là bức thành chắn ngang đường giao lưu giữa Trung Quốc và Miến Điện, Ấn Độ ngày nay.</p>
<p>Tất cả những điều nghiên cứu trên dẫn tới việc không công nhận tên trước Âu lạc hình thành do sự sáp nhập của hai tộc Âu lạc và tộc Lạc. Mà tên nước này đã xuất hiện ngay từ trước khi thời Hùng Vương kết thúc.</p>
<p><strong>Âu Lạc đã là một nhà nước thật sự</strong></p>
<p>Thời gian nghiên cứu gần đây, vấn đề này chưa được bàn tới nhiều. Những ý kiến đã chính thức công bố nêu ra đây không phải khác nhau về điểm Âu Lạc đã là một nhà nước thật sự. Mà khác nhau ở chỗ Nhà nước Âu Lạc đã xuất hiện trên cơ sở trình độ sản xuất của thời đại đồng hay thời đại sắt.</p>
<p>Những mũi tên đồng Cầu Vực được coi là vật tiêu biểu của “văn hóa đồ đồng ở giai đoạn Âu Lạc”. Và “văn hóa vật chất của tổ tiên ta ở thời An Dương Vương vẫn chưa khác văn hóa vật chất ở thời Hùng Vương bao nhiêu, căn bản vẫn là văn hóa đồ đồng”. Đây là một trong những lập luận cho rằng nước Âu Lạc là một nhà nước của thời đại đồng.</p>
<p>Một ý kiến khác cho rằng “những di tích văn hóa vật chất thời An Dương Vương còn để lại trên khu di tích Cổ Loa đã được tìm thấy một số: như những lưỡi cày đồng ở xóm Nhồi, kho mũi tên đồng với hàng vạn chiếc mà chúng ta đều biết và có thể là lớp dưới của tầng văn hóa ở di chỉ Bãi Mèn”. Tuy rằng người viết không nói rõ, nhưng ta hiểu ý đó nói rằng thời kỳ lịch sử An Dương Vương thuộc thời đại đồng thau.</p>
<p>Di chỉ Đường Mây được phát hiện và khai quật 2 lần vào năm 1970. Nhiều cục sắt và mảnh hiện vật bằng sắt được tìm thấy, trên cơ sở đó di chỉ được tạm định thuộc sơ kỳ thời đại sắt. Đặc biệt, di chỉ Đường Mây nằm trên một doi đất cao tự nhiên ven sông Hoàng và ven bờ đầm cả và ngay dưới chân thành ngoài của thành Cổ Loa. Từ lẽ đó, người khai quật di chỉ này quả quyết rằng “nó (Đường Mây) thuộc về một thời đại trực tiếp trước thời đại của thành Cổ Loa.</p>
<p>Khi tiến hành xây thành, người ta đã đắp lũy (thành ngoài) phủ lên trên khu di chỉ này. Biến quả gò trên đó trước đây có cư dân sinh sống thành một bộ phận của thành ngoài. Vì di chỉ ấy thuộc về sơ kỳ thời đạt sắt cho nên thời hạn niên đại dưới của thành Cổ Loa không thể xưa hơn sơ kỳ thời đại sắt. Thành Cổ Loa là một công trình của thời đại sắt Việt Nam. Điều đó bác bỏ luận điểm cũ của nhiều nhà sử học và khảo cổ học nói rằng thành Cổ Loa thuộc về thời đại đồng thau phát đạt của Việt Nam”.</p>
<p>Nghiên cứu sâu hơn nữa về nước Âu Lạc, tác giả của ý kiến Cổ Loa chỉ có thể là kinh thành của một nhà nước Việt Nam thời cổ, có trước đời Hán… Nhà nước đó, theo sử cũ là Nhà nước Âu Lạc của An Dương Vương”. Từ đó tác giả còn rút ra kết luận: “Nước Âu lạc do An Dương Vương lập đã là một nhà nước thật sự”.</p>
<p>Sự phân hóa giai cấp là rõ rệt. “Tầng lớp vua chúa quý tộc ở nhà ngói sân gạch”. Xã hội này đã có trình độ phát triển kinh tế cao, có quyền lực xã hội mạnh mẽ, kỹ thuật xây dựng cao, trình độ tổ chức cao, và có mức phát triển cao, của trí tuệ và tài năng sáng tạo, có trình độ nghệ thuật quân sự rất cao.</p>
<p>Một ý kiến khác cho rằng “văn hóa Âu Lạc” tồn tại chừng 100 năm trước khi nước Âu Lạc bị tiêu diệt, nghĩa là “văn hóa Âu Lạc” có hơn nửa thế kỷ song song tồn tại với “văn hóa Văn Lang” và thuộc thời đại sắt.</p>
<p>Với nhiều giả thuyết mơ hồ đặt ra, ta chỉ có thể khẳng định Thục Phán là lãnh đạo của tộc Âu Việt. Cư trú ở thượng du hay chính xác hơn là gần tỉnh Cao Bằng &#8211; Việt Nam lúc bây giờ.</p>
<h3>Lĩnh Nam Chích Quái cho rằng đó là sự đồng hóa</h3>
<p>Truyền thuyết “Họ Hồng Bàng” trong sách Lĩnh Nam chích quái cũng phản ánh phần nào cuộc tiếp xúc và đụng độ của người Việt với người Hoa Hạ ở phương Bắc. Sách có chép” Dân phương Nam khổ vì bị người phương Bắc quấy nhiễu, không được yên sống như xưa…”. Nước Tần thành lập năm 221 TCN đã mở rộng những cuộc chiến tranh xâm lược đại quy mô ra cả hai phía bắc, nam thành lập một đế chế rộng lớn đầu tiên trong lịch sử Trung Quốc. Về phía Nam tiếp tục kế thừa và phát triển chủ trương ” bình Bách Việt” của nước Sở trước đây.</p>
<p>Tần Thủy Hoàng đã sai 50 vạn quân xâm lược đất đai của Bách Việt ở phía Nam Trường Giang. Hàng vạn quân Tần vượt biên giới tràn vào lãnh thổ phía Bắc và đông bắc nước ta lúc đó. Lúc này hai tộc người Lạc Việt và Âu Việt (Tây Âu) vốn gần gũi về dòng máu, về địa vực cư trú, về kinh tế và văn hóa lại có điều kiện liên kết chặt chẽ lại với nhau hơn trong cuộc chiến đấu chống kẻ thù chung. Theo sách Hoài Nam Tử,&nbsp;<i>“lúc đó người Việt đều vào rừng ở với cầm thú, không ai chịu để quân Tần bắt”, và “họ cùng nhau đặt người kiệt tuấn lên làm tướng để ban đêm ra đánh quân Tần”</i>&nbsp;.</p>
<p>Đó là hình thức phôi thai của lối đánh du kích và thông qua lối đánh này mà lực lượng kháng chiến của người Việt ngày càng lớn mạnh; còn quân Tần dần dần bị dồn vào thế nguy khốn và tuyệt vọng. Trên đà chiến thắng, người Việt tập hợp lực lượng tổ chức đánh lớn nhằm tiêu diệt sinh lực địch, đại phá quân Tần, giết chết chủ tướng Đồ Thư, buộc nhà Tần phải bãi binh. Đây là thắng lợi oanh liệt đầu tiên của cả dân tộc ta chống lại họa xâm lược của phong kiến phương Bắc.</p>
<p>Trong cuộc chiến đấu này, vai trò và uy tín của Thục Phán, người thủ lĩnh kiệt xuất của liên minh bộ lạc Tây Âu ngày càng được nâng cao, không chỉ ở trong bộ lạc Tây Âu mà còn có ảnh hưởng sâu rộng trong bộ lạc Lạc Việt. Sau khi cuộc kháng chiến kết thúc thắng lợi, trong điều kiện cộng đồng cư dân Lạc Việt – Tây Âu đã hình thành và uy tín ngày càng cao của Thục Phán.</p>
<p>Thục Phán đã thay thế Hùng Vương, tự xưng là An Dương Vương, lập ra nước Âu Lạc. Sách&nbsp;<i>Việt sử lược</i>&nbsp;chép rằng&nbsp;<i>“Hùng Vương bị con vua Thục là Phán đánh đuổi mà lên thay”</i>&nbsp;. Còn một số thần tích và truyền thuyết dân gian lại cho rằng sau nhiều cuộc xung đột, cuối cùng Hùng Vương theo lời khuyên của con rể là Thánh Tản Viên đã nhường ngôi cho Thục Phán.</p>
<h3>Xây thành Cổ Loa</h3>
<p>Sau chiến thắng trước quân Tần, An Dương Vương quyết định giao cho tướng Cao Lỗ xây thành Cổ Loa nhằm củng cố thêm khả năng phòng thủ quân sự. Tục truyền rằng thành xây nhiều lần nhưng đều đổ. Sau có thần Kim Quy hiện lên, bò quanh bò lại nhiều vòng dưới chân thành. Thục An Dương Vương bèn cho xây theo dấu chân Rùa vàng. Từ đó, thành xây không đổ nữa. An Dương Vương cũng phát triển thuỷ binh và cho chế tạo nhiều vũ khí lợi hại, tạo lợi thế quân sự vững chắc cho Cổ Loa.</p>
<p>Di tích của thành Cổ Loa vẫn còn lưu lại cho đến nay, cách trung tâm Hà Nội khoảng 20km về phía đông bắc. Đền thờ An Dương Vương nằm ở trung tâm di tích này. Các nghiên cứu khảo cổ học tại đây vẫn tiếp tục làm sáng tỏ các thời kỳ lịch sử mà thành đã trải qua.</p>
<h3>Mắc mưu và sự sụp đổ của nhà nước Âu Lạc</h3>
<p>Triệu Đà buộc phải dùng kế nội gián bằng cuộc kết hôn giữa con trai mình là Trọng Thủy và con gái An Dương Vương là Mỵ Châu. Sau khi nắm được bí mật quân sự của An Dương Vương thông qua con trai, Triệu Đà đã thành công trong việc chinh phục Âu Lạc, buộc An Dương Vương bỏ chạy và tự tử, kết thúc thời kỳ An Dương Vương.</p>
<p>Về năm mất của triều đại An Dương Vương, các tài liệu ghi chép khác nhau. Đa phần sách sử Việt Nam&nbsp; đều chép là An Dương Vương mất nước năm 208 TCN. Sách giáo khoa của Việt Nam căn cứ vào Sử ký của Tư Mã Thiên ghi nước Âu Lạc mất năm 179 TCN. Sở dĩ như vậy vì Sử Ký chép là Triệu Đà diệt nước Âu Lạc “Sau khi Lã Hậu chết”, mà Lã Hậu chết năm 180 TCN, do đó nước Âu Lạc mất khoảng năm 179TCN.</p>
<h3>Giá trị lịch sử to lớn</h3>
<p>Nước Âu Lạc của An Dương Vương chỉ tồn tại trong khoảng thời gian ngắn (khoảng gần 30 năm), nhưng nó cũng đã có những đóng góp to lớn vào trong tiến trình phát triển của lịch sử đất nước. Thời kỳ Âu Lạc được đưa vào thời kỳ lập nước của sử Việt.</p>
', 'An Dương Vương tên thật là Thục Phán. Ông là vị vua duy nhất của triều đại Âu Lạc. Niên đại trị vì của An Dương Vương theo nhiều sử sách ghi lại là khác nhau. Trong Đại Việt Sử Kỳ Toàn Thư cho rằng thời gian ông làm vua kéo dài trong 50 năm [&hellip;]', 1045, 'post', '2018-06-22 08:54:15', '2023-04-23 12:33:57');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1001, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1001, 64);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (995, 'Bàn về 18 đời vua Hùng &#8211; Truyền thuyết và những phân tích của sử gia', '18-doi-vua-hung', '<p>18 đời vua Hùng kéo dài trong 2622 năm (Từ 2879 TCN đến 258 TCN). Không thể phủ nhận các đời vua Hùng là thủy tổ của người Việt. Nhưng bên trong đó còn rất nhiều giả thuyết và những nghi ngờ về sự chính xác trong đó. Nếu chia 2622 năm kéo dời của 18 đời vua Hùng. Thì mỗi đời có trung bình 145,666 năm. Nó lớn hơn hẳn tuổi thọ trung bình của người Việt thời bấy giờ. Và còn nhiều câu hỏi được đặt ra hơn nữa. Hãy cũng Huynh Hieu Travel tìm hiểu hết những câu chuyện, phân tích và giải đáp những thắc mắc về vua Hùng.</p>
<h2>18 Đời Vua Hùng &#8211; Những Bí Ẩn Cần Được Giải Đáp</h2>
<h3>Nguồn gốc vua Hùng &#8211; truyền thuyết 100 bọc trứng</h3>
<p>Nhắc đến nguồn gốc của vua Hùng phải kể đến thời Lộc Tục. Lộc Tục còn có hiệu là Kinh Dương Vương. Kinh Dương Vương là người cai quản những bộ lạc ở phương Nam. Sau đó ông lấy Thần Long, rồi sinh ra Lạc Long Vương.</p>
<p><em>Tìm hiểu về Kinh Dương Vương:&nbsp;<a href="http://bit.ly/2tqyAbi">http://bit.ly/2tqyAbi</a></em></p>
<p>Sau đó Lạc Long Quân thay cha cai quản miền đất phía Nam. Nhìn thấy Âu Cơ xinh đẹp, Lạc Long Quân biến thành chàng trai dũng mạnh, rước nàng về làm vợ. Hai người ở với nhau một năm, Âu Cơ sinh ra 100 bọc trứng. 100 bọc trứng nở ra 100 người con trai anh dũng.</p>
<p><em>Tìm hiểu về Lạc Long Quân:&nbsp;<a href="https://huynhhieutravel.com/lac-long-quan/">https://huynhhieutravel.com/lac-long-quan/</a></em></p>
<p>Lạc Long Quân nói:&#8221;Ta là loài rồng, sinh trưởng ở thủy tộc; nàng là giống tiên, người trên đất, vốn chẳng như nhau, tuy rằng khí âm dương hợp mà lại có con nhưng phương viên bất đồng, thủy hỏa tương khắc, khó mà ở cùng nhau trường cửu. Bây giờ phải ly biệt, ta đem năm mươi con trai về Thủy phủ, phân trị các xứ, năm mươi con trai theo nàng ở trên đất, chia nước mà cai trị, dù lên núi xuống nước nhưng có việc thì cùng nghe không được bỏ nhau&#8221;.</p>
<p><figure id="attachment_993" aria-describedby="caption-attachment-993" style="width: 1000px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-993" src="https://media.huynhhieutravel.com/lac-long-quan-va-au-co.jpg" alt="Lạc Long Quân và Âu Cơ" width="1000" height="744" srcset="https://media.huynhhieutravel.com/lac-long-quan-va-au-co.jpg 1000w, https://media.huynhhieutravel.com/lac-long-quan-va-au-co-768x571.jpg 768w" sizes="(max-width: 1000px) 100vw, 1000px" /><figcaption id="caption-attachment-993" class="wp-caption-text">Minh họa Lạc Long Quân và Âu Cơ</figcaption></figure></p>
<p>Từ đó, Lạc Long Quân đem 50 người con ra biển. Âu Cơ mang 50 người con lên núi ở tại Phong Châu. Đưa người con trưởng lên làm vua, tự là Hùng Vương.</p>
<h3>Phân chia nhà nước thời vua Hùng</h3>
<p>Quốc hiệu khi vua Hùng lên ngôi đặt là Văn Lang. Vua Hùng chia Văn Lang thành 15 bộ: Giao Chỉ, Chu Diên, Vũ Ninh, Phúc Lộc, Việt Thường, Ninh Hải, Dương Tuyền, Lục Hải, Vũ Định, Hoài Hoan, Cửu Chân, Bình Văn, Tân Hưng, Cửu Đức; đóng đô ở bộ Văn Lang, Phong Châu.</p>
<p>Vua Hùng đặt em thứ làm Tướng võ, Tướng văn. Tướng văn gọi là Lạc Hầu, Tướng võ là Lạc Tướng, con trai vua gọi là Quan Lang, con gái vua gọi là Mị Nương, quan Hữu ty gọi là Bố chính, thần bộc nô lệ gọi là nô tỳ, xưng thần là khôi, đời đời cha truyền con nối gọi là phụ đạo, thay đời truyền nhau cho đến hiệu là Hùng Vương không đổi.</p>
<p>Về ngoại giao vua Hùng có chính sách hòa hữu với Trung Quốc. Ông từng đem nhiều lễ vật sang tặng một số đời vua Trung Quốc.</p>
<h3>Sự thật về 18 đời vua Hùng &#8211; Chi tiết và nhận định</h3>
<p>18 đời vua Hùng trị vì hơn 2622 năm. Xét về mặt thời gian là khó khả thi. Mỗi đời vua sẽ kéo dài trung bình đến gần 150 năm. Điều vô lý này đã gây ra nhiều tranh cãi trên các diễn đàn lịch sử khác nhau. Nhưng nếu nhìn nhận theo một góc độ khác thì nó lại trở nên có lý.</p>
<p>Theo nhận định trong “Hùng Vương sự tích ngọc phả cổ truyện” do Nguyễn Như Đỗ thời nhà Hậu Lê.&nbsp; Thì chữ “đời” vua thường hay dùng phải hiểu là chữ “thế” trong Hán tự, nghĩa là không phải là một đời người mà là “một dòng gồm nhiều đời” hay “chi”. “Hùng Vương sự tích ngọc phả cổ truyện” chép rằng thời đại Hùng Vương kéo dài 2.622 qua 47 đời vua trị vì với 18 chi, mỗi một chi qua mấy đời vua. Mà “chi” đầu tiên lại được chép là Kinh Dương Vương.</p>
<p>18 chi được sắp theo bát quái (8 quái): 1 Càn (trời) (☰), 2 Đoài (đầm) (☱), 3 Ly (hỏa) (☲), 4 Chấn (sấm) (☳), 5 Tốn (gió) (☴), 6 Khảm (nước) (☵), 7 Cấn (núi) (☶), 8 Khôn (đất) (☷) và 10 thiên can Giáp, Ất, Bính, Đinh, Mậu, Kỷ, Canh, Tân, Nhâm, Quý.</p>
<p>18 chi thời Vua Hùng theo “Hùng Vương sự tích ngọc phả cổ truyện” lần lượt là:</p>
<ul>
<li>Chi Càn: Kinh Dương Vương, sinh năm nhâm ngọ 2919 TCN. Trị vì 86 năm từ Nhâm Tuất 2879 TCN đến Đinh Hợi 2794 TCN.</li>
<li>Chi Khảm: Lạc Long Quân tên húy là Sùng Lãm tức Hùng Hiền Vương. Chi này kéo dài 269 năm từ Mậu Tý 2793 đến Bính Thìn 2525 TCN. Thời kỳ này được truyện cổ tích họ “Hồng Bàng truyền kỳ” gọi là huyền sử Rồng Tiên.</li>
<li>Chi Cấn: Hùng Quốc Vương tên húy là Hùng Lân kéo dài 271 năm, từ 2524 đến 2253 TCN. Thời kỳ này theo truyền thuyết thì mẹ Âu dẫn 50 con (Tức 50 tộc người Bách Việt) ở lại vùng cao rồi cùng nhau suy cử người con trưởng lên làm vua, lấy hiệu là Hùng vương đóng đô ở Châu Phong. Cũng từ năm 2524 tên nước được đổi thành Văn Lang.</li>
<li>Chi Chấn: Hùng Hoa Vương tên húy là Hùng Bửu Lang, chi này kéo dài 342 năm.</li>
<li>Chi Tốn: Hùng Hi Vương tên húy là Bảo Long, chi này kéo dài 200 năm.</li>
<li>Chi Ly: Hùng Hồn Vương, tên húy là Long Tiên Lang, chi này gồm 2 đời vua, kéo dài 81 năm.</li>
<li>Chi Khôn: Hùng Chiêu Vương, tên húy là Quốc Lang, sinh năm 1659 TCN, lên ngôi năm 12 tuổi, gồm 5 đời vua, dài 200 năm.</li>
<li>Chi Đoài: Hùng Vĩ Vương, tên húy là Văn Lang, chi này gồm 5 đời vua kéo dài 100 năm. Thời kỳ này, truyền kỳ lịch sử kể rằng giặc Ân sang đánh nước ta bị Phù Đổng Thiên Vương đánh cho tan tác. Sử Trung Quốc ghi là đời Cao Tông triều Ân đánh nước Quỷ Phương 3 năm đóng quân ở đất Kinh.</li>
<li>Chi Giáp: Hùng Định Vương, tên húy là Chân Nhân Lang, Chi này gồm 3 đời vua, kéo dài 80 năm.</li>
<li>Chi Ất: Hùng Uy Vương tên húy là Hoàng Long Lang, gồm 3 đời vua dài 90 năm.</li>
<li>Chi Bính: Hùng Trinh Vương húy Hưng Đức Lang, chi này gồm 4 đời vua kéo dài 107 năm.</li>
<li>Chi Đinh: Hùng Vũ Vương tên húy Đức Hiền Lang, gồm 3 đời vua, kéo dài 96 năm.</li>
<li>Chi Mậu: Hùng Việt Vương, tên húy là Tuấn Lang, chi này gồm 5 đời vua, kéo dài 105 năm.</li>
<li>Chi Kỷ: Hùng Anh Vương, tên húy là Viên Lang, gồm 4 đời vua, dài 89 năm.</li>
<li>Chi Canh: Hùng Triệu Vương, tên húy là Chiêu Lang, chi này gồm 3 đời vua, kéo dài 94 năm.</li>
<li>Chi Tân: Hùng Tạo Vương, tên húy là Đức Quân Lang, chi này gồm 3 đời vua, kéo dài 92 năm. Trong “Hùng Triều Ngọc Phả”, Thần Phả xã Tiên Lát, huyện Việt Yên, tỉnh Hà Bắc có ghi rõ là đến đời Hùng Vương thứ 16 dời đô xuống Phong Châu Thượng.</li>
<li>Chi Nhâm: Hùng Nghi Vương, tên húy Bảo Quang, lên ngôi năm 9 tuổi, gồm 4 đời vua, dài 160 năm.</li>
<li>Chi Quý: Hùng Duệ Vương, tên húy là Huệ Vương Lang, lên ngôi năm 14 tuổi, chi này gồm 3 đời vua, từ năm 337 TCN đến năm 258 TCN, tức là được 79 năm.</li>
</ul>
<h3>Tại sao mùng 10 tháng 3 là ngày giỗ vua Hùng?</h3>
<p>Phải chăng vua Hùng đầu tiên mất vào ngày mùng 10 tháng 3? Hay triều đại kết thúc vào mùng 10 tháng 3? Những ghi chép lịch sử ghi nhận lại thì những giả thuyết đó đều không thuyết phục.</p>
<ul>
<li>Giả thuyết thứ 1: Trong văn hóa người Việt thì chúng ta được xem là con rồng cháu tiên. Rồng là thìn, mà tháng 3 là tháng của rồng &#8211; tháng Thìn. 10 thiên can được đặt tên cho 10 đời vua Hùng vì thế lấy ngày 10 là ngày giỗ.</li>
<li>Giả thuyết thứ 2: Trước đây ngày giỗ vua Hùng không được xác định rõ ràng. Nhiều nơi làm lễ giỗ nhiều ngày khác nhau theo bản mệnh tốt từng vùng. Thường là vào những ngày xuân thu. Lễ cúng Tổ ở địa phương thì lại được cử hành vào ngày 12.3 âm lịch kết hợp với thờ Thổ kỳ. Thường khi con cháu ở xa về sẽ làm giỗ trước một ngày chứ không mở hội lớn với quy mô toàn quốc. Nhận thấy điều này, Tuần phủ Phú Thọ ông Lê Trung Ngọc vào năm 1917 (niên hiệu Khải Định năm thứ nhất) đã làm bản tấu trình lên Bộ Lễ, xin định lệ lấy ngày 10.3 âm lịch hàng năm làm ngày Quốc tế.&nbsp;Từ đó về sau, cứ vào ngày 10.3 nhân dân cả nước lại hướng về vùng đất Cội nguồn &#8211; xã Hy Cương, Lâm Thao, Phú Thọ để tôn vinh công lao của các vị vua Hùng.</li>
</ul>
<h3>Kinh Tế Thời Hùng Vương</h3>
<p>Vào thời kỳ này săn bắt hái lượm vẫn giữ vai trò quan trọng trong đời sống kinh tế của người dân Lạc Việt. Nhưng nghề nông và đánh bắt đã bắt đầu có bước phát triển vượt bật. Kể cả câu chuyện truyền thuyết 100 bọc trứng vẫn có nói 50 người con xuống biển.</p>
<p>Thuở bấy giờ, người dân khi đi đánh bắt thường bị nhiều loài cá dữ sát hại. Vua Hùng dạy dân cách xăm mình những con cá dữ như cá sấu để chúng tưởng là đồng loại mà không sát hại. Từ đó tộc Việt bắt đầu có tục xăm mình. Tục này kéo dài đến vua Trần Anh Tông (năm 1293 &#8211; năm 1314) mới bắt đầu thoái trào.</p>
<p>Nghề rèn cũng bắt đầu phát triển mạnh mẽ hơn nhờ sự phát triển của ngư nghiệp. Những lưỡi câu bằng đồng, mũi lao có ngạnh bằng xương được sản xuất để người dân chống chọi với lũ cá dữ.</p>
<p>Người dân bắt đầu trồng lúa và vua Hùng cũng hay thường lên núi hàng năm để cầu vụ mùa bội thu.&nbsp;Chỗ núi vua lên khấn vái lúa về sau được gọi là núi Hùng (thuộc xã Hy Cương, huyện Phong Châu, Vĩnh Phú). Lúc bấy giờ những ruộng lúa thời vua Hùng gọi là ruộng Lạc (Chỉ những chỗ đồng bằng trũng nằm ven sông Hồng, sông Mã). Dân theo thủy triều lên xuống mà làm ruộng theo vụ, gọi là Lạc dân.</p>
<p>Lạc dân dùng phương pháp thủy nậu để cấy lúa bằng cách lấy chân đạp cho cỏ sụt bùn rồi mới lấy cấy lúa lên. Ban đầu là những giống lúa hoang. Dần về sau được lai tạo và chọn lọc thành những hạt gạo nếp dẻo thơm ngon hơn. Và sau này người dân còn mở rộng trồng các loại rau và nông sản khác.</p>
<p>Kỹ thuật luyện kim phát triển mạnh, cư dân Lạc Việt đã biết làm ra những công cụ sản xuất bằng kim loại như rìu đồng. Và quan trọng nhất là cày đồng và lưỡi hái bằng đồng ảnh hưởng mạnh đến sinh hoạt nông nghiệp. Lưỡi cày thời ấy có hình cánh bướm hoặc hình tam giác.</p>
<p>Những dụng cụ sinh hoạt như mâm đồng, đục, kim dao, lưỡi câu, chuông và đồ trang sức cũng được sản xuất với số lượng đáng kể. Ngoài ra, thời Lạc Việt đã có nghề luyện sắt (di tích Gò Chiền Vậy) và nghề gốm.</p>
<h3>Cư Trú</h3>
<p>Nhà được dựng theo kiểu nhà sàn. Nguyên liệu là gỗ, tre, nứa, lá. Nhà có mái cong hình thuyền hoặc mái tròn và sàn thấp. Nhà chưa có vách, đuôi mái gối sát sàn nhà. Cầu thang lên đặt trước nhà. Các ngôi nhà được bố trí quây tụ ở ven đồi, đỉnh gò, chân núi, nếu gần sông suối thì nằm trên các giải đất cao để tránh lụt lội.</p>
<h3>Trang phục</h3>
<p><strong>Đầu tóc</strong> để 3 kiểu chính: Cắt ngang vai cho cả nam và nữ, búi tóc lên đầu cho cả nam và nữ, riêng kiểu tóc kết đuôi sam và có vành khăn nằm ngang trán thì chỉ dùng cho phụ nữ.</p>
<p>Về <strong>mặc</strong> thì nam nữ đã có trang phục riêng:&nbsp;Nữ mặc váy, thân để trần, đi chân đất. Váy có hai kiểu là kín và mở, ngắn đến đầu gối, có khi có đệm váy. Phụ nữ giàu có ăn mặc có phần chải chuốt hơn, khăn chóp nhọn trùm lên búi tóc, đủ cả váy, áo và yếm, áo cánh xẻ ngực, thắt lưng có trang trí. Váy kín có trang trí, buông chùng đến gót chân, đệm váy có hình chữ nhật cũng có trang trí, thả trước bụng hay sau mông.</p>
<p>Nam đi chân không, ở trần, mặc khố. Khố có hai kiểu, kiểu quấn một vòng và kiểu quấn hai vòng. Có đuôi thả đàng sau.</p>
<p>Trang phục lễ hội không phân biệt nam nữ. Thường là váy kết bằng lá hay bằng lông vũ. Mũ kết bằng lông chim có cắm thêm bông lau ở phía trên hoặc phía trước.</p>
<p><strong>Đồ trang sức</strong>: người thời Hùng Vương cả nam lẫn nữ đều rất ưa thích dùng đồ trang sức. Nam cũng như nữ đều đeo vòng tai. Ngoài ra, các trang sức hạt chuỗi, nhẫn và vòng tay rất phổ biến. Hình dáng của vòng tay rất đa dạng: hình vành khăn, hình tròn, hình tròn có mấu. Hạt chuỗi có hình trụ, hình trái xoan, hình tròn. Vòng nhẫn hình tròn hoặc hình bện thừng. Vòng tay có tiết diện chữ nhật, hình ống, hoặc có cánh.</p>
<p>Chất liệu của các đồ trang sức là những kim loại cao cấp như vàng bạc. Thường là bằng đá, đồng thau, rất ít khi bằng ngọc nhưng được tạo thành với khiếu thẩm mỹ cao.</p>
<h3>Ăn uống</h3>
<p>Thức ăn chính là gạo nếp tẻ, đã có dụng cụ bếp núc như nồi, chõ. Sách Lĩnh Nam Chích Quái ghi lại là dân Lạc đã biết làm mắm: &#8220;Lấy cầm thú, cá, ba ba làm mắm&#8221;. Họ cũng biết làm rượu, làm bánh. Thức ăn thường là cá, gà, vịt, chim, heo, chó, trâu, hươu, nai, cáo, khỉ, ba ba, rùa, cua ốc&#8230; với các hương liệu: gừng muối, trầu cau, đất hun.</p>
<h3>Văn Hóa</h3>
<p><strong>Hôn nhân:&nbsp;</strong>Có một số tục lệ như lấy gói đất, gói muối tượng trưng cho tình nghĩa vợ chồng. Vì thế có câu: &#8220;Tục hôn nhân lấy gói đất (hoặc lấy gói muối) làm đầu&#8221;. Một số nghi thức khác trong hội lễ ghi nhận được là ném bùn, ném đất và hoa quả vào người chàng rể. Nghi thức chủ yếu nhất là hai vợ chồng mới ăn chung bát cơm nếp. Sau khi ăn bát cơm nếp, họ được cộng đồng công nhận là vợ chồng.</p>
<p><strong>Tang ma:&nbsp;</strong>Khi trong nhà có người chết, người ta giã vào cối, đó là tín hiệu thông tin cho hàng xóm, láng giềng biết để đến giúp đỡ. Người chết có quyền đem theo một số tài sản để sử dụng trong cuộc sống khác. Các đồ tùy táng là những đồ dùng hàng ngày và đồ trang sức.Thời ấy người chết được hỏa táng hay được chôn cất. Các nhà khảo cổ học đã đào được các quan tài độc mộc. Đó là một thân cây khoét rỗng có hình dáng giống như chiếc thuyền độc mộc.</p>
<p><strong>Một số phong tục khác</strong> như:&nbsp;Khi trẻ sơ sinh ra đời, dân Lạc có tục lệ lót ổ cho trẻ bằng lá chuối tươi. Khi trẻ lớn lên được làm lễ thành đinh, Lễ thành đinh mang tính thử thách năng lực của các thanh niên, thường được tổ chức những buổi thi tài trong các ngày hội. Sau lễ thành đinh, thanh niên trở thành thành viên lao động mới của xã hội.</p>
<p><strong>Vẽ</strong>: Nghệ thuật vẽ đã rất phổ biến với các hoa văn đa dạng trên các đồ gốm, trên các trống đồng. Không những thế cư dân Văn Lang đã biết dùng màu để vẽ. Tục xăm mình là một minh chứng về nghệ thuật vẽ màu của người Văn Lang.</p>
<p>Đề tài chính của nghệ thuật này là con người đang hoạt động, đang sống hồn nhiên. Đó là quang cảnh nhảy múa, thổi khèn, giã cối&#8230; hoặc là quan hệ giữa con người và thiên nhiên. Mặt trống đồng như một vũ trụ mà trung tâm là mặt trời. Hoạt động của con người quây tròn chung quanh mặt trời đang tỏa sáng.</p>
<p><strong>Tạc tượng</strong>: Chất liệu là đất nung, đồng thau, đá&#8230; những bức tượng mang dáng vẻ rất hồn nhiên, sinh động, ví dụ như bức tượng người ngồi thổi khèn, tượng người cõng nhau nhảy múa thổi khèn cho thấy sự thoải mái, thanh nhàn trong cuộc sống đơn giản. Bên cạnh đề tài là con người còn có các động vật gần trong sinh hoạt của con người: gà, chó, chim&#8230;</p>
<p><strong>Âm nhạc</strong>: Qua các hiện vật khảo cổ tìm được qua hình ảnh trên các trống đồng, ta thấy cư dân Văn Lang rất ưa ca hát, nhảy múa. Họ hát đối đáp, đánh trống, đánh cồng hoặc hòa tấu cùng nhau với đủ các dụng cụ âm nhạc mà họ đã sáng tạo được như sau: Trống đồng có âm thanh dũng mãnh: trống da, cồng chiêng (mỗi giàn chiêng có từ 6 đến 8 chiếc), chuông nhạc, phách, khèn&#8230;</p>
<p><strong>Hội lễ:&nbsp;</strong>Hội lễ là một phần trong cuộc sống của dân Lạc. Trong các buổi lễ hội có những sinh hoạt như sau:</p>
<ul>
<li>Tục lệ đánh trống đồng: hoặc do một người đánh hoặc hòa tấu từng cặp trống đực cái, người đánh trống bận lễ phục hình chim ở tư thế ngồi hay đứng.</li>
<li>Múa nhảy ca hát: Người trình diễn cũng bận lễ phục hình chim, có múa hóa trang, múa vũ trang, múa hát giao duyên nam nữ. Múa hóa trang thường đội mũ có gắn lông chim, có từ ba đến bảy người, có người cầm vũ khí, cầm khèn.</li>
<li>Hội giã cối: từng đôi nam nữ cầm chày dài giã cối tròn tạo nên hình ảnh tượng trưng cho sự sinh phồn.</li>
<li>Các cuộc đua thuyền hào hứng với những chiếc thuyền độc mộc mình thon, mũi cong, đuôi én.</li>
</ul>
<p>Mọi sinh hoạt trên đều gắn với điều cầu mong thiết thực của cuộc sống như mong mưa thuận, gió hòa, mong được mùa, mong sinh sản được nhiều.</p>
<h3>Tín ngưỡng</h3>
<p>Dân Lạc thờ các lực lượng thiên nhiên (thần núi, thần sông, thần đất); thờ các vật thiêng (thần rồng, chim, hổ); thờ anh hùng (Phù Đổng)</p>
<p><em>Thông tin được tổng hợp lại từ các nguồn Wiki, sách Lĩnh Nam Chích Quái, Đại Việt Sử Ký Toàn Thư và một số diễn đàn lịch sử.</em></p>
', '18 đời vua Hùng kéo dài trong 2622 năm (Từ 2879 TCN đến 258 TCN). Không thể phủ nhận các đời vua Hùng là thủy tổ của người Việt. Nhưng bên trong đó còn rất nhiều giả thuyết và những nghi ngờ về sự chính xác trong đó. Nếu chia 2622 năm kéo dời của [&hellip;]', 979, 'post', '2018-06-22 06:47:57', '2023-04-23 12:33:59');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (995, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (995, 64);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (995, 300);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (990, 'Lạc Long Quân', 'lac-long-quan', '<p>Lạc Long Quân tên húy là Sùng Lãm (Thế kỷ thứ 8 TCN &#8211; 7 TCN). Ông là con của Kinh Dương Vương và Thần Long. Ông được xem là thủy tổ của dân tộc Việt Nam. Truyền thuyết bọc trăm trứng nở trăm người con của Lạc Long Quân và Âu Cơ. 50 người con lên rừng và 50 người con xuống biển. Con trai ông là tù trưởng bộ lạc Văn Lang (vua Hùng). Người có công thống nhất tất cả bộ lạc và lập nên nhà nước Văn Lang. Xưng hiệu là vua Hùng.</p>
<h2>Lạc Long Quân</h2>
<p><figure id="attachment_991" aria-describedby="caption-attachment-991" style="width: 560px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-991 size-full" src="https://media.huynhhieutravel.com/lac-long-quan.jpg" alt="Lạc Long Quân" width="560" height="640"><figcaption id="caption-attachment-991" class="wp-caption-text">Ảnh minh họa Lạc Long Quân</figcaption></figure></p>
<p>Theo truyền thuyết Lạc Long Quân là con của <a href="http://bit.ly/2tqyAbi">Kinh Dương Vương</a>. Bạn có thể tìm hiểu Kinh Dương Vương qua link:&nbsp;<a href="http://bit.ly/2tqyAbi">http://bit.ly/2tqyAbi</a>.</p>
<h3>Truyền Thuyết Trong Lĩnh Nam Chích Quái</h3>
<p style="font-weight: 400;">Lạc Long Quân dạy dân việc cày cấy nông tang, đặt ra các đẳng quân, thần, tôn, ti, các đạo cha con, vợ chồng, đôi khi trở về Thủy Phủ mà trăm họ vẫn yên vui vô sự, không biết do đâu được thế. Hễ dân có việc lại lớn tiếng gọi Long Quân rằng: &#8220;Bố ơi! sao không lại cứu chúng tôi&#8221;. Long Quân tới ngay, sự linh hiển của Long Quân, người đời không ai lường nổi.</p>
<p style="font-weight: 400;">Đế Nghi truyền ngôi cho con là Đế Lai, cai trị Bắc phương. Nhân khi thiên hạ vô sự bèn sai quần thần là bọn Xuy Vưu thay mình trông coi quốc sự rồi đi tuần xuống nước Xích Quỷ ở phía Nam. Khi đó, Long Quân đã về Thủy Phủ, trong nước không có chúa.</p>
<p style="font-weight: 400;">Đế Lai bèn để ái nữ là Âu Cơ và các thị tỳ ở lại nơi hành tại rồi đi chu du thiên hạ, ngắm các nơi danh lam thắng cảnh. Thấy hoa kỳ cỏ lạ, trân cầm dị thú, ngọc ngà vàng bạc&#8230; các thứ đá quý, các cây trầm, đàn cùng các sơn hào hải vật không thiếu thứ gì, khí hậu bốn mùa không lạnh không nóng, Đế Lai rất ái mộ, vui quên trở về.</p>
<p style="font-weight: 400;">Dân phương Nam khổ vì bị người Bắc phương quấy nhiễu, không được yên sống như xưa mới cùng gọi Long Quân rằng: &#8220;Bố ơi ở đâu mà để cho dân Bắc xâm nhiễu&nbsp;chúng&nbsp;dân&#8221;.Long Quân đột nhiên trở về, thấy Âu Cơ có dung mạo đẹp đẽ kỳ lạ, trong lòng vui mừng, bèn hóa thành một trang thiếu niên phong tư tú lệ, tả hữu kẻ hầu người hạ đông đúc, vừa đi vừa ca hát đánh trống. Cung điện tự nhiên dựng lên.&nbsp;Âu Cơ vui lòng theo Long Quân. Long Quân giấu Âu Cơ ở Long Đài.</p>
<p style="font-weight: 400;">Đế Lai trở về, không thấy Âu Cơ, sai quần thần đi tìm khắp thiên hạ. Long Quân có phép thần thông biến hóa thành trăm hình vạn trạng yêu tinh, quỷ sứ, rồng, rắn, hổ, voi&#8230; làm cho bọn đi tìm đều sợ hãi không dám sục sạo, Đế Lai bèn phải trở về.</p>
<h3>Truyền Thuyết Lạc Long Quân Diệt Ngư Tinh</h3>
<p>Ở biển Đông có con tinh ngư xà (còn gọi là Ngư Tinh) dài hơn năm mươi trượng, chân nhiều như chân rết, biến hóa vạn trạng, linh dị khôn lường, khi đi thì ầm ầm như mưa, lại ăn được thịt người nên ai cũng sợ.</p>
<p>Thuở ấy có hòn đá Ngư Tinh, răng đá lởm chởm cắt ngang bờ bể, ở dưới đá có hang, Ngư Tinh sống ở trong đó. Vì sóng gió hiểm trở, không có lối thông, dân muốn mở một đường đi khác nhưng đá rắn khó đẽo. Thuyền của nhân dân đi qua chỗ này thường hay bị Ngư Tinh làm hại. Đêm kia có bọn người tiên đục đá làm đường đi để cho hành nhân có chỗ qua lại. Ngư Tinh bèn hóa làm con gà trắng gáy ở trên núi. Quần tiên nghe tiếng ngỡ rằng đã rạng đông bèn cùng bay lên trời.</p>
<p>Lạc Long Quân thương dân bị hại bèn hóa phép thành một chiếc thuyền của thường dân, hạ lệnh cho quỷ Dạ Thoa ở Thủy Phủ cấm hải thần nổi sóng, rồi chèo thuyền đến bờ hang đá Ngư Tinh, giả cách cầm một người sắp ném vào cho nó ăn. Ngư Tinh há miệng định nuốt. Long Quân cầm một khối sắt nung đỏ ném vào miệng cá. Ngư Tinh chồm lên quẫy mình quật vào thuyền. Long Quân cắt đứt đuôi cá, lột da phủ lên trên núi nay chỗ đó gọi là Bạch Long Vĩ, còn cái đầu trôi ra ngoài bể biến thành con chó. Long Quân bèn lấy đá ngăn bể rồi chém nó. Nó biến thành cái đầu chó, nay gọi là Cẩu Đầu Sơn. Thân trôi ra ngoài Mạn Cầu, chỗ đó nay gọi là Mạn Cầu Thủy (còn gọi là Cẩu Đầu Thủy).</p>
<h3>Tại Sao Vua Hùng Chứ Không Phải Lạc Long Quân Là Thủy Tổ?</h3>
<p>Nhiều luận cứ của những nhà sử học cho rằng Lạc Long Quân thật chất chỉ là trong truyền thuyết. Chúng ta thiếu nhiều căn cứ để xác định rằng Lạc Long Quân thật sự có tồn tại trong lịch sử. Riêng vua Hùng, ông là người thật sự có và đã thống nhất các bộ tộc Lạc Việt. Ông cũng là người lập nên một nhà nước có chính quyền đầu tiên mang tên Văn Lang của dân tộc Việt Nam.</p>
<p>Vua Tự Đức đã nhận định đây là những &#8220;câu truyện đề cập đến ma trâu, thần rắn, hoang đường không có chuẩn tắc&#8221; và kiên quyết loại Kinh Dương và Lạc Long ra khỏi chính sử bằng cách đưa xuống phụ chú dưới niên kỷ Hùng vương, để &#8220;cho hợp với cái nghĩa lấy nghi truyền nghi&#8221;.</p>
<h3>Nhiều Nơi Vẫn Lập Đền Thờ Phụng Lạc Long Quân</h3>
<p>Tuy rằng việc xác định thủy tổ còn chưa rõ ràng. Nhưng chúng ta cũng không bỏ quên công lao của vị cha vua Hùng này. Nhiều đình thờ được lập ra thờ phụng vị Tổ của đất nước này. Đặc biệt là ở dân làng Bình Đà.</p>
<p>Suốt sáu thế kỉ, đích thân 16 vị vua của các triều đại đều đích thân về Bình Đà dâng lễ Quốc tổ. Đã có 16 hiến sắc suy tôn Lạc Long Quân là &#8220;Khai Quốc Thần&#8221; (các hiến sắc này đều được lưu giữ tại Đền Nội Bình Đà và bảo tàng Lịch sử quốc gia)</p>
<p>Ngoài ra, Lăng và đền thờ của Kinh Dương Vương ở Bắc Ninh được nhiều đời triều đại vua phong kiến Việt Nam thờ phụng. Đến bây giờ ở Bắc Ninh vẫn tổ chức lễ hội thờ cúng Kinh Dương Vương hàng năm. Tên ông lấy làm tên đường nhiều tỉnh thành ở nước ta, đặc biệt thành phố Hồ Chí Minh cũng có tên đường của ông.</p>
<p>Bạn có thể tìm hiểu thêm về cha của Lạc Long Quân là Kinh Dương Vương:&nbsp;<a href="https://huynhhieutravel.com/kinh-duong-vuong/">https://huynhhieutravel.com/kinh-duong-vuong/</a></p>
', 'Lạc Long Quân tên húy là Sùng Lãm (Thế kỷ thứ 8 TCN &#8211; 7 TCN). Ông là con của Kinh Dương Vương và Thần Long. Ông được xem là thủy tổ của dân tộc Việt Nam. Truyền thuyết bọc trăm trứng nở trăm người con của Lạc Long Quân và Âu Cơ. 50 người [&hellip;]', 993, 'post', '2018-06-21 15:21:03', '2023-04-23 12:34:00');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (990, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (990, 64);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (990, 300);