INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (2600, 'Câu lạc bộ Tia Sáng', 'cau-lac-bo-tia-sang', '<p>Câu lạc bộ Tia Sáng được thành lập ở thành phố Hồ Chí Minh năm 2013. Câu lạc bộ bao gồm những thành viên trên mọi vùng miền tổ quốc với tinh thần thiện nguyện và giúp đỡ những người có hoàn cảnh khó khăn. Nơi những nhiệt huyết được thắp sáng lan tỏa đến những vùng miền khó khăn ở khắp đất nước Việt Nam. Mỗi năm, câu lạc bộ Tia Sáng đều thực hiện nhiều chương trình ý nghĩa đến nhiều tỉnh thành đất nước: Lâm Đồng, Cần Thơ, Hậu Giang, Đồng Tháp, Bình Phước, Ninh Thuận, Hồ Chí Minh,&#8230; Và ngọn lửa tình nguyện ấy vẫn đang lan tỏa đến nhiều vùng miền tổ quốc khác.</p>
<h2>Thông tin clb Tia Sáng</h2>
<p><figure id="attachment_2582" aria-describedby="caption-attachment-2582" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2582" src="https://media.huynhhieutravel.com/các-thành-viên-câu-lạc-bộ-tia-sáng-chụp-ảnh-cùng-nhau.jpg" alt="Các thành viên câu lạc bộ Tia Sáng chụp ảnh cùng nhau" width="913" height="608" srcset="https://media.huynhhieutravel.com/các-thành-viên-câu-lạc-bộ-tia-sáng-chụp-ảnh-cùng-nhau.jpg 913w, https://media.huynhhieutravel.com/các-thành-viên-câu-lạc-bộ-tia-sáng-chụp-ảnh-cùng-nhau-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2582" class="wp-caption-text">Các thành viên câu lạc bộ Tia Sáng chụp ảnh cùng nhau</figcaption></figure></p>
<p>Câu lạc bộ Tia Sáng hiện tại có gần 800 thành viên chính thức và nhiều thành viên, nhà tài trợ không chính thức trong các chuyến đi.</p>
<h3>Lịch sử hình thành câu lạc bộ Tia Sáng</h3>
<p>Thành phố Hồ Chí Minh vào những ngày mưa năm 2013, một nhóm người trẻ và đứng đầu là anh Nguyễn Tiến Dũng đã họp lại và quyết tâm hình thành một câu lạc bộ từ thiện. Một nhóm người trẻ mà nòng cốt là những người từng tham gia Hội trại Tuổi trẻ Phật giáo đã đặt cái tên Tia Sáng cho câu lạc bộ. Tia Sáng như một luồng sáng mang đến những ấm áp, rạng rỡ đến những vùng sâu vùng xa. Nơi những con người gặp khó khăn một vài điều gì đó.</p>
<p><figure id="attachment_2596" aria-describedby="caption-attachment-2596" style="width: 960px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2596" src="https://media.huynhhieutravel.com/thiện-nguyện-sài-gòn.jpg" alt="Thiện nguyện Sài Gòn - Thành phố Hồ Chí Minh" width="960" height="638" srcset="https://media.huynhhieutravel.com/thiện-nguyện-sài-gòn.jpg 960w, https://media.huynhhieutravel.com/thiện-nguyện-sài-gòn-768x510.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2596" class="wp-caption-text">Thiện nguyện Sài Gòn &#8211; Thành phố Hồ Chí Minh</figcaption></figure></p>
<p>Từ những ngày đầu chỉ tham gia những hoạt động ở nội thành thành phố Hồ Chí Minh. Những hoạt động như nấu cơm, cháo miễn phí cho các bệnh nhân ở bệnh viện. Hay tổ chức tặng quà, đến thăm các bệnh nhân trong một số trại tâm thần ở nội ô. Sau đó, câu lạc bộ đã dần mở rộng những chuyến đi của mình đi xa hơn: Biên Hòa, Bình Dương, Bình Phước hay những chuyến đi xuôi về miền Nam như Đồng Tháp, Long An,&#8230;</p>
<p><figure id="attachment_2594" aria-describedby="caption-attachment-2594" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2594" src="https://media.huynhhieutravel.com/sự-hồn-nhiên-các-thành-viên-clb-tia-sáng.jpg" alt="Sự hồn nhiên của các thành viên clb Tia Sáng" width="913" height="608" srcset="https://media.huynhhieutravel.com/sự-hồn-nhiên-các-thành-viên-clb-tia-sáng.jpg 913w, https://media.huynhhieutravel.com/sự-hồn-nhiên-các-thành-viên-clb-tia-sáng-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2594" class="wp-caption-text">Sự hồn nhiên của các thành viên clb Tia Sáng</figcaption></figure></p>
<h3>Ý nghĩa của câu lạc bộ Tia Sáng mang lại</h3>
<p>Mỗi hoạt động của câu lạc bộ Tia Sáng hay các câu lạc bộ từ thiện khác đều mang những ý nghĩa riêng mình. Và câu lạc bộ Tia Sáng có những tiêu chí muốn mang lại.</p>
<p><figure id="attachment_2597" aria-describedby="caption-attachment-2597" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2597" src="https://media.huynhhieutravel.com/trẻ-em-vùng-nông-thôn-việt-nam.jpg" alt="Trẻ em vùng nông thôn Việt Nam" width="1280" height="853" srcset="https://media.huynhhieutravel.com/trẻ-em-vùng-nông-thôn-việt-nam.jpg 1280w, https://media.huynhhieutravel.com/trẻ-em-vùng-nông-thôn-việt-nam-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-2597" class="wp-caption-text">Trẻ em vùng nông thôn Việt Nam</figcaption></figure></p>
<h4>Sẽ chia và giúp đỡ những người khó khăn</h4>
<p>Việt Nam là một trong những nước đang phát triển với nhiều vùng có hoàn cảnh khó khăn. Nơi những người dân nước Việt, những đồng bào của chúng ta vẫn còn gặp nhiều khó khăn trong cuộc sống. Nơi cái ăn hàng ngày luôn là điều lo lắng với họ. Đó là chúng ta chưa kể đến những dịch vụ, giáo dục và y tế cần thiết cho mỗi con người mà thời nay chúng tôi cho là cơ bản phải có được.</p>
<p><figure id="attachment_2585" aria-describedby="caption-attachment-2585" style="width: 912px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2585" src="https://media.huynhhieutravel.com/các-trẻ-em-tập-họp-chuẩn-bị-nhận-quà-của-câu-lạc-bộ-tia-sáng.jpg" alt="Các trẻ em tập họp chuẩn bị nhận quà của câu lạc bộ Tia Sáng" width="912" height="608" srcset="https://media.huynhhieutravel.com/các-trẻ-em-tập-họp-chuẩn-bị-nhận-quà-của-câu-lạc-bộ-tia-sáng.jpg 912w, https://media.huynhhieutravel.com/các-trẻ-em-tập-họp-chuẩn-bị-nhận-quà-của-câu-lạc-bộ-tia-sáng-768x512.jpg 768w" sizes="(max-width: 912px) 100vw, 912px" /><figcaption id="caption-attachment-2585" class="wp-caption-text">Các trẻ em tập họp chuẩn bị nhận quà của câu lạc bộ Tia Sáng</figcaption></figure></p>
<p>Tôi đã đồng hành cùng câu lạc bộ Tia Sáng đến nhiều nơi mà điện nước là những thứ vẫn là thứ thiếu thốn với họ. Những đứa bé dân tộc chưa sành sỏi cả tiếng Kinh nói gì đến việc đi học viết chữ, đọc chữ. Chúng tôi mang đến những bộ đồ cũ nhưng nguyên vẹn sạch sẽ đến những vùng khó khăn đó. Đôi khi là những dây diện để ủy ban phường, xã có thể nối điện cho bạn con. Đôi khi là những chiếc xe đạp để giúp hàng chục km đường đi học của các em ở đó trở nên nhanh chóng hơn.</p>
<p>Tất cả những chia sẽ đó đôi khi là nhỏ nhoi, nhưng chúng tôi tin rằng nếu chúng ta có tấm lòng thì sẽ tích nhỏ thành lớn. Những điều đó đôi khi sẽ ảnh hưởng lớn lao đến cuộc đời. Hoặc cải thiện bớt sự khó khăn ở những vùng đất chúng tôi đến.</p>
<p><figure id="attachment_2586" aria-describedby="caption-attachment-2586" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2586" src="https://media.huynhhieutravel.com/các-trẻ-em-vùng-quê-cầm-lồng-đèn-được-tặng.jpg" alt="Các trẻ em vùng quê cầm lồng đèn được tặng" width="913" height="608" srcset="https://media.huynhhieutravel.com/các-trẻ-em-vùng-quê-cầm-lồng-đèn-được-tặng.jpg 913w, https://media.huynhhieutravel.com/các-trẻ-em-vùng-quê-cầm-lồng-đèn-được-tặng-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2586" class="wp-caption-text">Các trẻ em vùng quê cầm lồng đèn được tặng</figcaption></figure></p>
<h4>Tạo kỳ ức tuổi thơ tươi đẹp hơn cho những đứa trẻ</h4>
<p>Đôi khi tặng quà không giúp quá nhiều vào sự thay đổi cuộc đời của hàng nghìn đứa trẻ ở những vùng chúng tôi đến. Những phần quà nhỏ đó chỉ giúp chúng bớt đói hơn trong vài ba tháng. Nhưng nó không thể nào tạo thành một cần câu cơm mãi mãi cho chúng. Nhưng đôi khi tinh thần, ký ức chúng ta tươi đẹp vì một vài mảnh tươi đẹp trong cả cuộc sống đen tối kéo dài.</p>
<p>Và chúng tôi muốn là một phần trong những ký ức tươi đẹp đó với những đứa bé khó khăn. Chúng sẽ được vui chơi cùng chúng tôi, được hòa mình nhiều hơn cùng những cô chú thành thị xuống chơi.</p>
<p><figure id="attachment_2589" aria-describedby="caption-attachment-2589" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2589" src="https://media.huynhhieutravel.com/đội-hậu-cần-câu-lạc-bộ-tia-sáng-chuẩn-bị-trò-chơi.jpg" alt="Đội hậu cần câu lạc bộ Tia Sáng chuẩn bị trò chơi" width="913" height="608" srcset="https://media.huynhhieutravel.com/đội-hậu-cần-câu-lạc-bộ-tia-sáng-chuẩn-bị-trò-chơi.jpg 913w, https://media.huynhhieutravel.com/đội-hậu-cần-câu-lạc-bộ-tia-sáng-chuẩn-bị-trò-chơi-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2589" class="wp-caption-text">Đội hậu cần câu lạc bộ Tia Sáng chuẩn bị trò chơi</figcaption></figure></p>
<h4>Và đó cũng là những ký ức tươi đẹp của những thành viên câu lạc bộ Tia Sáng</h4>
<p>Vui cùng những bạn nhỏ ở vùng sâu vùng xa, trò chuyện cùng những cụ già, nấu những bữa ăn ý nghĩa cho những người khó khăn,&#8230; Tất cả những điều đó là những ký ức tươi sáng trong những thành viên câu lạc bộ Tia Sáng. Nó giúp chúng tôi trưởng thành hơn để tự giác mang những trách nhiệm bản thân giúp đỡ người khác. Nó giúp chúng tôi mang đến những giá trị để khẳng định mình rất có ích cho cuộc sống.</p>
<p>Tất cả những tiếng cười các em nhỏ, những giọt mồ hôi chảy của chính mình. Hay cả những giọt nước mắt khi ra về tạo thành những mảnh ký ức trong lòng mỗi người. Nó đã gắn kết lên câu lạc bộ Tia Sáng trong hơn 5 năm hoạt động và sẽ còn nhiều năm hơn thế nữa.</p>
<p><figure id="attachment_2588" aria-describedby="caption-attachment-2588" style="width: 986px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2588" src="https://media.huynhhieutravel.com/chuẩn-bị-lồng-đèn-tặng-các-em-đêm-trăng-rằm.jpg" alt="Chuẩn bị lồng đèn tặng các em đêm trăng rằm" width="986" height="657" srcset="https://media.huynhhieutravel.com/chuẩn-bị-lồng-đèn-tặng-các-em-đêm-trăng-rằm.jpg 986w, https://media.huynhhieutravel.com/chuẩn-bị-lồng-đèn-tặng-các-em-đêm-trăng-rằm-768x512.jpg 768w" sizes="(max-width: 986px) 100vw, 986px" /><figcaption id="caption-attachment-2588" class="wp-caption-text">Chuẩn bị lồng đèn tặng các em đêm trăng rằm</figcaption></figure></p>
<h2>Những hoạt động thiện nguyện của câu lạc bộ Tia Sáng trong các chuyến đi</h2>
<p>Mỗi năm câu lạc bộ Tia Sáng đều có ít nhất 4-5 lần di chuyển xa đến các tỉnh thành khác nhau để giúp đỡ các đối tượng khó khăn, đặc biệt là các em nhỏ.</p>
<p><figure id="attachment_2599" aria-describedby="caption-attachment-2599" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2599" src="https://media.huynhhieutravel.com/trò-chơi-thú-nhúng.jpg" alt="Trò chơi thú nhúng" width="913" height="608" srcset="https://media.huynhhieutravel.com/trò-chơi-thú-nhúng.jpg 913w, https://media.huynhhieutravel.com/trò-chơi-thú-nhúng-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2599" class="wp-caption-text">Trò chơi thú nhúng</figcaption></figure></p>
<h3>Tạo nên những trò chơi thú vị cho trẻ em</h3>
<p>Chúng tôi có một team game riêng biệt để tạo những trò chơi đơn giản nhưng vô cùng vui nhộn cho những đứa bé. Chúng tôi vẽ lên những tờ giấy A4 và ghi tên trò chơi rồi treo lên để đánh dấu khu vực. Khi chơi thắng một trò chơi nào đó những đứa bé đó sẽ được thưởng một phiếu quà tặng. Chúng tôi sẽ có một quầy quà tặng và đồ ăn để chúng đổi bằng phiếu quà tặng.</p>
<p><figure id="attachment_2590" aria-describedby="caption-attachment-2590" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2590" src="https://media.huynhhieutravel.com/một-cậu-bé-dễ-thương-chơi-trò-chơi.jpg" alt="Một cậu bé dễ thương chơi trò chơi" width="1280" height="853" srcset="https://media.huynhhieutravel.com/một-cậu-bé-dễ-thương-chơi-trò-chơi.jpg 1280w, https://media.huynhhieutravel.com/một-cậu-bé-dễ-thương-chơi-trò-chơi-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-2590" class="wp-caption-text">Một cậu bé dễ thương chơi trò chơi</figcaption></figure></p>
<p>Trò bịt mắt đập lon là thú vị nhất. Chúng tôi bịt mắt những đứa trẻ bằng những chiếc khẩu trang kín. Chúng sẽ cầm một cái gậy và nghe chỉ dẫn của hàng chục khán giả bên ngoài. Tiến đến những cái lon được treo lủng lẳng trên dây. Chỉ cần chúng đập trúng lon sẽ lãnh phiếu thưởng của chúng tôi.</p>
<p>Trò thú nhúng luôn là trò gây cười nhất với chúng tôi. Chúng tôi thường chuẩn bị những con thú nhúng đầy màu sắc rực rỡ. Những đứa nhỏ sẽ leo lên chúng và nhúng đến vạch đích cách đó khoảng hơn 10-20 mét. Những chiến binh nhí ngồi trên những con thú nhúng ngộ nghĩnh dễ thương cùng nhau nhúng về địch. Trong thấy những sự ngây ngô, tinh nghịch của chúng cảm giác vui vô cùng.</p>
<p><figure id="attachment_2584" aria-describedby="caption-attachment-2584" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2584" src="https://media.huynhhieutravel.com/các-trẻ-em-chơi-trò-chơi-thú-nhúng.jpg" alt="Các trẻ em chơi trò chơi thú nhúng" width="913" height="608" srcset="https://media.huynhhieutravel.com/các-trẻ-em-chơi-trò-chơi-thú-nhúng.jpg 913w, https://media.huynhhieutravel.com/các-trẻ-em-chơi-trò-chơi-thú-nhúng-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2584" class="wp-caption-text">Các trẻ em chơi trò chơi thú nhúng</figcaption></figure></p>
<p>Trò chơi ném phi tiêu luôn là không gian tĩnh lặng nhất trong các gian hàng trò chơi. Những đứa bé với sự tập trung cao độ ném những phi tiêu đến những hồng tâm treo phía trước. Dường như rất nhiều robinhood đã được phát sinh ra từ trò chơi này. Những đứa trẻ luôn có tài ném hơn những người lớn của chúng tôi rất nhiều.</p>
<p>Trò vẽ tranh lại là trò thử thách trí tưởng tượng cao nhất. Những đứa bé có hoa tay vẽ đẹp thì không nói đến, những đứa bé hay vẽ tranh trừu tượng mới là những người gây hack não nhất. Những hình dạng kỳ quái của bức tranh đôi khi làm chúng ta xoắn cả não.</p>
<p><figure id="attachment_2591" aria-describedby="caption-attachment-2591" style="width: 912px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2591" src="https://media.huynhhieutravel.com/những-cậu-bé-chơi-trò-chơi-đập-lon.jpg" alt="Một cậu bé chơi trò chơi đập lon" width="912" height="608" srcset="https://media.huynhhieutravel.com/những-cậu-bé-chơi-trò-chơi-đập-lon.jpg 912w, https://media.huynhhieutravel.com/những-cậu-bé-chơi-trò-chơi-đập-lon-768x512.jpg 768w" sizes="(max-width: 912px) 100vw, 912px" /><figcaption id="caption-attachment-2591" class="wp-caption-text">Một cậu bé chơi trò chơi đập lon</figcaption></figure></p>
<p>Trò chơi câu đồ chơi luôn được chào đón nồng nhiệt nhất. Những đứa bé cầm cần câu móc vào những bịch bánh hay đồ chơi treo móc trước mặt. Đôi khi cần tí kiến trì và khéo léo để lấy được quà. Nhưng chắc chắn việc lãnh quà ngay lập tức khiến không khí trò chơi trở nên náo nhiệt vô cùng.</p>
<p>Và nhiều nhiều trò chơi khác diễn ra mà tôi không thể nào kể hết ra đây được.</p>
<p><figure id="attachment_2592" aria-describedby="caption-attachment-2592" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2592" src="https://media.huynhhieutravel.com/quầy-thức-ăn-và-đồ-chơi-cho-các-trẻ-em.jpg" alt="Quầy thức ăn và đồ chơi cho các trẻ em" width="913" height="608" srcset="https://media.huynhhieutravel.com/quầy-thức-ăn-và-đồ-chơi-cho-các-trẻ-em.jpg 913w, https://media.huynhhieutravel.com/quầy-thức-ăn-và-đồ-chơi-cho-các-trẻ-em-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2592" class="wp-caption-text">Quầy thức ăn và đồ chơi cho các trẻ em</figcaption></figure></p>
<h3>Team nấu ăn từ những người nấu bếp giỏi giang</h3>
<p>Chúng tôi có hẳn một team masterchef với những nhà đầu bếp giỏi giang. Những chàng trai, cô gái xúm lại người ngồi lặt rau, kẻ chế biến thịt cá. Những cậu con trai thì nhóm bếp lò bằng than củi. Những công việc được phân chia rõ ràng, mọi người đều chia việc giúp tạo nên những món ăn ngon lành.</p>
<p><figure id="attachment_2583" aria-describedby="caption-attachment-2583" style="width: 912px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2583" src="https://media.huynhhieutravel.com/các-tình-nguyện-viên-clb-tia-sáng-chuẩn-bị-đồ-ăn-cho-chương-trình.jpg" alt="Các tình nguyện viên câu lạc bộ Tia Sáng chuẩn bị đồ ăn cho chương trình" width="912" height="608" srcset="https://media.huynhhieutravel.com/các-tình-nguyện-viên-clb-tia-sáng-chuẩn-bị-đồ-ăn-cho-chương-trình.jpg 912w, https://media.huynhhieutravel.com/các-tình-nguyện-viên-clb-tia-sáng-chuẩn-bị-đồ-ăn-cho-chương-trình-768x512.jpg 768w" sizes="(max-width: 912px) 100vw, 912px" /><figcaption id="caption-attachment-2583" class="wp-caption-text">Các tình nguyện viên câu lạc bộ Tia Sáng chuẩn bị đồ ăn cho chương trình</figcaption></figure></p>
<h3>Hàng nghìn món quà được sắp xếp từ những con người làm việc quy chuẩn</h3>
<p>Sau khi khuân vác những bao đồ từ thiện vào bên trong, những món quà sắp đầy cả căn phòng. Chúng tôi có hẳn một team hậu cần chia ra làm việc xử lý chúng. Ngồi cùng nhau, người thì lo phần mở quà, người thì lo phần chia quà, người thì gói đồ lại, người thì sắp xếp chúng vào một chỗ ngăn nắp.</p>
<p><figure id="attachment_2598" aria-describedby="caption-attachment-2598" style="width: 913px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2598" src="https://media.huynhhieutravel.com/trò-chơi-team-game-chuẩn-bị-cho-chương-trình-từ-thiện.jpg" alt="Trò chơi team game chuẩn bị cho chương trình từ thiện" width="913" height="608" srcset="https://media.huynhhieutravel.com/trò-chơi-team-game-chuẩn-bị-cho-chương-trình-từ-thiện.jpg 913w, https://media.huynhhieutravel.com/trò-chơi-team-game-chuẩn-bị-cho-chương-trình-từ-thiện-768x511.jpg 768w" sizes="(max-width: 913px) 100vw, 913px" /><figcaption id="caption-attachment-2598" class="wp-caption-text">Trò chơi team game chuẩn bị cho chương trình từ thiện</figcaption></figure></p>
<h3>Chúng tôi có cả đoàn tạp kỹ, MC và ca sĩ nghiệp dư thú vị</h3>
<p>MC được lựa chọn từ những bạn có tinh thần hoạt náo và cái miệng lanh lợi khi nói. Họ giúp khuấy động không khí vô cùng ấn tượng trong buổi sinh hoạt. Những ca sĩ thể hiện những ca khúc bất hủ với tông giọng cao vút, vang khắp cả những bản làng. Tất cả tạo nên những màn trình diễn ngoạn mục. Nó giúp kết nối các em nhỏ cùng thành viên của câu lạc bộ Tia Sáng rất nhiều.</p>
<p><figure id="attachment_2595" aria-describedby="caption-attachment-2595" style="width: 300px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-2595" src="https://media.huynhhieutravel.com/sự-vui-tươi-của-một-thành-viên-câu-lạc-bộ-tia-sáng.jpg" alt="Sự tươi vui của một thành viên câu lac bộ Tia Sáng" width="300" height="450"><figcaption id="caption-attachment-2595" class="wp-caption-text">Sự tươi vui của một thành viên câu lac bộ Tia Sáng</figcaption></figure></p>
<h3>Kết nối nhau qua những đêm lửa trại</h3>
<p>Sau những công việc bộn bề của những team game, team hậu cần, team nấu nướng, team ca múa nhạc là những phút quây quần bên nhau. Những thành viên kết nối thành một vòng tròn cùng nhau hòa mình bên lửa trại. Tất cả hát vang những bài ca kết nối, cùng chơi những trò chơi lạ lẫm. Những tia sáng trong lòng mỗi người cùng rực trái bên ngọn lửa trại ấm nồng ở những vùng đất xa.</p>
<p><figure id="attachment_2593" aria-describedby="caption-attachment-2593" style="width: 912px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2593" src="https://media.huynhhieutravel.com/sau-những-giờ-thiện-nguyện-là-những-phút-giây-vui-vẻ-bên-nhau-của-câu-lạc-bộ-tia-sáng.jpg" alt="Sau những giờ thiện nguyện là những phút giây vui vẻ bên nhau của câu lạc bộ Tia Sáng" width="912" height="608" srcset="https://media.huynhhieutravel.com/sau-những-giờ-thiện-nguyện-là-những-phút-giây-vui-vẻ-bên-nhau-của-câu-lạc-bộ-tia-sáng.jpg 912w, https://media.huynhhieutravel.com/sau-những-giờ-thiện-nguyện-là-những-phút-giây-vui-vẻ-bên-nhau-của-câu-lạc-bộ-tia-sáng-768x512.jpg 768w" sizes="(max-width: 912px) 100vw, 912px" /><figcaption id="caption-attachment-2593" class="wp-caption-text">Sau những giờ thiện nguyện là những phút giây vui vẻ bên nhau của câu lạc bộ Tia Sáng</figcaption></figure></p>
<h2>Cách thức tham gia câu lạc bộ Tia Sáng</h2>
<p>Bạn có thể cập nhật các tin tức về những chuyến đi của câu lạc bộ Tia Sáng trên fanpage câu lạc bộ: <a href="https://www.facebook.com/CLB-Thi%E1%BB%87n-Nguy%E1%BB%87n-Tia-S%C3%A1ng-592960670742636/?eid=ARDNei5PqLqO1gfClG82rn2XLo9E_BIGcvrQiMQAGEStOhimTLHghjWOdpuEgsKKhfoqveYUrzDFKqS-">Fanpage Facebook CLB Tia Sáng.</a></p>
<p>Hoặc tham gia vào group facebook để trao đổi với câu lạc bộ Tia Sáng: <a href="https://www.facebook.com/groups/715237701954225/">Group Facebook CLB Tia Sáng.</a></p>
<p>Bạn cũng có thể liên lạc cùng chủ nhiệm câu lạc bộ hiện tại Mrs.Diệp Linh (0977263554).</p>
<h2>Video hành trình thiện nguyện câu lạc bộ từ thiện Tia Sáng</h2>
<p><iframe src="https://www.youtube.com/embed/RMTAWOGkWkU" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
', 'Câu lạc bộ Tia Sáng được thành lập ở thành phố Hồ Chí Minh năm 2013. Câu lạc bộ bao gồm những thành viên trên mọi vùng miền tổ quốc với tinh thần thiện nguyện và giúp đỡ những người có hoàn cảnh khó khăn. Nơi những nhiệt huyết được thắp sáng lan tỏa đến [&hellip;]', 2587, 'post', '2018-11-23 08:26:19', '2023-04-23 12:25:48');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (2600, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (2600, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (2600, 95);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (2562, 'Help Portrait Cần Thơ', 'help-portrait-can-tho', '<p>Help Portrait Cần Thơ là một ngày hội chụp ảnh chân dung ở Cần Thơ hưởng ứng theo chiến dịch Help Portrait toàn cầu. Help Portrait là phong trào toàn cầu các nhiếp ảnh gia và những nhà hậu cần (make up, làm tóc,&#8230;) sử dụng dụ cụ và chuyên môn của mình làm nên những bức ảnh chân dung đẹp. Sau đó rửa lại thành ảnh gửi tặng lại cho người có nhu cầu. Tại Cần Thơ nó đã trở thành một ngày hội họp mặt của các tình nguyện viên, các nhà nhiếp ảnh trẻ hoặc những người đam mê chụp hình. Những người với tâm làm tình nguyện mang những tấm hình đẹp, những món quà ý nghĩa đến các trẻ em, người già, người khó khăn,&#8230;</p>
<h2>Thông tin về Help Portrait Việt Nam</h2>
<figure id="attachment_2577" aria-describedby="caption-attachment-2577" style="width: 960px" class="wp-caption aligncenter"><img fetchpriority="high" decoding="async" class="size-full wp-image-2577" src="https://media.huynhhieutravel.com/tình-nguyện-viên-help-portrait-cần-thơ.jpg" alt="Tình nguyện viên Help Portrait Cần Thơ" width="960" height="539" srcset="https://media.huynhhieutravel.com/tình-nguyện-viên-help-portrait-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/tình-nguyện-viên-help-portrait-cần-thơ-768x431.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2577" class="wp-caption-text">Tình nguyện viên Help Portrait Cần Thơ</figcaption></figure>
<p>Help Portrait là một chương trình tổ chức trên toàn quốc vào ngày cuối tuần đầu tháng 12 hàng năm. Ở Việt Nam nó đã nhanh chóng lan rộng ra các tỉnh thành toàn quốc. Tạo thành một chiến dịch, một ngày hội rộng mở cho mọi người tham gia.</p>
<h3>Lịch sử hình thành Help Portrait Việt Nam</h3>
<p>Năm 2010, chương trình Help Portrait Việt Nam được khởi động lần đầu với chỉ riêng điểm chụp là thành phố Hồ Chí Minh. Với quy mô ban đầu chỉ là cấp phường, xóm, nhà trẻ. Số lượng tình nguyện viên 120 người, 4 điểm chụp với hơn 1200 bức ảnh.</p>
<p>Đến năm 2014 chương trình đã lan tỏa đến 13 tỉnh thành với quy mô lên đến 1600 tình nguyện viên và hơn 10.000 bức hình được chụp và gửi tặng đến các đối tượng khó khăn. Và từ đó đến năm 2017 nó luôn giữ vững số lượng trên 10.000 ảnh và hơn 1000 tình nguyện viên đăng ký tham gia ở các tỉnh thành trên toàn quốc.</p>
<figure id="attachment_2574" aria-describedby="caption-attachment-2574" style="width: 960px" class="wp-caption aligncenter"><img decoding="async" class="size-full wp-image-2574" src="https://media.huynhhieutravel.com/những-bức-ảnh-được-chụp-ở-help-portrait-cần-thơ.jpg" alt="Những bức ảnh được chụp ở Help Portrait Cần Thơ" width="960" height="720" srcset="https://media.huynhhieutravel.com/những-bức-ảnh-được-chụp-ở-help-portrait-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/những-bức-ảnh-được-chụp-ở-help-portrait-cần-thơ-768x576.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2574" class="wp-caption-text">Những bức ảnh được chụp ở Help Portrait Cần Thơ</figcaption></figure>
<h2>Hành trình Help Portrait Cần Thơ</h2>
<p>Và Help Portrait Cần Thơ được bắt đầu từ năm 2014 với hơn 5 điểm chụp khác nhau. Mỗi năm luôn có từ 50-100 tình nguyện viên đăng ký tham gia chương trình. Số lượng ảnh từ 500-1000 ảnh hàng năm. Đóng góp mạnh mẽ vào thành tích chung của chương trình Help Portrait Việt Nam.</p>
<p>Riêng năm 2017, số lượng tình nguyện viên là 50 người. Số lượng ảnh hơn 600 với 5 điểm chụp khác nhau.</p>
<figure id="attachment_2563" aria-describedby="caption-attachment-2563" style="width: 960px" class="wp-caption aligncenter"><img decoding="async" class="size-full wp-image-2563" src="https://media.huynhhieutravel.com/các-tình-nguyện-viên-chăm-sóc-các-cụ-già-ở-hội-dưỡng-lão-cần-thơ.jpg" alt="Các tình nguyện viên chăm sóc các cụ già ở hội dưỡng lão Cần Thơ" width="960" height="636" srcset="https://media.huynhhieutravel.com/các-tình-nguyện-viên-chăm-sóc-các-cụ-già-ở-hội-dưỡng-lão-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/các-tình-nguyện-viên-chăm-sóc-các-cụ-già-ở-hội-dưỡng-lão-cần-thơ-768x509.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2563" class="wp-caption-text">Các tình nguyện viên chăm sóc các cụ già ở hội dưỡng lão Cần Thơ</figcaption></figure>
<h3>Các điểm chụp Help Portrait Cần Thơ đã đến</h3>
<p>Help Portrait Cần Thơ đã tổ chức nhiều năm và đến nhiều điểm mái ấm tình thương, nhà trẻ mồ côi, hội dưỡng lão và nhiều điểm chụp hình khác nhau.</p>
<h4>Nhà trẻ mồ côi Hoa Mai</h4>
<p>Nhà trẻ mồ côi Hoa Mai nằm ở Phụng Hiệp &#8211; Hậu Giang nhưng chỉ cách trung tâm thành phố Cần Thơ khoảng 15km. Nơi đây nuôi dạy khoảng gần 30 bé mồ côi. Các em đa phần bị ba mẹ bỏ rơi từ nhỏ. Có những em vì gia đình khó khăn không nuôi nổi phải gửi lại. Hàng năm họ lại đến thăm các em vài lần. Những đứa trẻ ở đây khá hiếu động, nhưng vô cùng lễ phép. Ở đây, mỗi đứa trẻ có một câu chuyện khác nhau về cuộc đời mình. Hãy thử trò chuyện và tìm hiểu về chúng nhé! Bạn sẽ yêu quý chúng rất nhiều đấy.</p>
<figure id="attachment_2565" aria-describedby="caption-attachment-2565" style="width: 1280px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-2565" src="https://media.huynhhieutravel.com/các-tình-nguyện-viên-help-portrait-cần-thơ-chơi-cùng-các-bé-ở-nhà-trẻ-hoa-mai.jpg" alt="Các tình nguyện viên Help Portrait Cần Thơ chơi cùng các bé ở nhà trẻ mồ côi Hoa Mai" width="1280" height="848" srcset="https://media.huynhhieutravel.com/các-tình-nguyện-viên-help-portrait-cần-thơ-chơi-cùng-các-bé-ở-nhà-trẻ-hoa-mai.jpg 1280w, https://media.huynhhieutravel.com/các-tình-nguyện-viên-help-portrait-cần-thơ-chơi-cùng-các-bé-ở-nhà-trẻ-hoa-mai-768x509.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-2565" class="wp-caption-text">Các tình nguyện viên Help Portrait Cần Thơ chơi cùng các bé ở nhà trẻ mồ côi Hoa Mai</figcaption></figure>
<h4>Nhà trẻ mồ côi Hoa Hướng Dương</h4>
<p>Nhà trẻ mồ côi Hoa Hướng Dương cũng là một điểm chụp của Help Portrait Cần Thơ hàng năm. Nơi đây nuôi dạy hơn 30 bé mồ côi. Cấc bé nơi đây tính tình khá hiền lành và có phần nhút nhát hơn ở nhà trẻ mồ côi Hoa Hướng Dương. Tuy vậy, sâu trong tâm hồn các bé luôn là những đóa hoa tươi đẹp khiến chúng ta yêu mến khi tiếp xúc.</p>
<figure id="attachment_2564" aria-describedby="caption-attachment-2564" style="width: 960px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2564" src="https://media.huynhhieutravel.com/các-tình-nguyện-viên-của-help-portrait-cần-thơ.jpg" alt="Các tình nguyện viên của Help Portrait Cần Thơ" width="960" height="640" srcset="https://media.huynhhieutravel.com/các-tình-nguyện-viên-của-help-portrait-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/các-tình-nguyện-viên-của-help-portrait-cần-thơ-768x512.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2564" class="wp-caption-text">Các tình nguyện viên của Help Portrait Cần Thơ</figcaption></figure>
<h4>Nhà Nuôi Dưỡng Người Già Và Trẻ Em Không Nơi Nương Tựa</h4>
<p>Đây là nơi nuôi dưỡng gần 100 cụ già và một số trẻ em không nơi nương tựa. Các cụ sinh hoạt và sống cùng nhau trong các căn phòng chật hẹp. Đặc biệt, nơi đây có một số cụ không đi lại dễ dàng. Nên nơi đây có các cô hộ lý chăm sóc các cụ về ăn mặc, vệ sinh cá nhân. Gần như ở đây thiếu cái sinh khí của người trẻ, thiếu sự hoạt nào và sự động viên tình cảm của những &#8220;người con&#8221;.</p>
<p>Tôi luôn có những kỷ niệm đẹp khi đến đây. Những nhà trẻ luôn tràn đầy năng lượng của các bé khi vui đùa. Còn ở đây, luôn tràn đầy những câu chuyện, những sẽ chia từ thế hệ trước. Họ cần những người bạn, những người con sẽ chia cuộc sống rất nhiều. Khi đến đây, hãy tâm sự thật nhiều cùng họ nhé!</p>
<figure id="attachment_2563" aria-describedby="caption-attachment-2563" style="width: 960px" class="wp-caption aligncenter"><img decoding="async" class="size-full wp-image-2563" src="https://media.huynhhieutravel.com/các-tình-nguyện-viên-chăm-sóc-các-cụ-già-ở-hội-dưỡng-lão-cần-thơ.jpg" alt="Các tình nguyện viên chăm sóc các cụ già ở hội dưỡng lão Cần Thơ" width="960" height="636" srcset="https://media.huynhhieutravel.com/các-tình-nguyện-viên-chăm-sóc-các-cụ-già-ở-hội-dưỡng-lão-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/các-tình-nguyện-viên-chăm-sóc-các-cụ-già-ở-hội-dưỡng-lão-cần-thơ-768x509.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2563" class="wp-caption-text">Các tình nguyện viên chăm sóc các cụ già ở hội dưỡng lão Cần Thơ</figcaption></figure>
<h4>Hội người khuyết tật Cần Thơ</h4>
<p>Mỗi năm chúng tôi luôn đến đây sớm hơn vào ngày xuất phát chính thức hàng năm của Help Portrait Cần Thơ. Vì ngày quốc tế người khuyết tật vào ngày 1/12 hàng năm là ngày kỷ niệm và tụ họp của các người khuyết tật từ nhiều điểm đến Cần Thơ. Nơi đây luôn có những người khuyết tật với những sự lạc quan, tích cực trong cuộc sống.</p>
<figure id="attachment_2575" aria-describedby="caption-attachment-2575" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2575" src="https://media.huynhhieutravel.com/team-help-portrait-cần-thơ-chụp-ảnh-cùng-hội-khuyết-tật-cần-thơ.jpg" alt="Team Help Portrait Cần Thơ chụp ảnh cùng Hội khuyết tật Cần Thơ" width="1280" height="853" srcset="https://media.huynhhieutravel.com/team-help-portrait-cần-thơ-chụp-ảnh-cùng-hội-khuyết-tật-cần-thơ.jpg 1280w, https://media.huynhhieutravel.com/team-help-portrait-cần-thơ-chụp-ảnh-cùng-hội-khuyết-tật-cần-thơ-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-2575" class="wp-caption-text">Team Help Portrait Cần Thơ chụp ảnh cùng Hội khuyết tật Cần Thơ</figcaption></figure>
<h4>Nhà trẻ Thiên Ân</h4>
<p>Nơi đây còn gọi là mái ấm Thiên Ân. Nó không chỉ còn là nơi nuôi dạy cưu mang những đứa bé mồ côi nữa. Mà nó là một mái ấm, một gia đình của những đứa trẻ đó. Những đứa trẻ ở đây đến từ nhiều nơi với xuất thân khác nhau. Có những đứa bé đôi khi chưa biết nói tiếng Việt, chúng nó chỉ bập bẹ nói những tiếng Khmer. Hay có những đứa bé ngẩn ngơ đôi khi khóc nhè hỏi rằng mẹ chúng đâu. Nhưng chúng đã về sống chung một mái nhà và được đùm bọc bởi những cô bảo mẫu dễ thương và đầy tình thương.</p>
<figure id="attachment_2573" aria-describedby="caption-attachment-2573" style="width: 960px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2573" src="https://media.huynhhieutravel.com/một-em-bé-dễ-thương-ở-nhà-trẻ-Thiên-Ân.jpg" alt="Một em bé dễ thương ở nhà trẻ Thiên Ân" width="960" height="636" srcset="https://media.huynhhieutravel.com/một-em-bé-dễ-thương-ở-nhà-trẻ-Thiên-Ân.jpg 960w, https://media.huynhhieutravel.com/một-em-bé-dễ-thương-ở-nhà-trẻ-Thiên-Ân-768x509.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2573" class="wp-caption-text">Một em bé dễ thương ở nhà trẻ Thiên Ân</figcaption></figure>
<h4>Hội Nạn Nhân Chất Độc Màu Da Cam</h4>
<p>Nơi đây ban đầu nuôi dưỡng những đứa trẻ, những nạn nhân bị căn bệnh chất độc màu da cam tàn độc. Những đứa trẻ với hình thù kỳ dị hơn người thường. Nhưng ẩn dấu bên trong hình thù kỳ dị đó là một tâm hồn như bao tâm hồn người bình thường. Nhưng nó dần khép kín, tổn thương bởi sự xa lánh, kỳ thì của những người bình thường khác.</p>
<p>Ngoài ra, nơi đây còn nuôi dạy nhiều đứa trẻ bình thường khác nhưng bị ba mẹ bỏ rơi từ nhỏ. Những đứa trẻ lớn lên nếu may mắn chúng sẽ được những người lớn nhận nuôi. Hoặc chúng phải sống trong hiu quạnh nơi căn nhà lớn nhưng tình thương thiếu hụt.</p>
<figure id="attachment_2571" aria-describedby="caption-attachment-2571" style="width: 960px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2571" src="https://media.huynhhieutravel.com/help-portrait-cần-thơ-đến-thăm-hội-người-già-cần-thơ.jpg" alt="Help Portrait Cần Thơ đến thăm hội người già Cần Thơ" width="960" height="640" srcset="https://media.huynhhieutravel.com/help-portrait-cần-thơ-đến-thăm-hội-người-già-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/help-portrait-cần-thơ-đến-thăm-hội-người-già-cần-thơ-768x512.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2571" class="wp-caption-text">Help Portrait Cần Thơ đến thăm hội người già Cần Thơ</figcaption></figure>
<h3>Tổng kết số lượng thống kê Help Portrait Cần Thơ</h3>
<h4>Help Portrait Cần Thơ 2014</h4>
<ul>
<li>Số lượng tình nguyện viên: 80 người.</li>
<li>Số lượng điểm chụp: 6.</li>
<li>Số lượng ảnh chụp: hơn 800 ảnh.</li>
</ul>
<figure id="attachment_2566" aria-describedby="caption-attachment-2566" style="width: 500px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-2566" src="https://media.huynhhieutravel.com/chương-trình-help-portrait-cần-thơ.jpg" alt="Chương trình Help Portrait Cần Thơ" width="500" height="332" srcset="https://media.huynhhieutravel.com/chương-trình-help-portrait-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/chương-trình-help-portrait-cần-thơ-768x510.jpg 768w" sizes="(max-width: 500px) 100vw, 500px" /><figcaption id="caption-attachment-2566" class="wp-caption-text">Chương trình Help Portrait Cần Thơ</figcaption></figure>
<h4>Help Portrait Cần Thơ 2015</h4>
<ul>
<li>Số lượng tình nguyện viên: 120 người.</li>
<li>Số lượng điểm chụp: 5.</li>
<li>Số lượng ảnh chụp: hơn 700 ảnh.</li>
</ul>
<figure id="attachment_2567" aria-describedby="caption-attachment-2567" style="width: 500px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-2567" src="https://media.huynhhieutravel.com/đội-ngũ-chụp-ảnh-của-help-portrait-cần-thơ.jpg" alt="Đội ngũ chụp ảnh của Help Portrait Cần Thơ" width="500" height="331" srcset="https://media.huynhhieutravel.com/đội-ngũ-chụp-ảnh-của-help-portrait-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/đội-ngũ-chụp-ảnh-của-help-portrait-cần-thơ-768x509.jpg 768w" sizes="(max-width: 500px) 100vw, 500px" /><figcaption id="caption-attachment-2567" class="wp-caption-text">Đội ngũ chụp ảnh của Help Portrait Cần Thơ</figcaption></figure>
<h4>Help Portrait Cần Thơ 2016</h4>
<ul>
<li>Số lượng tình nguyện viên: 60 người.</li>
<li>Số lượng điểm chụp: 5.</li>
<li>Số lượng ảnh chụp: hơn 700 ảnh.</li>
</ul>
<figure id="attachment_2568" aria-describedby="caption-attachment-2568" style="width: 500px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-2568" src="https://media.huynhhieutravel.com/hậu-trường-chụp-ảnh-help-portrait-cần-thơ.jpg" alt="Hậu trường chụp ảnh Help Portrait Cần Thơ" width="500" height="333" srcset="https://media.huynhhieutravel.com/hậu-trường-chụp-ảnh-help-portrait-cần-thơ.jpg 960w, https://media.huynhhieutravel.com/hậu-trường-chụp-ảnh-help-portrait-cần-thơ-768x512.jpg 768w" sizes="(max-width: 500px) 100vw, 500px" /><figcaption id="caption-attachment-2568" class="wp-caption-text">Hậu trường chụp ảnh Help Portrait Cần Thơ</figcaption></figure>
<h4>Help Portrait Cần Thơ 2017</h4>
<ul>
<li>Số lượng tình nguyện viên: 50 người.</li>
<li>Số lượng điểm chụp: 4.</li>
<li>Số lượng ảnh chụp: hơn 600 ảnh.</li>
</ul>
<figure id="attachment_2576" aria-describedby="caption-attachment-2576" style="width: 500px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-2576" src="https://media.huynhhieutravel.com/thẻ-ban-tổ-chức-help-portrait-cần-thơ.jpg" alt="Thẻ ban tổ chức Help Portrait Cần Thơ" width="500" height="667"><figcaption id="caption-attachment-2576" class="wp-caption-text">Thẻ ban tổ chức Help Portrait Cần Thơ</figcaption></figure>
<h4>Help Portrait Cần Thơ 2018: Đang cập nhật</h4>
<h2>Ý nghĩa của Help Portrait</h2>
<p>Help Portait Cần Thơ, Việt Nam hay dù bất kỳ quốc gia nào đều mang những ý nghĩa chung</p>
<h4>Giúp họ tìm ý tưởng mới cho cuộc sống của mình</h4>
<p>Một thành viên team Help Portrait Cần Thơ chia sẽ: &#8220;Tôi đã có một ngày tuyệt vời cùng Help Portrait Cần Thơ. Tôi đi cùng những người bạn mình đến một nhà trẻ cách xa trung tâm thành phố Cần Thơ. Chúng tôi làm việc khá tích cực và có tâm để trang điểm cho những đứa bé ở nhà trẻ mồ côi đó. Chúng tôi sử dụng những cây cọ, son của mình tạo nên điều gì đó tích cực, vui vẻ, dễ thương và có chút gì đó tỏa sáng trên khuôn mặt của những đứa bé. Thật tuyệt vời, khi những nụ cười tỏa sáng và sự hài lòng của chúng luôn thể hiện ra trên khuôn mặt đó.&#8221;</p>
<figure id="attachment_2578" aria-describedby="caption-attachment-2578" style="width: 960px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2578" src="https://media.huynhhieutravel.com/tình-nguyện-viên-help-portrait-cần-thơ-dỗ-dành-một-đứa-bé-đang-khóc.jpg" alt="Tình nguyện viên Help Portrait Cần Thơ dỗ dành một đứa bé đang khóc" width="960" height="636" srcset="https://media.huynhhieutravel.com/tình-nguyện-viên-help-portrait-cần-thơ-dỗ-dành-một-đứa-bé-đang-khóc.jpg 960w, https://media.huynhhieutravel.com/tình-nguyện-viên-help-portrait-cần-thơ-dỗ-dành-một-đứa-bé-đang-khóc-768x509.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-2578" class="wp-caption-text">Tình nguyện viên Help Portrait Cần Thơ dỗ dành một đứa bé đang khóc</figcaption></figure>
<p>Bạn Hiếu chia sẽ thêm: &#8220;Thật tuyệt vời! Chúng tôi mang cả một đội ngũ chuyên nghiệp như Hollywood vậy. Từ chuyên viên make up, hậu cần, làm tóc đến những thợ chụp ảnh tốt nhất. Đó là một ngày tuyệt vời. Những đứa trẻ bảo tôi rằng nó đã tìm ra những điều mới mẻ hơn trong cuộc sống của nó. Bọn chúng khỏe tôi những bức hình, nụ cười luôn tươi rói trên môi.&#8221;</p>
<h4>Hạnh phúc là thứ cần được chia sẽ</h4>
<p>Chúng tôi nhận ra rằng khi chia sẽ những bức hình tươi rói của những đứa trẻ đó, những người xem cũng thấy vui vẻ cùng. Không những là những đóng góp thêm về mặt tài trợ. Mà họ còn hỏi tôi là tại sao cậu lại làm đứa bé đó cười tươi đến vậy? Đơn giản là tôi chia sẽ niềm hạnh phúc của tôi cùng đứa bé đó, đứa bé đó lại truyền niềm hạnh phúc vào những bức ảnh và chia sẽ thêm nhiều nơi.</p>
<p>Và bạn có muốn cùng chia sẽ những khoảnh khắc đó ở ngay tại quê hương, tỉnh thành hay quận huyện của bạn đến chúng tôi? Cộng đồng ở Cần Thơ đã tạo dựng được một Help Portrait Cần Thơ trải dài 5 năm và có thể hơn thế nữa. Vậy tại sao bạn không thử?</p>
<h4>Không chỉ những đứa trẻ mà cả tình nguyện viên là những người nhận được thêm điều gì đó</h4>
<p>Help Portrait Cần Thơ đến tặng quà cho những đứa trẻ. Dĩ nhiên những đứa bé đó nhận được những món quà, những tấm ảnh và cả sự nồng nhiệt từ tình nguyện viên. Đó là thời gian, công sức và tiền bạc cho những bộ trang điểm, những bức ảnh rửa ra. Nhưng chúng tôi bỏ ra để nhận được. Chúng tôi nhận được nụ cười từ những đứa bé. Chúng tôi lưu giữ những khoảnh khắc hồn nhiên của chúng. Chúng tôi làm ra những ký ức được lưu giữ qua những tấm hình.</p>
<p>Đôi khi món quà quý giá của cuộc sống không chỉ là vật chất, mà là những ký ức tuyệt vời mà bạn lưu giữ được. Khi nghĩ đến chúng thôi bạn cũng đã thấy hạnh phúc tràn đầy.</p>
<h2>Cách thức đăng ký Help Portrait Cần Thơ</h2>
<p>Chương trình Help Portrait Cần Thơ hưởng ứng theo chương trình toàn cầu và Việt Nam với ngày tổ chức hàng năm là ngày cuối tuần đầu tiên của tháng 12. Năm 2018 sẽ được tổ chức vào ngày 8/12/2018. Bạn có thể đăng ký chương trình Help Portrait Cần Thơ năm 2018 qua link: <a href="http://bit.ly/HelpPortrait2018">Đăng ký Help Portrait Cần Thơ 2018.</a></p>
<p>Những thông tin mới nhất về Help Portrait Cần Thơ sẽ được update trên group facebook: <a href="https://www.facebook.com/groups/1388697448038847/">Group Facebook Help Portrait Cần Thơ.</a></p>
<p>Bạn cũng có thể tìm hiểu và update các thông tin mới của Help Portrait Việt Nam qua: <a href="https://www.facebook.com/helpportraitvn/">Group Facebook Help Portrait Việt Nam.</a></p>
<p>Trang web Help Portrait toàn cầu:&nbsp;<a href="http://help-portrait.com/">http://help-portrait.com/</a></p>
', 'Help Portrait Cần Thơ là một ngày hội chụp ảnh chân dung ở Cần Thơ hưởng ứng theo chiến dịch Help Portrait toàn cầu. Help Portrait là phong trào toàn cầu các nhiếp ảnh gia và những nhà hậu cần (make up, làm tóc,&#8230;) sử dụng dụ cụ và chuyên môn của mình làm nên [&hellip;]', 2570, 'post', '2018-11-21 06:09:52', '2023-04-23 12:25:49');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (2562, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (2562, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (2562, 97);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (2334, 'La Viet Coffee Đà Lạt', 'la-viet-coffee-da-lat', '<p><strong>La Viet Coffee Đà Lạt</strong> là một quán cafe dành cho những <strong>người yêu cafe</strong> đích thực. Nơi đây cafe được đánh giá là đủ độ mạnh để làm &#8220;<strong>say cafe</strong>&#8221; bất kỳ ai. Tôi đã đến đây một lần, chỉ cần bước vào thì mùi cafe thoang thoảng bốc lên cũng đủ làm bạn ngất ngây. Điều đặc biệt của La Viet Coffee là đem mô hình công xưởng của mình vào trong quán cafe. Không những bạn được xem người chế biến cafe làm ngay tại quầy. Mà bạn còn được xuống tận công xưởng xem quy trình chế biến cafe của La Viet Coffee.</p>
<h2>Thông tin La Viet Coffee Đà Lạt</h2>
<p>Là Viet Coffee Đà Lạt nằm cách trung tâm Đà Lạt khoảng <strong>3km</strong> về hướng đồi Thiên Phúc Đức. Nhắc đến quán cafe ở Đà Lạt dành cho những tín đồ cafe đích thức thì ta không thể bỏ qua La Viet Coffee. Bạn chỉ cần bước vào quán cafe này, vừa mở cửa ra thì mùi cafe đã xông thẳng vào mũi làm bạn ngất ngây. Quán cafe chia làm hai khu là khu chế biến phục vụ khách và xưởng cafe để chế biến hạt cafe.</p>
<p><strong>Địa chỉ</strong>: 200 Nguyễn Công Trứ, Phường 8, Thành phố Đà Lạt, Lâm Đồng, Việt Nam.</p>
<p><strong>Số điện thoại</strong>: 0966592942</p>
<p><strong>Giờ mở cửa</strong>: 7h30-21h30.</p>
<p><strong>Mức giá</strong>: 30.000đ-55.000đ.</p>
<p><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15613.498167868986!2d108.43452054579254!3d11.948549750727421!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x69dd101b15161e40!2sLa+Viet+Coffee!5e0!3m2!1svi!2s!4v1542468247351" width="600" height="450" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h3>La Viet Coffee Đà Lạt có gì đặc biệt?</h3>
<p>La Viet Coffee luôn là điểm hẹn hàng đầu của nhiều bạn trẻ, đặc biệt là những người mê cafe. Ngoài điểm chính là Đà Lạt thì quán còn có cả chi nhánh ở Sài Gòn. Vậy điều gì làm nên sự đặc biệt của La Viet Coffee Đà Lạt?</p>
<h4>Chất lượng cafe tuyệt hảo</h4>
<p>Chất lượng cafe ở La Viet Coffee Đà Lạt tuyệt vời vô cùng. Các loại cafe ở đây cũng tương tự như ở các quán cafe khác. Từ cafe đen, cafe sữa thuần việt đến các loại cafe tây như capuccino, expresso,&#8230; Nhưng hương vị lại đậm đà và độc đáo hơn các quán khác vô cùng. Nơi đây những hạt cafe nguyên chất được trồng từ những cánh đồng cafe riêng.</p>
<p>Khi pha chế, các barista đều có dụng cụ cân nguyên liệu rõ ràng. Mỗi loại cafe đều có thành phần nước và cafe khác nhau. Vị ngon của nó tùy thuộc vào tỷ lệ nước:hạt cafe arabica và cả thời gian chiết xuất và cách chiết xuất. Nơi đây, các barista đều được cung cấp một công thức chuẩn mực và các thiết bị đo lường chính xác. Ngoài ra, thông thường chúng ta chiết xuất cafe phin bằng nước nóng. Thì ở La Viet Coffee lại chiết xuất cafe bằng nhưng viên đá lạnh. Tất cả đều tuân thủ quy tắc chiết xuất cafe giữ lại hương vị toàn vẹn nhất của hạt cafe.</p>
<figure id="attachment_2339" aria-describedby="caption-attachment-2339" style="width: 594px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2339" src="https://media.huynhhieutravel.com/thưởng-thức-cafe-là-việt-đà-lạt.jpg" alt="Thưởng thức cafe La Viet Đà Lạt" width="594" height="421" /><figcaption id="caption-attachment-2339" class="wp-caption-text">Thưởng thức cafe La Viet Đà Lạt</figcaption></figure>
<h4>Tìm hiểu về 2 loại cafe ở La Viet Coffee Đà Lạt</h4>
<p>Loại đầu tiên phải kể đến là hạt cafe arabica. Đây luôn là chất liệu làm nên những ly cafe specialty tuyệt vời nhất. Đặc trưng của hạt cafe arabica là mùi thơm, vị chua ngọt riêng. Hạt arabica phải được chiết xuất và pha trực tiếp chứ không thêm vào đường hay sữa như các loại cafe thông thường khác. Bạn phải dùng những cách chiết xuất đặc biệt chứ không phải giống như chiết xuất kiểu cafe phin là qua nước nóng. Nên hạt cafe arabica là chất lượng tuyệt hảo làm nên những ly cafe specialty hảo hạng, mắc tiền.</p>
<p>Loại thứ hai là hạt cafe robusta. Đây là loại cafe thông dụng nhất ở Việt Nam, nó được dụng hầu hết các quán cafe bình thường. Vị cafe của hạt robusta có hậu đắng, màu đen sánh. Nên nó thường được dùng chung với đường và sữa pha thành các ly cafe đen hay cafe sữa.</p>
<figure id="attachment_2337" aria-describedby="caption-attachment-2337" style="width: 598px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2337" src="https://media.huynhhieutravel.com/la-viet-có-những-sách-nói-về-cafe-khá-hay.jpg" alt="La Viet có những sách nói về cafe khá hay" width="598" height="597" srcset="https://media.huynhhieutravel.com/la-viet-có-những-sách-nói-về-cafe-khá-hay.jpg 598w, https://media.huynhhieutravel.com/la-viet-có-những-sách-nói-về-cafe-khá-hay-150x150.jpg 150w" sizes="(max-width: 598px) 100vw, 598px" /><figcaption id="caption-attachment-2337" class="wp-caption-text">La Viet có những sách nói về cafe khá hay</figcaption></figure>
<h4>Không gian bình dân nhưng thu hút và thoải mái</h4>
<p>Không gian quán cafe thường phải rất lung linh với đầy đủ các loại tiểu cảnh khác nhau nhưng La Viet Coffee Đà Lạt thì không phải vậy. Nó có một không gian khá bình dân nhưng rộng rãi thoải mái. Dường như nó muốn tạo cảm giác thân thiện cùng người đến thưởng thức cafe. Màu chủ đạo ở đây là trắng đen. Trần nhà được lợp một lớp tôn bình thường.</p>
<p>Quầy pha chế nhiều dụng cụ phức tạp nhưng được xây dựng giản đơn. Phía sau quầy là một bản đen, vẽ nguệch ngoạc menu các loại cafe đặc trưng. Bạn có thể ngồi ngay tại chỗ gần quầy xem các bạn pha chế cafe trực tiếp. Đôi khi vừa ngồi tám chuyện vừa xem ly cafe của mình gọi được pha chế kỳ công như thế nào thì cũng tuyệt vời đúng không?</p>
<figure id="attachment_2338" aria-describedby="caption-attachment-2338" style="width: 598px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2338" src="https://media.huynhhieutravel.com/la-viet-da-lat.jpg" alt="La Viet Đà Lạt" width="598" height="600" srcset="https://media.huynhhieutravel.com/la-viet-da-lat.jpg 598w, https://media.huynhhieutravel.com/la-viet-da-lat-150x150.jpg 150w" sizes="(max-width: 598px) 100vw, 598px" /><figcaption id="caption-attachment-2338" class="wp-caption-text">La Viet Đà Lạt</figcaption></figure>
<h4>Một công xưởng cafe thu nhỏ phía sau</h4>
<p>Điều đặc biệt làm nên thương hiệu cafe tuyệt vời của La Viet Coffee không chỉ là công thức cafe chuẩn mực mà còn nằm ở công xưởng sản xuất hạt cafe trực tiếp của quán. Bạn sẽ được tham quan một công xưởng cafe ngay phía sau quán. Tất cả các công đoạn từ lặt tay hạt cafe, rang, xay hạt cafe cho đến đóng gói với các máy móc hiện đại theo tiêu chuẩn Mỹ.</p>
<figure id="attachment_2341" aria-describedby="caption-attachment-2341" style="width: 400px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="wp-image-2341" src="https://media.huynhhieutravel.com/xuong-san-xuat-cafe-la-viet.jpg" alt="Xưởng sản xuất cafe La Viet" width="400" height="502" /><figcaption id="caption-attachment-2341" class="wp-caption-text">Xưởng sản xuất cafe La Viet</figcaption></figure>
<h4>Tour La Viet Coffee Đà Lạt tìm hiểu về cafe</h4>
<p>Bạn cũng có thể đăng ký tham gia tour 1 ngày của La Viet Coffee Đà Lạt để tìm hiểu về quy trình sản xuất cafe ngay tại nông trại. Bạn sẽ được tham gia toàn bộ quy trình sản xuất cafe từ thu hoạch ngay vùng nguyên liệu đến các giai đoạn ở xưởng cafe và tự tay chế biến ly cafe cho mình. Tất cả công đoạn từ A-Z chế biến nên một ly cafe từ hạt cafe.</p>
<figure id="attachment_2340" aria-describedby="caption-attachment-2340" style="width: 598px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-2340" src="https://media.huynhhieutravel.com/tour-cafe-la-viet.jpg" alt="Tour cafe La Viet Đà Lạt" width="598" height="399" /><figcaption id="caption-attachment-2340" class="wp-caption-text">Tour cafe La Viet Đà Lạt</figcaption></figure>
<h3>Đường đi đến La Viet Coffee Đà Lạt</h3>
<p>Quán cafe La Viet Coffee Đà Lạt nằm trên đường Nguyễn Công Trứ cách Đà Lạt khoảng 3km. Bạn có thể di chuyển bằng xe máy hoặc xe hơi đến đây. Đường đi khá dễ dàng và quán có chỗ đậu xe hơi. Bạn nhập tọa độ hoặc bật định vị từ vị trí của mình vào link này nhé: <a href="https://www.google.com/maps/dir//La+Viet+Coffee,+200+Nguy%E1%BB%85n+C%C3%B4ng+Tr%E1%BB%A9,+Ph%C6%B0%E1%BB%9Dng+8,+Th%C3%A0nh+ph%E1%BB%91+%C4%90%C3%A0+L%E1%BA%A1t,+L%C3%A2m+%C4%90%E1%BB%93ng,+Vi%E1%BB%87t+Nam/@11.948852,108.4310041,15z/data=!4m8!4m7!1m0!1m5!1m1!1s0x317112d0ec679cb9:0x69dd101b15161e40!2m2!1d108.4351652!2d11.9568492">Tọa độ và cách đi đến La Viet Coffee Đà Lạt.</a></p>
<h3>Mức giá ở La Viet Coffee Đà Lạt</h3>
<p>Quán chủ yếu bán các loại cafe. Ngoài ra cũng có một vài loại nước uống khác nhưng không quá đa dạng. Mức giá từ 30.000đ-55.000đ. Giá hiện tại của tour 1 ngày sản xuất cafe là 75$ bao gồm các chi phí di chuyển, ăn trưa và hướng dẫn viên trong 8 tiếng.</p>
<p><em><strong>Lưu ý: Mức giá được lấy dữ liệu tháng 11 năm 2018 và có thể thay đổi theo giá thị trường!</strong></em></p>
<h3>Thời điểm thích hợp đi La Viet Coffee Đà Lạt</h3>
<p>Bạn nên đến đây vào buổi sáng sớm để đón những ánh nắng đẹp và tránh dòng người đông đúc đến quán. Lựa một chỗ vị trí gần quầy pha chế, vừa ngồi tám chuyện vừa xem barista pha chế nước uống cho mình.</p>
<h2>Review La Viet Coffee Đà Lạt</h2>
<p>La Viet Coffee Đà Lạt có đặc trưng là những ly cafe tuyệt vời hảo hạng làm say đắm bất kỳ ai yêu cafe. Bạn sẽ khó tìm được quán cafe nào khác được pha chế chuẩn mực từ nguyên liệu đến công đoạn chế biến cafe như La Viet Đà Lạt. Nhưng nó cũng chỉ dành cho những ai yêu cafe mà thôi. Nếu không phải là một tín đồ cafe thì nó có vẻ hơi tẻ nhạt. Nên hãy cân nhắc khi đến đây bạn nhé!</p>
<p><em><strong>Đánh giá</strong></em>: 7/10.</p>
<h3>Đánh giá của khách du lịch về La Viet Đà Lạt</h3>
<ul>
<li>Bạn Tien Khoa Nguyen đánh giá 5/5: &#8220;Nhân viên nhiệt tình, vui vẻ, thao tác tỉ mỉ và chuyên nghiệp. Các món nước được làm khá ngon, bánh croissant giòn thơm béo, thật sự là rất ngon. Lần đầu tiên thấy 1 quán lấy trà oloong làm trà phục vụ cho khách, vừa ấm vừa thơm. Nếu ai tò mò về cách sản xuất cafe thì nhờ mấy em phục vụ sẽ có người dẫn đi xem quy trình sản xuất cafe, các em nhiệt tình và giải đáp thắc mắc khi được hỏi. Một nơi đáng đến ở Đà Lạt.&#8221;</li>
</ul>
<p>Cảm ơn bạn Tien Khoa Nguyen về nhận xét rất có tâm và vô cùng đầy đủ.</p>
<ul>
<li>Bạn Quà Tặng đánh giá 5/5: &#8220;La Viet cà phê là nơi lý tưởng cho dân thưởng thức cà phê chuyên nghiệp, hương vị thơm ngon và giá mềm. Ở đây vừa là xưởng sản xuất cà phê vừa là nhà cung cấp chính cho hầu hết các quán cà phê ở Đà Lạt.&#8221;</li>
</ul>
<p>Đây là điểm uống cafe lý tưởng nhất ở Đà Lạt mà mình biết</p>
<figure id="attachment_2335" aria-describedby="caption-attachment-2335" style="width: 368px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-2335" src="https://media.huynhhieutravel.com/review-la-viet-coffee-đà-lạt.png" alt="Review La Viet Coffee Đà Lạt" width="368" height="540" /><figcaption id="caption-attachment-2335" class="wp-caption-text">Review La Viet Coffee Đà Lạt</figcaption></figure>
<p>Bài viết gần như tổng hợp tất cả những hiểu biết của mình về quán La Viet Coffee Đà Lạt. Nếu có thêm thông tin gì khác hãy cùng chia sẽ bạn nhé!</p>
<p>Email: <em><strong>huynhtronghieu1911@gmail.com</strong></em></p>
<p>Ngoài ra các bạn có thể tham khảo thêm những địa điểm du lịch thú vị khác:</p>
<blockquote class="wp-embedded-content" data-secret="ZYCnjMJVW5"><p><a href="https://huynhhieutravel.com/an-cafe-da-lat/">An Cafe Đà Lạt</a></p></blockquote>
<p><iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="position: absolute; clip: rect(1px, 1px, 1px, 1px);" title="&#8220;An Cafe Đà Lạt&#8221; &#8212; Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/an-cafe-da-lat/embed/#?secret=m75zxl98m1#?secret=ZYCnjMJVW5" data-secret="ZYCnjMJVW5" width="600" height="338" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></p>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Sunshine Coffee Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/sunshine-coffee-da-lat/embed/#?secret=it2DhEK9Qi" width="600" height="257" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="it2DhEK9Qi" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Quán Cafe F Cánh Đồng Hoa Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/quan-cafe-f-canh-dong-hoa-da-lat/embed/#?secret=Nvr9EZaRhd" width="600" height="257" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="Nvr9EZaRhd" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Up Coffee Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/up-coffee-da-lat/embed/#?secret=p15raVTfVy" width="600" height="257" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="p15raVTfVy" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Quán Cafe Thong Dalat Space” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/quan-cafe-thong-dalat-space/embed/#?secret=Pyipf05FQe" width="600" height="257" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="Pyipf05FQe" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Cầu thang vô cực Đà Lạt ở cafe Nông Trại Vui Vẻ Sunny Farm” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/cau-thang-vo-cuc-da-lat-o-cafe-nong-trai-vui-ve-sunny-farm/embed/#?secret=4SpjBabjQ4" width="600" height="287" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="4SpjBabjQ4" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Full House Coffee” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/full-house-coffee/embed/#?secret=kmIdtslepc" width="600" height="259" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="kmIdtslepc" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Cafe Panorama Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/cafe-panorama-da-lat/embed/#?secret=v5ttcRUcw8" width="600" height="259" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="v5ttcRUcw8" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Cafe Tỏi Đen Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/cafe-toi-den-da-lat/embed/#?secret=9Wfn9bP54H" width="600" height="259" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="9Wfn9bP54H" data-mce-fragment="1"></iframe></p>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Sense Coffee Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/sense-coffee-da-lat/embed/#?secret=I4yhlPSi9T" width="600" height="259" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="I4yhlPSi9T" data-mce-fragment="1"></iframe></p>
</div>
</div>
', 'La Viet Coffee Đà Lạt là một quán cafe dành cho những người yêu cafe đích thực. Nơi đây cafe được đánh giá là đủ độ mạnh để làm &#8220;say cafe&#8221; bất kỳ ai. Tôi đã đến đây một lần, chỉ cần bước vào thì mùi cafe thoang thoảng bốc lên cũng đủ làm bạn [&hellip;]', 2336, 'post', '2018-11-17 17:00:48', '2023-04-23 12:46:10');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (2334, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (2334, 48);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (2334, 269);