INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1028, 'Cách Đi Chợ Nổi Cái Răng &#8211; Kinh Nghiệm Du Lịch Nổi Cái Răng', 'cach-di-cho-noi-cai-rang', '<p>Chợ Nổi Cái Răng là một đặc trưng văn hóa phi vật thể Việt Nam. Nếu bạn đã đến Cần Thơ du lịch thì không thể không ghé nơi đây. Bạn sẽ được trải nghiệm ngồi ghe thuyền khám phá vùng chợ nổi đặc sắc này. Nhìn ngắm hàng trăm ghe tàu tấp nập mua bán các loại nông sản khác nhau. Bạn sẽ được chiêm ngưỡng một phong cảnh thú vị lúc bình minh. Ngoài ra, thưởng thức bữa ăn sáng với tô bún riêu ngay tại ghe thật sự tuyệt vời. Thêm vào đó, mua trái cây tươi ngon ngay chợ nổi để ăn ngay hoặc đem về làm quà biếu đều rất hay.</p>
<h2>Một Ngày Ở Chợ Nổi Cái Răng</h2>
<p><figure style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" src="https://nucuoimekong.com/wp-content/uploads/2018/06/Chợ-Nổi-Cái-Răng4.jpg" alt="Chợ Nổi Cái Răng flycam" width="1200" height="900"><figcaption class="wp-caption-text">Hình ảnh Chợ nổi Cái Răng chụp bằng flycam</figcaption></figure></p>
<p>Sáng 5h30 tôi xuất phát từ bến Ninh Kiều. Tôi lựa chọn ghe nhỏ để di chuyển để có sự riêng tư. Và cũng dễ dàng chụp hình và thăm thú bao lâu tùy thích ở Chợ Nổi Cái Răng.</p>
<p><figure id="attachment_1033" aria-describedby="caption-attachment-1033" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1033 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng5.jpg" alt="Bến tàu bến Ninh Kiều" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng5.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng5-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1033" class="wp-caption-text">Bến tàu Chợ Nổi Cái Răng &#8211; Huynh Hieu Travel</figcaption></figure></p>
<p>Dọc con đường thủy đến Chợ Nổi Cái Răng từ Bến Ninh Kiều, bạn có thể tranh thủ ngắm nhìn cảnh vật 2 bên sông. Những không gian rất yên tĩnh vào buổi sáng sớm. Ngoài ra những tòa nhà cao tầng từ thành phố ngắm nhìn rất đẹp. Tôi nhìn thấy tòa Vincome sừng sửng chiếm trọn một không gian lớn.</p>
<p><figure id="attachment_1031" aria-describedby="caption-attachment-1031" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1031 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng3.jpg" alt="Thuyền đi chợ nổi Cái Răng đi ngang qua tòa nhà Vinpearl Cần Thơ" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng3.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng3-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1031" class="wp-caption-text">Tòa nhà Vincom được chụp từ giữa sông</figcaption></figure></p>
<p>Thỉnh thoảng là những người dân đi ghe nhỏ đi đâu đó.</p>
<p><figure id="attachment_1034" aria-describedby="caption-attachment-1034" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1034 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng6.jpg" alt="Nếp sống sông nước của người dân sông Hậu" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng6.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng6-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1034" class="wp-caption-text">Chợ Nổi Cái Răng &#8211; Huynh Hieu Travel</figcaption></figure></p>
<p>Khi đến Chợ Nổi Cái Răng. Khung cảnh đầu tiên làm tôi phải thốt lên: &#8220;WOW, AMAZING!!!&#8221;. Rất nhiều tàu bè tấp nập, hàng trăm chiếc tàu ghe với đủ thứ loại nông sản trên đó.</p>
<p><figure style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" src="https://nucuoimekong.com/wp-content/uploads/2018/06/Chợ-Nổi-Cái-Răng2.jpg" alt="Ghe tàu tấp nập ở Chợ Nổi Cái Răng" width="1200" height="900"><figcaption class="wp-caption-text">Ghe tàu tấp nập ở Chợ Nổi Cái Răng qua góc nhìn flycam</figcaption></figure></p>
<p>Ghe nhỏ của chúng tôi len lỏi qua hàng chục con thuyền khác nhau. Ngắm nhìn những người tiểu thương nhộn nhịp mua bán, trao đổi hàng hóa và nông phẩm. Những thuyền lớn, ghe nhỏ chở đầy những nông phẩm trên đó: dứa, xoài, thanh long, mãng cầu, sầu riêng,&#8230;</p>
<p><figure id="attachment_1036" aria-describedby="caption-attachment-1036" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1036 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng8.jpg" alt="Một thuyền chở đầy thơm trên Chợ Nổi Cái Răng" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng8.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng8-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1036" class="wp-caption-text">Một thuyền chở đầy thơm trên Chợ Nổi Cái Răng</figcaption></figure></p>
<p>Thỉnh thoảng sẽ có những ghe nhỏ đi đến thuyền lớn. Họ đưa những nông sản từ thuyền lớn sang ghe nhỏ rồi vận chuyển vào bờ bán lại cho các chợ nhỏ hơn.</p>
<p><figure id="attachment_1035" aria-describedby="caption-attachment-1035" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1035" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng7.jpg" alt="Chợ Nổi Cái Răng" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng7.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng7-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1035" class="wp-caption-text">Chợ Nổi Cái Răng &#8211; Huynh Hieu Travel</figcaption></figure></p>
<p>Chúng tôi chạy chậm để thưởng thức một buổi sáng tốt lành ở xứ sở sông nước. Thỉnh thoảng một vài ghe bán đầy nước và thức ăn chào hàng chúng tôi. Thử uống một tách cafe sáng trên ghe, cảm giác thật khác lạ. Trên ghe hàng nước đủ các loại: nước ngọt, cafe, trà đường cho đến dừa tươi, chanh muối,&#8230;</p>
<p><figure id="attachment_1032" aria-describedby="caption-attachment-1032" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1032 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng4.jpg" alt="Ghe hàng nước di động" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng4.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng4-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1032" class="wp-caption-text">Ghe hàng nước di động</figcaption></figure></p>
<p>Đặc trưng nơi đây là một chợ buôn bán sỉ lâu đời. Hàng trăm ghe thuyền neo đậu sẳn bán những loại nông sản khác nhau. Thế cách nào để phân biệt thứ mình cần để mua giữa hàng trăm thuyền lớn? Những người miền sông nước đã nghĩ ra một cách quảng cáo sản phẩm rất hay. Đó là bán gì treo đó. Họ treo nông sản mình bán lên một cây sào, cột trên cao. Người mua chỉ cần nhìn từ xa là biết thuyền đó bán gì, tìm kiếm cũng trở nên dễ dàng hơn.</p>
<p><figure id="attachment_1029" aria-describedby="caption-attachment-1029" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1029 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng.jpg" alt="Bán bí thì treo bí lên cao" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1029" class="wp-caption-text">Bán bí thì treo bí lên cao</figcaption></figure></p>
<p>Nhìn lên cây bí ngô treo lủng lẳng. Bạn có thể biết tàu này bán một vựa đầy bí ngô.</p>
<p><figure id="attachment_1030" aria-describedby="caption-attachment-1030" style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1030 size-full" src="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng2.jpg" alt="Ghe bán bí ở chợ nổi Cái Răng" width="1200" height="900" srcset="https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng2.jpg 1200w, https://media.huynhhieutravel.com/Chợ-Nổi-Cái-Răng2-768x576.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /><figcaption id="caption-attachment-1030" class="wp-caption-text">Ghe bán bí ở chợ nổi Cái Răng</figcaption></figure></p>
<p>Thỉnh thoảng chúng ta cũng thấy những người khách du lịch tham quan Chợ Nổi Cái Răng với những gương mặt đầy thích thú. Cùng vẫy gọi xin chào với chúng ta từ xa.</p>
<p><figure style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" src="https://nucuoimekong.com/wp-content/uploads/2018/06/Chợ-Nổi-Cái-Răng16.jpg" alt="Những cô gái mặt áo bà bà tham quan chợ nổi Cái Răng" width="1200" height="675"><figcaption class="wp-caption-text">Những cô gái mặt áo bà bà tham quan chợ nổi Cái Răng</figcaption></figure></p>
<p>Hay những người khách nước ngoài với vẻ mặt đầy thư giãn hay thích thú tham quan Chợ Nổi Cái Răng</p>
<p><figure style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" src="https://nucuoimekong.com/wp-content/uploads/2018/06/Chợ-Nổi-Cái-Răng26.jpg" alt="Du khách nước ngoài thích thú tham quan chợ nổi Cái Răng" width="1200" height="675"><figcaption class="wp-caption-text">Du khách nước ngoài thích thú tham quan chợ nổi Cái Răng</figcaption></figure></p>
<p>Tham quan những điều thú vị. Nhưng bạn cũng đừng quên thưởng thức một tô bún hay hủ tiếu ở ngay trên ghe. Những ghe bán đồ ăn sáng với nhiều loại khác nhau có mùi vị vô cùng tuyệt vời. Ăn trên ghe cũng là một nghệ thuật tỉ mỉ. Bạn đừng để sóng đánh lắc lư thuyền làm văng nước ra ngoài nhé!</p>
<p><figure style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" src="https://nucuoimekong.com/wp-content/uploads/2018/06/Chợ-Nổi-Cái-Răng35.jpg" alt="Ăn hủ tiếu trên ghe ở Chợ Nổi Cái Răng" width="1200" height="675"><figcaption class="wp-caption-text">Ăn hủ tiếu trên ghe ở Chợ Nổi Cái Răng</figcaption></figure></p>
<p>Thỉnh thoảng có những người dân thân thiện xung quanh mời bạn mua trái cây. Những loại trái cây ở đây bao ngon, bao ăn. Bạn có thể thử trước khi mua về. Giá cả tương đương với chợ, bạn cũng có thể thử tài trả giá một ít. Trái cây ở đây từ vườn hái ra nên bạn cứ yên tâm hơn về chất lượng của nó.</p>
<p><figure style="width: 1200px" class="wp-caption alignnone"><img loading="lazy" decoding="async" src="https://nucuoimekong.com/wp-content/uploads/2018/06/Chợ-Nổi-Cái-Răng37.jpg" alt="Cô bán hàng mời người mua trên Chợ Nổi Cái Răng" width="1200" height="675"><figcaption class="wp-caption-text">Cô bán hàng mời người mua trên Chợ Nổi Cái Răng</figcaption></figure></p>
<p>Sau khi đi vài vòng chán chê. Tôi bắt đầu đi tiếp miệt vườn Cái Răng. Tham quan những vườn trái cây và làng nghề hủ tiếu.</p>
<h2>Kinh Nghiệm Đi Chợ Nổi Của Tôi</h2>
<p>Chợ Nổi Cái Răng là một điểm du lịch lý thú. Nhưng những cạnh tranh và khách đông đúc tạo nên một hệ thống du lịch hỗn loạn. Bạn cần một số kinh nghiệm trước để có một hành trình thú vị ở Chợ Nổi Cái Răng.</p>
<h2>Lựa Chọn Một Dịch Vụ Thuê Tàu Uy Tín</h2>
<p>Chợ Nổi Cái Răng với nhiều cò mồi thuê tàu khác nhau. Bạn sẽ hoang mang khi đến bến Ninh Kiều bởi những lời mời gọi rất nhiều. Sẽ có những dịch vụ tốt ở trong đó nhưng cũng có thể bạn sẽ gặp xui với một dịch vụ du lịch tệ hại. Với những dịch vụ không rõ ràng, bạn dễ dàng thành con mồi ngon cho các hãng du lịch không tốt.</p>
<p>Bạn nên chọn một nhà dịch vụ du lịch có uy tín và trụ sở rõ ràng. Tôi đã tìm hiểu và lựa chọn dịch vụ của công ty địa phương là Nụ Cười Mekong. Họ có một trụ sở ở Bến Ninh Kiều và hoạt động uy tín.</p>
<p><strong>Nếu đi lẻ 1,2 người bạn có thể chọn:</strong></p>
<ul>
<li>Tour Chợ Nổi Cái Răng + Miệt Vườn:&nbsp;<a href="http://bit.ly/2tJKkFV">http://bit.ly/2tJKkFV</a></li>
<li>Tour chỉ đi Chợ Nổi Cái Răng:&nbsp;<a href="http://bit.ly/2J47rBV">http://bit.ly/2J47rBV</a></li>
</ul>
<p><strong>Hoặc nếu đi đông bạn có thể thuê ghe riêng:</strong></p>
<ul>
<li><a href="http://bit.ly/2J47rBV">http://bit.ly/2J47rBV</a></li>
</ul>
<h3>Bảng Giá Cho Thuê Tàu Chợ Nổi Cái Răng</h3>
<p>Bảng giá cho thuê tàu Chợ Nổi Cái Răng được cập nhật tháng 10/2018. Bạn có thể liên hệ&nbsp;+84939729609 (Mr. Thái) để đặt vé tàu:</p>
<p><figure id="attachment_1967" aria-describedby="caption-attachment-1967" style="width: 787px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1967" src="https://media.huynhhieutravel.com/Bảng-giá-thuê-tàu-chợ-nổi-cái-răng.png" alt="Bảng giá cho thuê tàu đi Chợ Nổi Cái Răng" width="787" height="214" srcset="https://media.huynhhieutravel.com/Bảng-giá-thuê-tàu-chợ-nổi-cái-răng.png 787w, https://media.huynhhieutravel.com/Bảng-giá-thuê-tàu-chợ-nổi-cái-răng-768x209.png 768w" sizes="(max-width: 787px) 100vw, 787px" /><figcaption id="caption-attachment-1967" class="wp-caption-text">Bảng giá cho thuê tàu đi Chợ Nổi Cái Răng</figcaption></figure></p>
<h2>Lựa Chọn Thời Gian Thích Hợp Để Đi</h2>
<p>Chợ Nổi Cái Răng chỉ hoạt động vào buổi sáng. Bạn có thể đi từ 5h-6h xuất phát từ bến Ninh Kiều để tránh cái nắng gắt. Và đón buổi họp chợ đúng thời điểm hơn. Hoặc từ 7h-8h bạn có thể đón ánh sáng tốt hơn để có những bức hình đẹp. Nhưng bạn cần trang bị kem chống nắng thật tốt.</p>
<h3>Các chiêu trò lừa gạt và kinh nghiệm phòng tránh khi đi chợ nổi Cái Răng</h3>
<p><em><strong>Ăn bún trên ghe hay bè với giá cắt cổ</strong></em></p>
<p>Trước đây ăn trên ghe khi đến chợ nổi ở cuối chợ do bà Hai bán khá tốt. Giá cả và nước lèo rất ngon nhưng hiện tại bà Hai đã không còn bán nữa. Những ghe tàu bàn ở cuối chợ thường móc nối với láy tàu để lấy tiền khách du lịch. Một tô hủ tiếu có giá từ 20.000-25.000 đã được đôn thành 40.000đ/tô. Bạn nên hỏi giá và thỏa thuận giá trước khi ăn.</p>
<p><em><strong>Chở đến nhiều điểm mua sắm tẻ nhạt</strong></em></p>
<p>Thường khi đến một điểm mua sắm, tài công sẽ được nhận một ít tiền boa. Và bạn càng mua nhiều thì tài công càng được tiền. Bạn nên xem xét nói thẳng với tài công là sẽ không đến những điểm mua sắm. Thông thường những điểm ấy chỉ bán khô, bánh các loại và giá khá mắc.</p>
<p><em><strong>Chở nhanh hoặc lòng vòng cho có rồi về</strong></em></p>
<p>Tài công một số chỗ thiếu uy tín thường chỉ chở bạn một vòng rồi về hoặc hay đi lòng vòng các địa điểm mua sắm rồi nói hết thời gian. Bạn nên thuê tàu ở những điểm du lịch chợ nổi chất lượng đừng trả giá với người dân ở bến Ninh Kiều. Khi đi cùng tài công, bạn nên thỏa thuận trước và hiểu về quyền lợi của bạn. Trong 2,3,4 tiếng thuê tàu, bạn có quyền kêu tài công đưa đi 2,3 vòng chợ nổi Cái Răng để chụp hình thêm. Bạn cũng có quyền linh động thay đổi địa điểm đi trước. Nhớ boa cho tài công nếu họ đi tàu có tâm bạn nhé!</p>
<h3>Video về chợ nổi Cái Răng</h3>
<p>Video một ngày ở Chợ Nổi Cái Răng. Cùng xem tận mắt để thấy nó hấp dẫn ra sao bạn nhé!</p>
<p><iframe title="Dậy sớm thuê tàu đi chợ nổi Cái Răng ở Cần Thơ từ bến Ninh Kiều" width="800" height="450" src="https://www.youtube.com/embed/h6RMvEIRQZk?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
', 'Chợ Nổi Cái Răng là một đặc trưng văn hóa phi vật thể Việt Nam. Nếu bạn đã đến Cần Thơ du lịch thì không thể không ghé nơi đây. Bạn sẽ được trải nghiệm ngồi ghe thuyền khám phá vùng chợ nổi đặc sắc này. Nhìn ngắm hàng trăm ghe tàu tấp nập mua [&hellip;]', 1035, 'post', '2018-06-29 05:35:55', '2023-04-23 12:47:41');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1028, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1028, 105);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1028, 302);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1025, 'Triệu Đà &#8211; Kẻ Xâm Lược Hay Vị Vua Có Công Của Việt Nam?', 'trieu-da', '<p>Triệu Đà là người khởi đầu cho sự cai trị của dòng họ Triệu lên nhà nước Nam Việt trong giai đoạn từ năm 204 TCN đến 111 TCN. Ông là người đã đánh bại An Dương Vương và sáp nhập Âu Lạc vào nhà nước Nam Việt. Chúng ta được biết đến Triệu Đà nhiều hơn qua truyền thuyết Trọng Thủy &#8211; Mỵ Châu. Triệu Đà có nguồn gốc là người Hán từ Trung Quốc. Ông được nhà Tần cử xuống cai trị phương Nam. Nhưng sau này nhà Tần suy yếu nên ông đã làm phản lại và tách ra cát cứ. Như vậy, từ những góc độ khác nhau, các nhà sử học đã có những tranh luận về sự chính thống của nhà Triệu trong các triều đại vua của Việt Nam. Những người nổi tiếng công nhận nhà Triệu như Hưng Đạo Vương, Nguyễn Trãi,&#8230; Một số nhà sử học khác đời Hậu Lê lại phủ nhận nó như Ngô Thì Sĩ, hay nhà thơ Tố Hữu cũng từng gọi là giặc.</p>
<h2>Triệu Đà &#8211; Triệu Vũ Đế</h2>
<p>Triệu Đà (257 TCN &#8211; 137 TCN) vốn là người nhà Hán. Quê ông ở Hằng Sơn (tỉnh Hà Bắc thuộc Trung Quốc hiện nay). Ông là một vị Tướng của nhà Tần. Ông được lệnh Tần Thủy Hoàng dẫn quân Nam tiến, chiếm đoạt các vùng đất của dân Bách Việt xưa. Sau khi Triệu Đà đánh bại các bộ tộc ở phía Nam, mà điển hình là Lạc Việt. Nhà Tần bị diệt vong. Nhân thấy triều đình bị sụp đổ, ông đã tách ra và xưng Đế, quy phục nhà Hán (Tuy là chư hầu nhưng trong nội bộ ông vẫn xưng là Hoàng Đế).</p>
<p>Ông làm vua xứ Nam Việt (bao gồm tỉnh Quảng Đông, Quảng Tây thuộc Trung Quốc và một số tỉnh miền Bắc Việt Nam ngày nay). Ông trị vị từ năm 207 TCN đến năm 137 TCN.</p>
<h3>Sự Nghiệp Của Triệu Vũ Đế</h3>
<p>Triệu Vũ Đế hay còn gọi là Triệu Đà từng là một võ tướng nhà Tần. Sau này nhà Tần diệt vong, ông tách ra xưng đế. Cuộc đời ông có nhiều sự kiện đáng để ta lưu ý.</p>
<h4><strong>Tần Thủy Hoàng giao trọng trách bình đình xuống Nam</strong></h4>
<p>Sau khi thống nhất 7 nước tranh hùng. Tạo nên một nhà nước Trung Quốc thống nhất vĩ đại. Tần Thủy Hoàng bắt tay bình định xuống phía Nam. Năm 218 TCN, Tần Thủy Hoàng cho Đồ Thư cùng 50 vạn quân tiến đánh vùng đất phía Nam. Sau khi chiếm được Lĩnh Nam, Đồ Thư tử trận. Sau đó, Tần Thủy Hoàng cho Nhâm Ngao cùng Triệu Đà đến cai trị vùng Lĩnh Nam.</p>
<p>Sau khi tới thủ phủ Long Xuyên nhậm chức, Triệu Đà áp dụng chính sách &#8220;hoà tập Bách Việt&#8221; đồng thời xin Tần Thủy Hoàng di dân 50 vạn người từ Trung Nguyên đến vùng này, tăng cường chính sách &#8220;Hoa Việt dung hợp&#8221; (hòa lẫn người Hoa Hạ và người Lĩnh Nam).</p>
<h4><strong>Chinh Phục Âu Lạc</strong></h4>
<p>Sử sách ghi lại rằng lần xâm phạm đầu tiên, Triệu Đà đóng quân ở núi Tiên Du (thuộc tỉnh Bắc Ninh ngày nay) giao chiến với An Dương Vương bị thất bại và bỏ chạy. Triệu Đà lập mưu gả con trai là Trọng Thủy cho con gái An Dương Vương là Mỵ Châu để do thám bí mật về bố phòng quân sự của Âu Lạc để tiếp tục tiến hành âm mưu xâm lược.</p>
<p>Trong truyền thuyết Trọng Thủy &#8211; Mỵ Châu thì có tính ướt lệ và hoành tráng hơn. Triệu Đà cho con ở rể để cướp đoạt nỏ thần mà thần Kim Quy ban. Sau đó tiến công và chiến thắng nhà nước Âu Lạc.</p>
<h4><strong>Tách khỏi nhà Tần</strong></h4>
<p>Sau khi nhà Tần bị tiêu diệt, Trung Nguyên rơi vào cảnh rối ren. Năm 208 TCN, Nhâm Ngao bị bệnh nặng, nhường quyền hạn lại cho Triệu Đà. Triệu Đà cho quân xuống Lĩnh Nam canh giữ quân Trung Nguyên kéo xuống. Sau đó cho quân tiêu diệt các quan quân nhà Tần chống lại mình.</p>
<h4>Quy phục nhà Hán</h4>
<p>Trải qua chiến tranh thắng lợi, Lưu Bang thu phục được nhà nước Tây Hán vào năm 202 TCN. Để bảo tồn lực lượng sau chiến tranh.</p>
<p>Năm 196 TCN, Hán Cao Tổ Lưu Bang sai quan đại phu Lục Giả đi sứ đến nước Nam Việt khuyên Triệu Đà quy phục nhà Hán.</p>
<p>Sách Việt Nam sử lược của Trần Trọng Kim chép:</p>
<p><strong><em>Vũ Vương vốn là người kiêu căng, có ý không muốn phục nhà Hán, đến khi Lục Giả sang đến nơi, vào yết kiến Vũ Vương, Vũ Vương ngồi xếp vành tròn, không đứng dậy tiếp. </em></strong></p>
<p><strong><em>Lục Giả thấy vậy mới nói rằng: &#8220;Nhà vua là người nước Tàu, mồ mả và thân thích ở cả châu Chân Định. Nay nhà Hán đã làm vua thiên hạ, sai sứ sang phong vương cho nhà vua, nếu nhà vua kháng cự sứ thần, không làm lễ thụ phong, Hán đế tất là tức giận, hủy hoại mồ mả và giết hại thân thích của nhà vua, rồi đem quân ra đánh thì nhà vua làm thế nào?&#8221; Vũ Vương nghe lời ấy vội vàng đứng dậy làm lễ tạ, rồi cười mà nói rằng: &#8220;Tiếc thay ta không được khởi nghiệp ở nước Tàu, chứ không thì ta cũng chẳng kém gì Hán Đế!&#8221;</em></strong></p>
<p>Triệu Đà chịu nhận ấn tước Nam Việt Vương, quy thuận nhà Hán trên danh nghĩa.</p>
<h4>Xưng Đế đối lập nhà Hán</h4>
<p>Sau khi Lã Hậu lên nắm quyền chuyên chính (Đối với văn hóa Trung Hoa, Lã hậu cùng Võ Tắc Thiên và Từ Hi thái hậu là những người phụ nữ chuyên chính nổi bật nhất lịch sử Trung Quốc).&nbsp;Lã Hậu ra lệnh cấm vận với nước Nam Việt. Triệu Đà thấy Lã Hậu có thể qua nước Trường Sa [15] mà thôn tính Nam Việt. Thế là Triệu Đà bèn tuyên bố độc lập hoàn toàn khỏi nhà Hán, tự xưng &#8220;Nam Việt Vũ Đế&#8221; và cất quân đánh nước Trường Sa, chiếm được mấy huyện biên giới của Trường Sa mới chịu thôi.</p>
<p>Lã Hậu bèn sai đại tướng Long Lư hầu là Chu Táo đi đánh Triệu Đà. Quân lính Trung Nguyên không quen khí hậu nóng nực và ẩm thấp miền nam, ùn ùn đổ bệnh, ngay dãy núi Ngũ Lĩnh cũng chưa đi qua nổi. Một năm sau, Lã Hậu chết, mưu đồ đánh Triệu Đà của quân nhà Hán bỏ hẳn.</p>
<p>Lúc đó Triệu Đà dựa vào tiếng tăm tài quân sự của mình lừng lẫy cả vùng Lĩnh Nam, lại nhờ tài hối lộ của cải, làm cả Mân Việt và phía Tây nước Âu Lạc cũ ùn ùn quy thuộc Nam Việt. Lúc ấy nước Nam Việt bành trướng đến mức cực thịnh. Triệu Đà bắt đầu lấy tên uy Hoàng Đế mà ra lệnh ra oai, thanh thế ngang ngửa đối lập với nhà Hán.</p>
<h4>Quy thuân nhà Hán một lần nữa</h4>
<p>Năm 179 TCN, vua Hán sai người tu sửa mồ mả cha ông Triệu Đà, cắt đặt hàng năm đúng ngày thờ cúng, ban thưởng chức vụ và của cải cho bà con Triệu Đà còn ở trong đất Hán. Nghe thừa tướng Trần Bình tiến cử, Lưu Hằng sai Lục Giả, người từng được Hán Cao Tổ sai sứ đi Nam Việt nhiều lần, làm chức Thái Trung Đại Phu, lại đi thuyết phục Triệu Đà quy Hán. Lục Giả đến Nam Việt, lại trổ tài thuyết phục Triệu Đà. Triệu Đà nghe thuyết phục phải trái hơn thiệt, quyết định bỏ danh hiệu Đế, quy phục nhà Hán (nhưng vẫn tiếm hiệu xưng Hoàng Đế ở trong nước Nam Việt).</p>
<p>Sau đó&nbsp;Triệu Đà chết đi, con cháu tiếp tục được 4 đời vua Nam Việt, cho đến năm 111 trước Công Nguyên mới bị nhà Hán chiếm.</p>
<p>Triệu Hưng lên ngôi thay Triệu Ddaf, tức Triệu Ai Vương. Mẹ là Cù thái hậu tham chính. Hán Vũ Đế sai sứ giả An Quốc Thiếu Quý, vốn là người tình cũ của Cù thái hậu, sang thuyết phục Nam Việt nội phụ nhà Hán. Cù thái hậu lại cùng Thiếu Quý tư thông và muốn thuận theo nhà Hán, nhưng Thừa tướng người Việt là Lữ Gia phản đối. Năm 112 TCN, Lữ Gia đem quân đánh vào cung, giết chết Cù thái hậu và Triệu Ai Vương cùng An Quốc Thiếu Quý, lập anh của Triệu Ai Vương là Triệu Kiến Đức lên ngôi, tức là Triệu Thuật Dương Vương.</p>
<p>Năm 111 TCN, Hán Vũ Đế sai Dương Bộc, Lộ Bác Đức đem đại quân sang đánh. Vua Triệu là Thuật Dương Vương Kiến Đức và Thừa tướng Lữ Gia lần lượt đều bị bắt và bị hại (111 TCN). Dựa trên hệ thống các đền, miếu, đình, chùa thờ Lữ Gia, phu nhân và các tướng lĩnh của ông rải rác trên khắp vùng đồng bằng sông Hồng ở miền Bắc Việt Nam, rất có thể cuộc kháng chiến chống nhà Tây Hán còn kéo dài đến năm 98 TCN. Sau khi Phiên Ngung thất thủ, Tây Vu Vương (thủ lĩnh đất tự trị Tây Vu với trung tâm là Cổ Loa đã nổi dậy chống lại nguy cơ Bắc thuộc lần 1 trước sự xâm lăng của nhà Tây Hán. Tả tướng Hoàng Đồng (黄同) của hai quận Giao Chỉ và Cửu Chân đã giết chết Tây Vu Vương đang làm loạn để hàng Hán. Triều đại nhà Triệu chính thức kết thúc.</p>
<h3>Những tranh luận về nhà Triệu và Triệu Đà</h3>
<p>Nhà Triệu là một triều đại, hay một giai đoạn lịch sử gây nhiều tranh luận cho giới nghiên cứu sử học Việt Nam. Sử học Việt Nam từ trước đến nay đều có hai quan điểm trái ngược nhau:</p>
<p>Triệu Vũ Đế đánh bại An Dương Vương, sáp nhập Âu Lạc vào Nam Việt là chuyện nội bộ nước Việt, nhà Triệu là triều đại chính thống của Việt Nam. Nhà Triệu mất là khởi đầu thời kỳ Bắc thuộc.</p>
<p>Triệu Đà là người phương Bắc, quê quán ở Trung Quốc (nay là tỉnh Hà Bắc, thuộc lưu vực sông Hoàng Hà ở Trung Quốc) theo lệnh Tần Thuỷ Hoàng đem di dân người Hoa Hạ (sau này gọi là người Hán) xuống vùng Lĩnh Nam, khi nhà Tần mất thì mới tách ra cát cứ, do đó Triệu Đà là kẻ ngoại bang đến xâm lược nước Âu Lạc. An Dương Vương mất nước là mở đầu thời kỳ Bắc thuộc.</p>
<p>Xoay quanh vấn đề Triệu Đà và nhà Triệu, mấu chốt là thế giới quan nhìn nhận của nhà sử học. Những người đề cao thuyết Thiên mệnh của Nho giáo (cho rằng ngôi vị là do &#8220;Trời định&#8221;, ai xưng đế ở vùng đất nào thì nghiễm nhiên được coi là vua, nắm giữ &#8220;Thiên Mệnh&#8221; của vùng đất đó, bất kể xuất thân thuộc dân tộc nào) thì sẽ nhìn nhận Triệu Đà là vua Việt Nam, đây là cách nhìn của nhiều sử gia Việt Nam thời phong kiến. Ngược lại, những nhà sử học có tư duy biện chứng về quốc gia &#8211; dân tộc, coi trọng nguồn gốc xuất thân, tính dân tộc của người cầm đầu chính quyền, bản chất của bộ máy quan lại nước Nam Việt (hầu hết quan lại Nam Việt là người Trung Hoa, còn người Việt là dân bị trị) và không công nhận thuyết &#8220;Thiên Mệnh&#8221; thì sẽ coi Triệu Đà là triều đại xâm chiếm của phương Bắc, đây là cách nhìn của các sử gia thời hiện đại.</p>
<p>Các tài liệu lịch sử của nhà Triệu thì cho thấy đến cuối đời, Triệu Đà đã quyết định bỏ việc xưng Đế, quy phục nhà Hán (nhưng vẫn xưng Hoàng Đế ở trong Nam Việt). Triệu Đà viết thư nhờ Lục Giả gửi cho vua Hán, trong thư Triệu Đà đã công nhận rằng mình là người Trung Hoa và nhà Triệu chỉ là chư hầu phục vụ cho nhà Hán, thay mặt vua Hán để cai trị phía Nam, bản thân ông ta cũng chỉ coi những thần dân người Việt là đám &#8220;Man Di&#8221; mà thôi chứ không coi họ ngang hàng với dân Trung Hoa.</p>
<h4>Ý kiến công nhận nhà nước Triệu Đà</h4>
<p>Từ khi giành lại quyền tự chủ, nhiều triều đại Việt đề cao vai trò lịch sử của Triệu Đà. Các bộ quốc sử Việt Nam soạn từ nhà Trần cho đến nhà Nguyễn đều chép nhà Triệu là một triều đại chính thống. Nhà Trần phong ông là Khai thiên Thế đạo Thánh vũ Thần triết Hoàng đế.</p>
<p>Bộ Đại Việt sử ký soạn bởi sử gia Lê Văn Hưu đời Trần.&nbsp;Ông so sánh Vũ Đế với các bậc vua hiền thời cổ như Thuấn, Văn Vương:<br />
Đất Liêu Đông không có Cơ Tử thì không thành phong tục mặc áo đội mũ, đất Ngô Cối không có Thái Bá thì không thể lên cái mạnh của bá vương. Đại Thuấn là người Đông Di nhưng là bậc vua giỏi trong Ngũ Đế. Văn Vương là người Tây Di mà là bậc vua hiền trong Tam Đại. Thế mới biết người giỏi trị nước không cứ đất rộng hay hẹp, người Hoa hay Di, chỉ xem ở đức mà thôi.</p>
<p>Triệu Vũ Đế khai thác đất Việt ta mà tự làm đế trong nước, đối ngang với nhà Hán, gửi thư xưng là &#8220;lão phu&#8221;, mở đầu cơ nghiệp đế vương cho nước Việt ta, công ấy có thể nói là to lắm vậy. Người làm vua nước Việt sau này nếu biết bắt chước Vũ Đế mà giữ vững bờ cõi, thiết lập việc quân quốc, giao thiệp với láng giềng phải đạo, giữ ngôi bằng nhân, thì gìn giữ bờ cõi được lâu dài, người phương Bắc không thể lại ngấp nghé được.</p>
<p>An Nam chí lược soạn bởi Lê Tắc đời Trần có viết: Triệu Đà làm vua Nam Việt, mới lấy thi lễ giáo hóa nhân dân một ít.</p>
<p>Điều này chứng tỏ Triệu Đà là người mang sự học đến Việt Nam từ trước chứ không phải Sĩ Nhiếp.</p>
<p>Bình Ngô đại cáo soạn bởi Nguyễn Trãi thay lời Bình Định Vương Lê Lợi sau khi bình xong quân Minh:</p>
<p>Tự Triệu, Đinh, Lý, Trần chi triệu tạo ngã quốc,<br />
Dữ Hán, Đường, Tống, Nguyên nhi các đế nhất phương.</p>
<p>Tức là:</p>
<p>Từ Triệu, Đinh, Lý, Trần bao đời gây nên độc lập,<br />
Cùng Hán, Đường, Tống, Nguyên mỗi bên xưng đế một phương.</p>
<p>Hai câu này khẳng định nước Việt không những độc lập với phương Bắc mà còn xưng đế hiệu cùng một thời (nhà Triệu với nhà Hán), tỏ ra hoàn toàn ngang hàng (Tuy nhiên cũng có quan điểm khác cho rằng &#8220;Triệu&#8221; ở đây là chỉ Triệu Quang Phục, vua của nước Vạn Xuân, tuy nhiên Triệu Quang Phục chỉ xưng Vương chứ chưa xưng đế nên không thể ngang hàng với nhà Hán được)</p>
<p>Bộ Đại Việt sử ký toàn thư soạn bởi Ngô Sĩ Liên, sử gia nhà Hậu Lê cũng dành cho Triệu Vũ Đế những lời tốt đẹp:</p>
<p>Truyện Trung Dung có câu: &#8220;Người có đức lớn thì ắt có ngôi, ắt có danh, ắt được sống lâu&#8221;. Vũ Đế làm gì mà được như thế? Cũng chỉ vì có đức mà thôi. Xem câu trả lời Lục Giả thì oai anh vũ kém gì Hán Cao. Đến khi nghe tin Văn Đế đặt thủ ấp trông coi phần mộ tổ tiên, tuế thời cúng tế, lại ban thưởng ưu hậu cho anh em, thì bấy giờ vua lại khuất phục nhà Hán, do đó tông miếu được cúng tế, con cháu được bảo tồn, thế chẳng phải là nhờ đức ư? Kinh Dịch nói: &#8220;Biết khiêm nhường thì ngôi tôn mà đức sáng, ngôi thấp mà không ai dám vượt qua&#8221;. Vua chính hợp câu ấy.</p>
<p>Quốc sử quán triều Nguyễn thời vua Tự Đức vẫn ghi danh các vua Triệu như là tiền triều.</p>
<p>Khâm Định Việt sử thông giám cương mục có ghi lời phê:</p>
<p>Xét chung từ trước đến sau, đất đai của nước Việt ta bị mất về Trung Quốc đã đến quá một nửa, tiếc rằng vua sáng tôi hiền các triều đại cũng nhiều người lỗi lạc hiếm có ở trên đời, mà vẫn không thể nào lấy lại được một tấc, đó là việc đáng ân hận lắm! Thế mới biết việc thu hồi đất đai đã mất, từ đời trước đã là việc khó, chứ không những ngày nay mà thôi. Thật đáng thương tiếc.</p>
<p>Việt Nam sử lược soạn bởi Trần Trọng Kim (1919) viết nhà Triệu là chính thống, thuộc một chương riêng, thuộc thời tự chủ không phải Bắc thuộc (Phần I: Thượng Cổ thời đại. Chương IV: Nhà Triệu)</p>
<h4>Ý kiến phủ nhận nhà nước Triệu Đà</h4>
<p>Các tài liệu lịch sử của nhà Triệu thì cho thấy đến cuối đời, Triệu Đà đã quyết định bỏ danh hiệu Đế, quy phục nhà Hán (nhưng vẫn xưng Hoàng Đế ở trong Nam Việt). Triệu Đà viết thư nhờ Lục Giả gửi cho vua Hán, trong thư ông viết:</p>
<p>“Man Di đại trưởng lão phu, thần Đà, mạo muội đáng chết, hai lạy dâng thư lên Hoàng đế bệ hạ. Lão phu vốn là lại cũ ở đất Việt, Cao Đế ban cho ấn thao làm Nam Việt Vương. Hiếu Huệ Hoàng Đế lên ngôi, vì nghĩa không nỡ tuyệt nên ban cho lão phu rất hậu. Cao Hậu lên coi việc nước lại phân biệt Hoa &#8211; Di, ra lệnh không cho Nam Việt những khí cụ làm ruộng bằng sắt và đồng; ngựa, trâu, dê nếu cho thì cũng chỉ cho con đực, không cho con cái. Lão phu ở đất hẻo lánh, ngựa, trâu, dê đã già&#8230; Lại nghe đồn rằng, phần mộ của cha mẹ lão phu bị đập phá, anh em họ hàng đều bị giết.</p>
<p>Vì vậy, bọn lại bàn nhau rằng: &#8220;Nay bên trong không được phấn chấn với nhà Hán, bên ngoài không lấy gì để tự cao khác với nước Ngô&#8221;. Vì vậy mới đổi xưng hiệu là Đế, để tự làm Đế nước mình, không dám làm điều gì hại đến thiên hạ. Cao Hoàng Hậu nghe tin cả giận, tước bỏ sổ sách của Nam Việt, khiến cho việc sai người đi sứ không thông&#8230; Lão phu ở đất Việt 49 năm, đến nay đã ẵm cháu rồi, những vẫn phải dậy sớm, ngủ muộn, nằm không yên chiếu, ăn không biết ngon, mắt không trông sắc đẹp, tai không nghe tiếng chuông trống, chỉ vì không được làm bề tôi nhà Hán mà thôi. Nay may được bệ hạ có lòng thương đến, được khôi phục hiệu cũ, cho thông sứ như trước, lão phu dù chết xương cũng không nát. Vậy xin đổi tước hiệu, không dám xưng Đế nữa.”</p>
<p>Như vậy, Triệu Đà đã nhận rằng mình chỉ là phiên vương phục vụ cho nhà Hán, thay mặt vua Hán để cai trị phía Nam, bản thân ông cũng chỉ coi những thần dân người Việt là đám &#8220;Man Di&#8221; mà thôi.</p>
<p>Sử gia Hồ Sĩ Dương nhà Hậu Lê khi soạn lại Lam Sơn thực lục (1679) đã viết lời bình:</p>
<p>Vũ đế nhà Triệu cùng vua Hán đều tự làm vua nước mình, gồm có đất ở ngoài Ngũ Lĩnh, đóng đô ở Phiên Ngung, thật là vua anh hùng. Thế nhưng chẳng qua cũng là một người Tàu sang cai trị nước ta, chưa được chính thống&#8230;<br />
Ngô Thì Sĩ, một thế kỷ sau, cuối đời Hậu Lê đã đánh giá vai trò của nhà Triệu trong Việt sử tiêu án, ông khẳng định nước Nam Việt là ngoại bang, Triệu Đà là kẻ ngoại tộc:</p>
<p>An Dương Vương mất nước, để quốc thống về họ Triệu, chép to 4 chữ: &#8220;Kỷ Triệu Vũ Đế&#8221;. Người đời theo sau đó không biết là việc không phải. Than ôi! Đất Việt Nam Hải, Quế Lâm không phải là đất Việt Giao Chỉ, Cửu Chân, Nhật Nam. Triệu Đà khởi phát ở Long Xuyên, lập quốc ở Phiên Ngung, muốn cắt đứt bờ cõi, gồm cả nước ta vào làm thuộc quận, đặt ra giám chủ để cơ mi lấy dân, chứ chưa từng đến ở nước ta.</p>
<p>Nếu coi là đã làm vua nước Việt, mà đến ở cai trị nước ta, thì sau đó có Lâm Sĩ Hoằng khởi ở đất Bàn Dương, Lưu Nghiễm khởi ở Quảng Châu, đều xưng là Nam Việt Vương, cũng cho theo Quốc kỷ được ư? Triệu Đà kiêm tính Giao Châu, cũng như Ngụy kiêm tính nước Thục, nếu sử nước Thục có thể đưa Ngụy tiếp theo Lưu Thiện, thì quốc sử ta cũng có thể đưa Triệu tiếp theo An Dương. Không thế, thì xin theo lệ ngoại thuộc để phân biệt với nội thuộc vậy.</p>
<p>Ngô Thì Sĩ kết luận: Nước ta bị nội thuộc vào nước Tàu từ đời Hán đến Đường, truy nguyên thủ họa chả Triệu Đà thì còn ai nữa? Huống chi Triệu Đà chia nước ta làm quận huyện, duy chỉ biết biên số thổ địa, thu thuế má, cung cấp ngọc bích cho nhà Hán, đầy túi tham của Lục Giả thôi. Đến như việc xướng ra cơ nghiệp đế vương trước tiên, tán tụng Triệu Đà có công to, Lê Văn Hưu sáng lập ra sử chép như thế, Ngô Sĩ Liên theo cách chép hẹp hòi ấy, không biết thay đổi, đến như bài Tổng luận sử của Lê Tung, thơ vịnh sử của Đặng Minh Khiêm thay nhau mà tán tụng, cho Triệu Đà là bậc thánh đế của nước ta. Qua hàng nghìn năm mà không ai cải chính lại vì thế mà tôi phải biện bạch kỹ càng.</p>
<p>Trong một bài viết trên báo Sông Hương năm 1936, Pham Quỳnh phản đối các sử gia phong kiến đã coi Triệu Đà là vua của Việt Nam. Theo ông, &#8220;quốc sử phải lấy dân tộc làm nền&#8221;, Triệu Đà là người Hán nên không thể coi là vua nước Việt, và &#8220;sử gia phong kiến tôn y (Triệu Đà) là ông vua khai quốc, ấy là đã làm một việc vô nghĩa&#8230;&#8221;.</p>
<p>Học giả Đào Duy Anh, trong cuốn Lịch sử cổ đại Việt Nam(1957) cho rằng:</p>
<p>Nhà Triệu không phải là quốc triều, Triệu Đà chỉ là một tên giặc cướp nước, quan niệm của Lê Văn Hưu là quan niệm lịch sử phản dân tộc!</p>
<p>Giáo trình lịch sử văn học Việt Nam, tập I: Văn học dân gian (1961, PGS. Đỗ Bình Trị):</p>
<p>Thất bại của An Dương Vương do không đề phòng kẻ địch – thậm chí còn tin vào kẻ địch nham hiểm – là mặt thứ hai của bài học giữ nước.</p>
<p>Văn học dân gian Việt Nam (1962), GS.Đinh Gia Khánh viết:</p>
<p>Thần Nông lúc đầu vốn có trong thần thoại của Miêu tộc, dân tộc Hán sau này đã nhập vị thần này vào sổ bạ nhà thần Hán tộc; mặt khác, ông đánh giá Triệu Đà là kẻ ngoại xâm, kẻ gây ra tấn bi kịch nước mất, nhà tan cho cha con An Dương Vương.</p>
<p>Lịch sử Việt Nam, tập 1 (1971,công trình tập thể không ghi tên các tác giả), được biên soạn dưới sự chỉ đạo trực tiếp của Ủy ban Khoa học xã hội Việt Nam được xuất bản. Cuốn sách đã viết về Triệu Đà với cái nhìn thiếu thiện cảm:</p>
<p>Triệu Đà biết rằng không thể thắng được Âu Lạc về quân sự nên rút về núi Vũ Ninh, xin hòa với An Dương Vương. Hắn sai con trai là Trọng Thủy sang hàng phục An Dương Vương, xưng thần mà thờ. An Dương Vương gả con gái là Mị Châu cho Trọng Thủy. Trọng Thủy ở gửi rể bên nước Âu Lạc. Đấy chính là mưu mẹo mà Triệu Đà dùng để chiếm nước Âu Lạc.</p>
<p>Trong những năm ở gửi rể, Trọng Thủy đã dò xét tình hình Âu Lạc, học phép chế nỏ và phá nỏ của người Âu Lạc rồi trốn về nước báo cho Triệu Đà. Kết hợp lực lượng quân sự và mưu mẹo gián điệp, lần này Triệu Đà thôn tính được nước Âu Lạc. An Dương Vương thua trận, phải nhảy xuống biển tự vẫn. Việc đó xảy ra vào khoảng năm 179 trước Công nguyên.</p>
<p>Tìm hiểu tiến trình văn học dân gian Việt Nam (1974), nhà nghiên cứu Cao Huy Đỉnh nhận xét:</p>
<p>&#8230;Nếu dân tộc Âu Lạc đã thống nhất từ bên dưới thì xã hội Âu Lạc lại bắt đầu chia rẽ từ bên trên. Quyền lợi vật chất đã tập trung vào một dòng họ quý tộc. Dòng họ này sống bằng mồ hôi nước mắt và máu của nô tì lao dịch, co rúm vào trong nội thành, đã mất cảnh giác với kẻ thù lại không tin vào nhân dân, thậm chí nghe lời gièm pha của bọn gian thần mà hại cả kiệt tướng trung thần. Sự đối lập giai cấp và lẫn lộn bạn thù này tất phải mở đường cho cuộc xâm lược của cha con họ Triệu nòi Hán và kết thúc bằng số phận bi thảm của cha con vua Chủ (An Dương Vương và Mị Châu). Trong lúc đó thì quần chúng vẫn không nguôi hận thù đối với bọn cướp nước.</p>
<p>Văn học dân gian Việt Nam (1990, do GS. Lê Chí Quế chủ biên) và trong Văn học dân gian Việt Nam, tập 2 (của PGS. Hoàng Tiến Tựu), các tác giả đều xếp Triệu Đà vào hàng ngũ bọn xâm lược.</p>
<p>Phan Huy Lê, giáo sư lịch sử, trong lời giới thiệu cuốn Đại Việt Sử Ký Toàn Thư (2000) cho rằng:</p>
<p>Việc Lê Văn Hưu, Ngô Sĩ Liên coi nhà Triệu là một vương triều chính thống của Việt Nam là một sai lầm nghiêm trọng. Ông khẳng định Nam Việt là một nước cát cứ của một tập đoàn phong kiến, không phải là nước của người Việt Nam. Ông cho rằng việc Triệu Đà đặt tên nước là Nam Việt (tỏ ý muốn phục hưng nước cũ của người Việt) cũng như việc Triệu Đà tự xưng là &#8221; Man Di đại trưởng lão phu&#8221;, lấy vợ Việt, theo tục Việt&#8230;chỉ là các thủ đoạn mị dân Việt. Việc Triệu Đà chống Tần chống Hán cũng chỉ nhằm thỏa mãn mộng bá vương của riêng mình&#8230;</p>
<p>Nhưng nhiều sử gia phong kiến đã không nhận ra bộ mặt cát cứ, xâm lược của nhà Triệu và ngộ nhận coi nhà Triệu là một triều đại của Việt Nam.</p>
<p>Tố Hữu làm thơ gọi họ Triệu là &#8220;giặc&#8221;, phê phán Mỵ Châu làm mất nước:</p>
<p>Tôi kể ngày xưa chuyện Mỵ Châu,<br />
Trái tim lầm chỗ để trên đầu.<br />
Nỏ thần vô ý trao tay giặc,<br />
Nên nỗi cơ đồ đắm bể sâu.</p>
<p>Quan điểm phủ nhận Triệu Đà hiện là quan điểm chính thống của giới sử học Việt Nam, được phản ảnh trong các bộ thông sử quốc gia, được đưa vào chương trình giáo dục phổ thông và đại học.</p>
<h4><strong>Quan điểm nhìn nhận</strong></h4>
<p><strong>Vấn đề nguồn gốc của dòng vua</strong></p>
<p>Xoay quanh vấn đề Triệu Đà và nhà Triệu, mấu chốt là do quan điểm nhìn nhận. Các sử gia không có xu hướng coi nặng việc tìm nguồn gốc Triệu Đà và bản chất dân nước Nam Việt sẽ nhìn nhận Triệu Đà là vua Việt Nam. Ngược lại những người coi trọng nguồn gốc xuất thân, dân tộc của người cầm đầu chính quyền, và bản chất dân nước Nam Việt thì sẽ có nhìn nhận khác.</p>
<p>Triệu Đà là người phương Bắc (đến từ phía Bắc sông Hoàng Hà, ngày nay là miền Bắc Trung Quốc), vốn là tướng nhà Tần, quê ở Chân Định (tỉnh Hà Bắc, Trung Quốc ngày nay), mộ cha mẹ vẫn táng ở đấy.</p>
<p><strong>Bên công nhận nhà Triệu cho rằng:</strong></p>
<p>Nếu đặt ra vấn đề nguồn gốc của Triệu Đà, thì chính nguồn gốc của An Dương vương, gần đây cũng được nhiều nhà nghiên cứu nêu ra, sẽ không khác gì Triệu Đà. Theo một số công trình nghiên cứu gần đây (Lịch sử Việt Nam tập 1, Theo dòng lịch sử &#8211; nhiều tác giả) thì Thục Phán vốn gốc là dòng dõi người nước Thục ở Tứ Xuyên (Trung Quốc) và sang xâm lược nước Văn Lang, tiêu diệt Hùng Vương[cần dẫn nguồn]. Nếu vậy, An Dương vương liệu còn là một triều đại Việt Nam không? Đi xa hơn nữa, nếu truy về nguồn cội tổ tiên, thì còn những trường hợp khác mà sử đã ghi, như Lý Nam đế (Lý Bí) có tổ 7 đời là người phương Bắc (Trung Hoa) vào Việt Nam, hoặc tổ tiên 5 đời của nhà Trần cũng vốn xuất thân từ đất Mân (Phúc Kiến &#8211; Trung Quốc) sang; tổ tiên của Hồ Quý Ly là Hồ Hưng Dật sang Việt Nam thời Dương Tam Kha (sử chép là thời Hậu Hán 947 &#8211; 950, tương đương Dương Bình vương) được phong chức ở châu Hoan&#8230;</p>
<p>Một số nhà nghiên cứu cho rằng, trên thế giới, việc một người nước ngoài làm vua không phải là không có. Chẳng hạn nước Nga vẫn ghi nhận vợ của Pyotr Đại đế là Ekaterina I, dù không phải là người Nga, nhưng được chồng cho thừa kế ngôi, là nữ hoàng như các nữ hoàng khác.</p>
<p>Tuy nhiên, những người phản bác cho rằng trường hợp nữ hoàng Ekaterina I của Nga cũng không thể so với Triệu Đà: một đàng chỉ một người ngoại quốc đã &#8220;nhập gia&#8221; quê chồng, còn triều đình, quân đội, ngôn ngữ vẫn là bản địa, đằng kia toàn bộ triều đình, quân đội, ngôn ngữ là dị biệt. Đặt giả định nếu nhà Tần không mất thì Triệu Đà sẽ không tách ra cát cứ, và cũng sẽ chẳng có nước Nam Việt mà đó chỉ là một quận của Trung Hoa mà thôi. Vai trò của Triệu Đà khi ấy sẽ chẳng khác gì những viên quan Thái thú triều đình phía Bắc khác đã cai trị Việt Nam suốt thời Bắc thuộc.</p>
<p>Theo tác giả Hà Văn Thùy, cuối thế kỷ 18, vua nước Xiêm là một người Trung Quốc tên Trịnh Quốc Anh từng kéo quân sang đánh Hà Tiên. Trong khi đó, Triệu Đà có vợ Trình Thị là người Đường Thâm, Giao Chỉ, nên các con cháu ông &#8211; các đời vua sau của nhà Triệu &#8211; đều có phần máu Việt. Cũng theo ông Hà Văn Thùy thì &#8220;đúng Triệu Đà là người Hán nhưng đất Nam Việt lúc đó hầu hết là người Việt, vì vậy không thể phủ nhận việc ông là vị vua đầu tiên của nước Nam Việt, ông vua khai sáng của Việt Nam chúng ta&#8221;.</p>
<p><strong>Vấn đề &#8220;xâm lược&#8221; hay &#8220;thống nhất&#8221;</strong></p>
<p>Những người phản đối tính chính thống của nhà Triệu, trong đó có Ngô Thì Sĩ, lập luận rằng Triệu Đà khởi phát ở bên ngoài lãnh thổ nước Việt, chiếm nước Việt làm quận huyện. Nước Nam Việt của Triệu Đà không phải nước Việt với ba vùng Giao Chỉ, Cửu Chân, Nhật Nam mà trong sử sách Việt Nam vẫn coi là lãnh thổ của mình. Do đó, nếu coi Triệu Đà là một vua Việt Nam thì giả thuyết này coi nước Việt Nam lúc ấy bao gồm cả các tỉnh Quảng Đông, Quảng Tây, một phần của tỉnh Hồ Nam, Vân Nam, và Phúc Kiến của Trung Quốc bây giờ. Nếu không thì phải cho đây là một sự xâm lược.</p>
<p>Một số học giả lại không cho việc Triệu Đà sáp nhập vùng đất của Âu Lạc vào Nam Việt là xâm lược. Tác giả Hà Văn Thùy lập luận rằng &#8220;sự liên kết trong mỗi quốc gia còn lỏng lẻo và biên giới từng quốc gia chưa ổn định, đang trong xu hướng sáp nhập tập trung thành những quốc gia đủ mạnh để tồn tại. Do đó, việc thôn tính các nước Sở, Ngô, Việt&#8230; để thành nước Tần không phải hành động xâm lược mà là công lớn thống nhất đất nước. Tương tự vậy, việc Triệu Đà chiếm Âu Lạc cũng không thể coi là cuộc xâm lược mà là hành động thống nhất những nhóm, những tiểu quốc người Việt lại thành môt nước Việt lớn hơn, ngăn chặn hành động thôn tính của kẻ mạnh ở phương Bắc.&#8221; Học giả này đánh giá cao vai trò của nhà Triệu trong việc &#8220;tạo nên và củng cố tinh thần quốc gia của người Việt&#8221;, và cho rằng đó là &#8220;di sản quý báu nhất họ Triệu để lại cho người Việt&#8221;.</p>
<p>Theo một nghiên cứu của tác giả E Lusuo người Đài Loan về quá trình nhà Tần bình định vùng Nam Việt, vào thời nhà Tần, dân cư bên này hay bên kia biên giới Việt-Trung hiện đại là không thể phân biệt được. Một sự kiện lịch sử ủng hộ thuyết này đó là: cuộc khởi nghĩa của Hai Bà Trưng cũng nhận được sự ủng hộ và tham gia của cư dân tại các quận Nam Hải, Hợp Phố mà nay thuộc địa phận Trung Quốc đã chiếm được 65 thành trì (Theo sách Hậu Hán Thư, chương 68: &#8220;Lịch sử về tộc Man Di phía Nam và Tây Nam&#8221; (Biographies of the Southern and the Southwestern Barbarians)); các học giả Trung Quốc gọi họ là người Lạc Việt, họ được cho là sử dụng cùng một ngôn ngữ.</p>
<p><strong>Vấn đề chấp nhận triều đại ngoại tộc</strong></p>
<p>Có người cho rằng quan điểm của các sử gia Việt Nam và Trung Quốc, một nước phong kiến khác tại châu Á, có sự khác nhau. Ở Trung Quốc, có nhiều triều đại, điển hình là Bắc Ngụy thời Nam Bắc triều, nhà Nguyên, nhà Thanh đều xuất thân ngoại tộc, không phải người Hán, nhưng sử sách vẫn chép như những triều đại khác của Trung Quốc, không coi là thời kỳ bị nội thuộc Hung Nô hay Mông Cổ. Những triều đại này sử dụng tiếng Hán, nghi lễ tập tục trong triều đã Hán hóa khá nhiều. Thậm chí người Mãn đã Hán hóa đến mức ngày nay chỉ còn một số rất ít người già còn biết tiếng Mãn, còn lớp trẻ chỉ biết tiếng Hán, một phần người Mông Cổ hay người Mãn ngày nay là 2 trong số 56 dân tộc của Trung Quốc, tức là lịch sử của họ cũng có thể coi là một phần lịch sử quốc gia. Ngoài ra, đất đai của các triều đại này phần lớn là lãnh thổ Trung Quốc ngày nay.</p>
<p>Theo học giả Lê Thành Khôi thì mặc dù gốc Trung Hoa, Triệu Đà đã chịu đồng hóa với dân Nam Việt, mà ông chấp nhận các phong tục tập quán đến độ gần như quên cả quá khứ của mình</p>
<h3>Vai trò của Nhà Triệu trong lịch sử Việt Nam</h3>
<p>PGS-TS Trương Sỹ Hùng đánh giá, Nhà Triệu nổi bật nhất trong khía cạnh bảo vệ độc lập, tự chủ của nước Nam Việt trước cường quốc phương Bắc là nhà Hán &#8211; khi đó mới thành lập sau khi Hán &#8211; Sở tranh hùng.</p>
<p>&#8220;Bên cạnh đó, ông (Triệu Đà) trả lời một câu rất hay là: Nhưng mà tôi vẫn đặt quan hệ đi lại, bang giao &#8211; tức là để quan hệ bang giao thuận lợi hơn, mà không để giãn cách. Tôi cho rằng, bài học đấy không những bây giờ, mà mãi mãi về sau này, bởi vì cái sự tồn tại, độc lập dân tộc của mỗi quốc gia là riêng. Còn vấn đề lúc va chạm nhau là chuyện giải quyết thắng thua, rành mạch, sòng phẳng, sau đó chúng ta lại phải giữ quan hệ với nhau hữu hảo, lâu dài.&#8221;</p>
<p>Nhà giáo Vũ Thế Khôi phân tích kỹ hơn, Nhà Triệu đã lập ra một quốc gia tự chủ cho người Việt, bằng cách tập hợp, thống nhất được sự đoàn kết của các sắc tộc cùng sinh sống trong lãnh thổ Nam Việt mà được gọi là &#8220;Hòa tập Bách Việt&#8221;. Nhà Triệu cũng khôn khéo trong chính sách &#8220;Trong Đế &#8211; Ngoài Vương&#8221; và cương quyết bảo vệ nền độc lập trước nhà Hán khi bị xâm chiếm.</p>
<p><i>&#8220;Để tồn tại được thì rất mềm mỏng, nhưng khi cần bảo vệ quốc gia thì cương quyết, không hèn nhát. Và chính vì thế, vương triều nhà Triệu cho đến bây giờ vẫn sống trong tâm thức người Việt. Rất nhiều nơi trên đất Việt Nam, theo thống kê của Trung tâm Minh Triết là hơn 30 nơi thờ Triệu Vũ Đế.&#8221;</i></p>
<p>Bên cạnh đó, Nhà giáo Vũ Thế Khôi cho rằng, để tạo ra sự thống nhất, Triệu Vũ Đế đã đưa chữ Hán vào đời sống chính trị, xã hội Nam Việt khi đó, chứ không phải do quân đội nhà Tần mang đến.</p>
<p><i>&#8220;Trong khi chữ Việt cổ bị mai một từ lúc nào đấy do hoàn cảnh lịch sử. Mà bây giờ các học giả đã chứng minh là nó có, mà chính người Trung Hoa xây dựng chữ tượng hình của họ trên cơ sở chữ Việt cổ đó. Nhưng lúc bấy giờ chữ Việt cổ không còn được sử dụng rộng rãi nữa, thì ông ấy sử dụng luôn chữ Hán, để làm công cụ truyển tải trong chính quyền của ông ấy.&#8221;</i></p>
<p>Lịch sử Việt Nam thời kỳ dựng nước và bảo vệ nền độc lập từ ngày đầu còn nhiều điều mà hậu thế chưa rõ, và cả dân tộc này vẫn đang đi tìm hiểu lấp đầy những khoảng trống, giải quyết những khúc mắc.</p>
<p>PGS-TS Trương Sỹ Hùng cho biết, thời gian tới đây, các học giả, nhà nghiên cứu Việt Nam sẽ tiếp tục khảo sát những di chỉ khảo cổ, tìm kiếm tài liệu, thư tịch cổ về Nhà Triệu không chỉ tại miền Bắc Việt Nam, mà còn cả ở Quảng Đông, Quảng Tây &#8211; những vùng đất của người Bách Việt xưa, trong lãnh thổ Nam Việt thời Triệu Đà.</p>
<h3>Đền thờ Triệu Đà</h3>
<p>Tượng thờ Triệu Vũ Đế (tức Triệu Đà) đặt tại đền Đồng Xâm, xã Hồng Thái, huyện Kiến Xương, tỉnh Thái Bình.</p>
<p>Nhiều nơi ở miền Bắc Việt Nam và miền Nam Trung Quốc có đền miếu thờ cúng ông. Đình thờ Thành hoàng Triệu Đà ở xã Xuân Quan, huyện Văn Giang, tỉnh Hưng Yên, Việt Nam. Xưa kia đây là nơi Triệu Đà cho xây dựng điện Long Hưng. Đình thờ cha mẹ và đền thờ của Triệu Đà ở xã Quang Minh, huyện Thanh Oai, TP Hà Nội. Đền Đồng Xâm ở xã Hồng Thái, huyện Kiến Xương, tỉnh Thái Bình, Việt Nam thờ Triệu Đà và phu nhân Trình thi.Nhiều nơi xung quanh khu vực Cổ Loa (huyện Đông Anh, Hà Nội) như các làng Văn Tinh, Lực Canh (thuộc xã Xuân Canh), Thạc Quả (thuộc xã Dục Tú) thờ Triệu Đà.</p>
<p>Truyền thuyết dân gian vùng ven thành Cổ Loa kể lại khi đi đánh An Dương Vương. Triệu Đà đã cho thuyền ngược sông Hồng và cho đóng quân ở bến sông, nay là đoạn cuối làng Dâu (hay có tên khác là làng Lực Canh) và đầu làng Văn Tinh, nơi rất gần với ngã ba Dâu (nơi hợp lưu của sông Đuống và sông Hồng).</p>
<p>Tương truyền, làng Văn Tinh là nơi Triệu Đà đóng đại bản doanh còn dân làng Lực Canh chỉ làm nhiệm vụ như cắt cỏ ngựa, khuân vác, phục vụ cho quân đội. Vì thế, đình Văn Tinh được coi là nơi thờ chính còn các nơi khác chỉ là nơi thờ vọng. Lễ hội làng Văn Tinh được tổ chức từ ngày mùng 6 đến mùng 8 tháng 3 hàng năm để tưởng nhớ Triệu Đà. Ngày 7 tháng 3, nhân dân làng Lực Canh rước tượng Trọng Thủy đến Văn Tinh với ý nghĩa con về thăm cha.</p>
<p>Miếu Nam Việt Vương ở thị trấn Đà Thành, huyện Long Xuyên, địa cấp thị Hà Nguyên, tỉnh Quảng Đông, Trung Quốc thờ Thành hoàng Triệu Đà. Miếu được xây dựng từ thời nhà Thanh.</p>
<p>Quyển thơ sử với đầu đề &#8220;Lịch sử nước ta&#8221; do Hồ Chí Minh viết tay (do Việt Minh Tuyên truyền Bộ xuất bản năm 1942) cũng đã có đoạn viết:</p>
<p>Triệu Đà là vị hiền quân<br />
Quốc danh Nam Việt trị dân năm đời.</p>
<p>Quan điểm chính thống hiện nay của Việt Nam coi nhà Triệu là triều đại của ngoại bang, thời kỳ Bắc thuộc (bị Trung Hoa đô hộ) được tính từ thời nhà Triệu, nhưng lại có ngoại lệ là cuốn Niên biểu Việt Nam, tiếp theo nhà Thục, kê rõ nhà Triệu với đầy đủ các đời vua, tiếp theo là đến &#8220;Thời kỳ đấu tranh chống phong kiến Trung Hoa thống trị lần thứ nhất&#8221; tính từ năm 111 TCN.</p>
<p>Trong bảng tra cứu niên hiệu các đời vua Việt Nam cũng liệt kê niên hiệu Kiến Đức của Thuật Dương Vương, vua cuối cùng nhà Triệu (thật ra Kiến Đức là tên húy của ông vua này). Ngoại lệ này có lẽ do sách niên biểu cốt để phục vụ việc tra cứu, trong khi nhiều sử sách xưa của Việt Nam coi nhà Triệu là một triều đại Việt Nam.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
', 'Triệu Đà là người khởi đầu cho sự cai trị của dòng họ Triệu lên nhà nước Nam Việt trong giai đoạn từ năm 204 TCN đến 111 TCN. Ông là người đã đánh bại An Dương Vương và sáp nhập Âu Lạc vào nhà nước Nam Việt. Chúng ta được biết đến Triệu Đà [&hellip;]', 1026, 'post', '2018-06-26 10:18:22', '2023-04-23 12:33:54');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1025, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1025, 64);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1016, 'Nhà trẻ Thiên Ân Cần Thơ &#8211; Chuyến đi từ thiện ý nghĩa của tôi', 'chuyen-tu-thien-nha-tre-thien-an', '<p><strong>Nhà trẻ Thiên Ân</strong> hay còn gọi cái tên thân thương khác là Mái ấm Thiên Ân. Đúng như cái tên mái ấm của mình. Nơi đây là nơi nuôi dưỡng ấm áp cho các trẻ mồ côi hoặc những đứa bé có gia đình khó khăn không nuôi nổi. Nơi đây đã mang lại cho các em có hoàn cảnh bất hạnh một mái ấm gia đình. Không những vậy, nơi đây còn nuôi dạy cho các em đến trường và xin việc làm. Tôi đã có dịp đến thăm mái ấm Thiên Ân một vài lần. Những chuyến đi đều mang hương vị thân thương với những đứa bé ở đây. Mỗi lần đến cách vài tháng hay có khi cả năm. Những đứa bé dần trở nên lớn hơn. Đôi khi những đứa bé mình từng dỗ dành khóc nhè nay đã lớn. Nhưng nụ cười của chúng ở trên môi luôn làm tôi cảm động.</p>
<h2>Nhà Trẻ Thiên Ân</h2>
<p>Địa chỉ: 601/22 KV Bình Trung, P.Long Hòa, Q. Bình Thủy, TP. Cần Thơ.</p>
<p>Số điện thoại:&nbsp;0292888542</p>
<p><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3928.6337853049245!2d105.73561171428231!3d10.047047774980342!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31a0887d1f13574d%3A0x64a61ace4ec9e78!2sThien+An+Orphanage!5e0!3m2!1svi!2s!4v1540479889639" width="600" height="450" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h3>Nhà của những đứa trẻ đáng thương</h3>
<p>Nhà trẻ Thiên Ân ở Cần Thơ được thành lập vào năm 2004. Đây là nơi chăm sóc các bé nhỏ, thanh thiếu niên có hoàn cảnh khó khăn. Những đứa trẻ bị bỏ rơi khi vừa sinh ra hay những gia đình nghèo khó không đủ khả năng nuôi con của mình. Những đứa bé ở đây thường dao động từ 30-50 bé từ 3 đến 18 tuổi. Ở đây đủ mọi vùng miền khác nhau, bạn sẽ bắt gặp những đứa bé bập bẹ những tiếng dân tộc khác. Chúng có thể là người Chăm, Khmer hay Kinh. Tất cả đều có một thân thế đau buồn.</p>
<p><figure id="attachment_1020" aria-describedby="caption-attachment-1020" style="width: 600px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1020" src="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho4.jpg" alt="Nhà Trẻ Thiên Ân Cần Thơ" width="600" height="398" srcset="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho4.jpg 960w, https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho4-768x510.jpg 768w" sizes="(max-width: 600px) 100vw, 600px" /><figcaption id="caption-attachment-1020" class="wp-caption-text">Nhà Trẻ Thiên Ân Cần Thơ</figcaption></figure></p>
<p>Nơi đây thỉnh thoảng vẫn tổ chức những buổi dạy thêm cho các bé từ anh văn đến tin học. Nhưng đa phần đều do tình nguyện viên là sinh viên, một số người hảo tâm hay người nước ngoại dạy miễn phí. Nên đôi khi các khóa học thường không được nối liền mạch. Hy vọng nơi đây sẽ có những tình nguyện viên gắn bó lâu dài hơn.</p>
<h3>Chuyến đi thăm của tôi đến mái ấm Thiên Ân</h3>
<p><figure id="attachment_1018" aria-describedby="caption-attachment-1018" style="width: 600px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1018" src="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho2.jpg" alt="Nhà Trẻ Thiên Ân Cần Thơ" width="600" height="450" srcset="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho2.jpg 800w, https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho2-768x576.jpg 768w" sizes="(max-width: 600px) 100vw, 600px" /><figcaption id="caption-attachment-1018" class="wp-caption-text">Nhà Trẻ Thiên Ân Cần Thơ</figcaption></figure></p>
<p>Ngay từ ban đầu khi có người hỏi tôi muốn thăm một nhà trẻ mồ côi không? Tôi đã nhận lời ngay lập tức. Những đứa trẻ khi sinh ra đều là những thiên thần. Và tôi sẽ không bỏ lỡ chuyến thăm đến nơi mà các thiên thần cần tôi. Tôi hỏi người bạn khác tại sao muốn đến đó vậy? Không phải nó hơi xa trung tâm thành phố Cần Thơ? &#8220;Chúng ta cần đem lại điều tốt đẹp nhất cho người cần chúng ta nhất! Mà 10km từ trung tâm thành phố thì quá ngắn!&#8221;.</p>
<p>Khi ấy chúng tôi dùng xe máy chạy vào trong con hẻm dưới một cây cầu. Chạy một con đường làng không lớn nhưng trải xi măng kéo dài. Lúc ấy, cầu bắc ngang Nhà trẻ Thiên Ân vẫn còn độc mộc như một cây cầu khỉ cỡ to vậy. Tay láy của tôi khá cứng nên cứ băng băng đi qua. Những bạn nữ chạy phía sau cứ la hét thất thanh. Còn bây giờ, đường vào Nhà trẻ đã được xây dựng lại khá ổn. Những nhà hảo tâm và chính quyền nơi đây đã tạo điều kiện tốt hơn cho mái ấm và người dân của phường.</p>
<p><figure id="attachment_1021" aria-describedby="caption-attachment-1021" style="width: 960px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1021" src="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho3.jpg" alt="Nhà Trẻ Thiên Ân Cần Thơ" width="960" height="637" srcset="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho3.jpg 960w, https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho3-768x510.jpg 768w" sizes="(max-width: 960px) 100vw, 960px" /><figcaption id="caption-attachment-1021" class="wp-caption-text">Nhà Trẻ Thiên Ân Cần Thơ</figcaption></figure></p>
<h3>Sự khởi đầu ở nhà trẻ Cần Thơ</h3>
<p>Đứng trước cổng nhỏ của ngôi nhà. Sân vườn nơi đây khá thoáng mát, có một số dụng cụ trò chơi được quyên tặng để lác đác trong sân. Tôi dừng xe lại và cùng đoàn đem quà vào nhưng cổng đã khóa lại. Một bé gái dễ thương chạy ra lễ phép hỏi:</p>
<p>&#8211; Mấy anh tìm ai ạ?</p>
<p>Tôi mỉm cười thân thiện. Sách vở vẫn hay nói 5 giây đầu tiên khi tiếp xúc rất là quan trọng. Tôi nói từ tốn:</p>
<p>&#8211; Tụi anh hôm trước có gọi cho cô. Anh đến để đem quà tặng cho mấy đứa nè. Em vào hỏi cô rồi mở cửa cho tụi anh vào với!</p>
<p>Sau khi thông báo cho cô phụ trách, đứa bé chạy ra mở cửa và khoanh tay chào tôi lễ phép. Cô phụ trách rất thân thiện, giới thiệu cho chúng tôi về Nhà trẻ Thiên Ân. Chúng tôi nhanh chóng chia người ra, chuẩn bị kế hoạch đầy đủ. Một nhóm thì chuẩn bị các quà tặng và chương trình phía sau. Một nhóm thì cùng chơi với mấy đứa trẻ.</p>
<p><figure id="attachment_1017" aria-describedby="caption-attachment-1017" style="width: 370px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1017 size-medium" src="https://media.huynhhieutravel.com/nha-tre-thien-an-can-tho-370x260.jpg" alt="Nhà Trẻ Thiên Ân Cần Thơ" width="370" height="260"><figcaption id="caption-attachment-1017" class="wp-caption-text">Nhà Trẻ Thiên Ân Cần Thơ</figcaption></figure></p>
<p>Tôi cứ mải miết chơi với mấy đứa trẻ vì chúng quá dễ thương và ngoan. Chúng rất thích bu lấy người lớn và chơi đủ trò nhưng lại rất nghe lời. Sự ngây thơ và hồn nhiền của chúng đã cải tạo tâm hồn tưởng chừng già nua của tôi. Sau khi chúng tôi chơi đủ mệt với những đứa bé. Chương trình tiếp tục với những phần quà trao tặng.</p>
<h3>Và tôi đã khóc&#8230;</h3>
<p>Khi tôi đang chơi với những đứa trẻ. Chúng tôi chơi trò chuyền vật và hát. Những đứa trẻ rất hứng thú với trò chơi, chúng chuyền đồ rất nhanh. Bỗng một đứa trẻ nhỏ tuổi òa khóc. Chúng tôi rất bất ngờ, vội quây lấy đứa bé. Tôi ẳm đứa bé lên và dỗ dành nó. Nhưng nó vẫn cứ khóc. Nó khóc lớn, mắt đỏ hoe cả lên nhưng không nói tại sao khóc. Tôi đem kẹo bánh dỗ nhưng nó chỉ cầm mà không ăn hay nín khóc. Một đứa trẻ lớn hơn nói lớn: &#8220;Nó lại nhớ mẹ nó mà khóc đấy!&#8221;.</p>
<p>Đứa bé thút thít, nấc nghẹn lên tiếng: &#8220;Con không cần gì hết, con cần mẹ con à!&#8221;. Nhìn vào đôi mắt to tròn đẫm lệ của nó, mắt tôi cũng dần đỏ hoe. Cha, mẹ &#8211; Những điều linh thiêng nhất mà đa số chúng ta đều có. Đôi khi chúng ta cũng không quá đủ trân trọng thứ ấy. Nhưng đứa bé này, à không, tất cả những đứa bé này đều thiếu nó.</p>
<p>Tôi đưa đứa bé lại cho người khác ẩm, đứa bé đã nín khóc. Nhưng tôi đã bỏ đi ra sau nhà, có lẽ nước mắt thật dễ lây cho nhau.</p>
<p><figure id="attachment_2573" aria-describedby="caption-attachment-2573" style="width: 680px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="wp-image-2573" src="https://media.huynhhieutravel.com/một-em-bé-dễ-thương-ở-nhà-trẻ-Thiên-Ân.jpg" alt="Một em bé dễ thương ở nhà trẻ Thiên Ân" width="680" height="451" srcset="https://media.huynhhieutravel.com/một-em-bé-dễ-thương-ở-nhà-trẻ-Thiên-Ân.jpg 960w, https://media.huynhhieutravel.com/một-em-bé-dễ-thương-ở-nhà-trẻ-Thiên-Ân-768x509.jpg 768w" sizes="(max-width: 680px) 100vw, 680px" /><figcaption id="caption-attachment-2573" class="wp-caption-text">Một em bé dễ thương ở nhà trẻ Thiên Ân</figcaption></figure></p>
<h3>Câu chuyện của những đứa trẻ ngoan bị bỏ rơi</h3>
<p>Tôi ngập ngừng khi gặp cô phụ trách. Tôi không mở miệng được vì ngại hỏi. Dường như hiểu được ánh mắt và cử chỉ của tôi. Cô phụ trách nhẹ cười và nói:</p>
<p>&#8211; Có phải con muốn hỏi những đứa trẻ ở đây đều không có cha mẹ đúng không? Cũng không hẳn tất cả đều không có cha mẹ. Những đứa trẻ ở đây cũng có những đứa bị bỏ rơi. Chúng bị bỏ rơi từ nhỏ, vì cha mẹ chúng có người vì &#8220;lỡ&#8221; có chúng khi còn nhỏ hoặc có người nuôi không nổi phải bỏ lại đây. Ở đây có những đứa vẫn chưa biết tiếng Kinh nữa đó con. Nhưng Thiên Ân đã thu nhận tất cả chúng lại, chăm sóc những đứa bé này, dạy chúng học. Chúng rất chăm ngoan lại thông minh nữa. Hy vọng 10,20 năm sau chúng sẽ thành những người giúp ích cho xã hội.</p>
<p>Tôi ngập ngừng hỏi tiếp:</p>
<p>&#8211; Nuôi chúng khó khăn không cô?</p>
<p>Cô dịu dàng trả lời:</p>
<p>&#8211; À! Khó chứ con. Một đứa trẻ thôi đã nuôi vất vả lắm rồi. Cô có tới mấy chuc đứa làm sao không khó được. Nhưng chúng ta chỉ cần cái tâm của mình, những cái khó sẽ được giải quyết thôi. Ở đây các cô chia nhau chăm sóc những đứa trẻ này. Dạy chúng đôi khi nghiêm khắc nhưng chúng cũng rất ngoan. Kinh phí nuôi dạy chúng thì có những nhà hảo tâm và nhà nước giúp đỡ thêm. Cô làm được việc này cũng là nhờ những người như nhóm của con vậy.</p>
<p>Tôi thật sự khâm phục cô và yêu những đứa trẻ này khi biết rõ hơn về thân thế của chúng.</p>
<p>Nếu bạn ở Cần Thơ, những đóng góp của bạn về vật chất hay góp sức thăm những đứa bé này đều là những san sẻ tuyệt vời. Sau những lần thăm nơi đây, tôi đều cảm thấy được dung dưỡng và thanh lọc hơn. Tôi hy vọng các bạn cũng sẽ chia sẽ tình thương của mình với nơi đây. Hy vọng Mái ấm Thiên Ân sẽ ngày càng phát triển. Nơi đây sẽ trở thành ngôi nhà, gia đình của những đứa trẻ cơ nhở mồ côi, thiếu may mắn trong cuộc sống.</p>
', 'Nhà trẻ Thiên Ân hay còn gọi cái tên thân thương khác là Mái ấm Thiên Ân. Đúng như cái tên mái ấm của mình. Nơi đây là nơi nuôi dưỡng ấm áp cho các trẻ mồ côi hoặc những đứa bé có gia đình khó khăn không nuôi nổi. Nơi đây đã mang lại [&hellip;]', 1019, 'post', '2018-06-25 08:51:23', '2023-04-23 12:25:54');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1016, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1016, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1016, 298);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1016, 97);