-- huynhhieutravel DB Seed

-- CATEGORIES
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (431, 'Blog', 'blog', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (489, 'Cá Nhân', 'ca-nhan', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (1, 'Chưa được phân loại', 'khong-phan-loai', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (500, 'Chuyện Văn Phòng', 'chuyen-van-phong', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (34, 'Địa Điểm', 'dia-diem-du-lich', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (493, 'Giáo dục', 'giao-duc', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (380, 'Hiệu ứng và tính năng thú vị cho website', 'hieu-ung-va-tinh-nang-website', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (481, 'Học AI', 'hoc-ai', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (420, 'Kinh Nghiệm Làm Việc', 'kinh-nghiem', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (434, 'Kỹ Năng Làm Việc', 'ky-nang-lam-viec', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (501, 'Marketing', 'marketing', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (373, 'Project', 'project', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (427, 'SEO', 'seo', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (377, 'Tarot', 'tarot', '');
INSERT OR IGNORE INTO Category (id, name, slug, description) VALUES (467, 'Xây dựng hệ thống học tập LMS', 'lms', '');

-- TAGS
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (84, '18 đời vua hùng', '18-doi-vua-hung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (72, '5 cách làm quen bạn mới khi đi du lịch', '5-cach-lam-quen-ban-moi-khi-di-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (408, 'Ace of Wands', 'ace-of-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (482, 'AI', 'ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (86, 'an dương vương', 'an-duong-vuong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (236, 'Ảnh Cần Thơ xưa', 'anh-can-tho-xua');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (88, 'âu lạc', 'au-lac');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (283, 'bảng giá cho thuê tàu đi chợ nổi cái răng', 'bang-gia-cho-thue-tau-di-cho-noi-cai-rang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (158, 'banshee', 'banshee');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (160, 'banshee là ai', 'banshee-la-ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (159, 'banshee là gì', 'banshee-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (147, 'Basilisk', 'basilisk');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (150, 'Basilisk là con gì', 'basilisk-la-con-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (148, 'Basilisk là gì', 'basilisk-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (348, 'bến tre', 'ben-tre');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (231, 'biệt thự hằng ngay đà lạt', 'biet-thu-hang-ngay-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (117, 'bikini', 'bikini');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (152, 'black shuck', 'black-shuck');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (155, 'black shuck là gì', 'black-shuck-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (43, 'blogger du lịch', 'blogger-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (38, 'Blogger Du Lịch Việt Nam', 'blogger-du-lich-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (400, 'Bộ Ẩn Chính', 'bo-an-chinh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (238, 'bộ ảnh Cần Thơ xưa nay', 'bo-anh-can-tho-xua-nay');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (407, 'Bộ Wands', 'bo-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (378, 'Bói Tarot', 'boi-tarot');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (131, 'bóng đá', 'bong-da');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (464, 'Brainstorm', 'brainstorm');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (68, 'cách chạy quảng cáo facebook', 'cach-chay-quang-cao-facebook');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (107, 'cách đi chợ nổi cái răng', 'cach-di-cho-noi-cai-rang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (216, 'cách đi langbiang', 'cach-di-langbiang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (230, 'cách đi thung lũng vàng', 'cach-di-thung-lung-vang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (202, 'cách đi tuyệt tình cốc đà lạt', 'cach-di-tuyet-tinh-coc-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (116, 'cách kiếm tiền với minds', 'cach-kiem-tien-voi-minds');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (73, 'cách tìm bạn khi du lịch', 'cach-tim-ban-khi-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (277, 'cafe đà lạt', 'cafe-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (295, 'cafe nông trại vui vẻ đà lạt', 'cafe-nong-trai-vui-ve-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (289, 'cafe panorama', 'cafe-panorama');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (281, 'cafe pini đà lạt', 'cafe-pini-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (284, 'cafe sense coffee đà lạt', 'cafe-sense-coffee-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (292, 'cafe thiên thanh đà lạt', 'cafe-thien-thanh-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (278, 'cafe tỏi đen', 'cafe-toi-den');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (290, 'cafe view đẹp đà lạt', 'cafe-view-dep-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (359, 'cần thơ', 'can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (237, 'Cần Thơ xưa và nay', 'can-tho-xua-va-nay');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (351, 'cảnh đẹp', 'canh-dep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (478, 'Case Study', 'case-study');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (293, 'cầu thang vô cực', 'cau-thang-vo-cuc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (132, 'cầu thủ bóng đá', 'cau-thu-bong-da');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (133, 'cầu thủ xuất sắc nhất thế giới', 'cau-thu-xuat-sac-nhat-the-gioi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (250, 'cây cô đơn đà lạt', 'cay-co-don-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (161, 'Cerberus', 'cerberus');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (162, 'cerberus là gì', 'cerberus-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (474, 'Chat GPT cho SEO', 'chat-gpt-cho-seo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (483, 'Chatbot', 'chatbot');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (421, 'ChatGPT', 'chatgpt');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (475, 'ChatGPT cho SEO', 'chatgpt-cho-seo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (438, 'Chiến lược kinh doanh', 'chien-luoc-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (444, 'Chính sách kinh doanh', 'chinh-sach-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (165, 'chó 3 đầu', 'cho-3-dau');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (164, 'chó ba đầu', 'cho-ba-dau');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (153, 'chó đen', 'cho-den');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (104, 'Chợ Nổi Cái Răng', 'cho-noi-cai-rang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (340, 'chùa', 'chua');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (272, 'chùa đà lạt', 'chua-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (271, 'chùa linh phước', 'chua-linh-phuoc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (270, 'chùa ve chai', 'chua-ve-chai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (485, 'Cơ bản về AI', 'co-ban-ve-ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (92, 'cổ loa thành', 'co-loa-thanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (488, 'Copywritting', 'copywritting');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (128, 'cr7', 'cr7');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (232, 'crazy house', 'crazy-house');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (127, 'Cristiano Ronaldo', 'cristiano-ronaldo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (211, 'cuộc chiến thương mại mỹ trung', 'cuoc-chien-thuong-mai-my-trung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (193, 'danh sách chương trình thực tế', 'danh-sach-chuong-trinh-thuc-te');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (395, 'Death', 'death');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (456, 'Dịch vụ khách hàng', 'dich-vu-khach-hang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (265, 'dinh pinhaat', 'dinh-pinhaat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (465, 'Dự án', 'du-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (349, 'du lịch', 'du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (307, 'du lịch biển đảo', 'du-lich-bien-dao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (105, 'Du Lịch Cần Thơ', 'du-lich-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (106, 'du lịch chợ nổi', 'du-lich-cho-noi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (48, 'du lịch đà lạt', 'du-lich-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (273, 'du lịch đà lạt nên đi đâu', 'du-lich-da-lat-nen-di-dau');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (41, 'du lịch đúng nghĩa', 'du-lich-dung-nghia');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (58, 'du lịch hội an', 'du-lich-hoi-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (39, 'du lịch không hoàn hảo', 'du-lich-khong-hoan-hao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (42, 'du lịch là như thế nào', 'du-lich-la-nhu-the-nao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (306, 'du lịch miền tây', 'du-lich-mien-tay');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (309, 'du lịch miền trung', 'du-lich-mien-trung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (308, 'du lịch miền ttrung', 'du-lich-mien-ttrung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (40, 'du lịch việt nam', 'du-lich-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (44, 'đà lạt', 'da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (248, 'đà lạt milk farm', 'da-lat-milk-farm');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (354, 'đại học', 'dai-hoc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (356, 'đại học hùng vương', 'dai-hoc-hung-vuong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (446, 'Đào tạo nhân viên', 'dao-tao-nhan-vien');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (52, 'Đèn lồng Hội An', 'den-long-hoi-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (245, 'đèo thiên phúc đức', 'deo-thien-phuc-duc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (242, 'điểm du lịch đà lạt', 'diem-du-lich-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (263, 'điểm du lịch ở đà lạt', 'diem-du-lich-o-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (267, 'điểm tham quan đà lạt', 'diem-tham-quan-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (460, 'Điều hành doanh nghiệp', 'dieu-hanh-doanh-nghiep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (215, 'đỉnh núi Langbiang', 'dinh-nui-langbiang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (266, 'đỉnh núi pinhatt', 'dinh-nui-pinhatt');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (264, 'đỉnh pinhatt', 'dinh-pinhatt');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (252, 'Đồi chè Cầu Đất', 'doi-che-cau-dat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (251, 'đồi thiên phúc đức', 'doi-thien-phuc-duc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (454, 'Đóng cửa doanh nghiệp', 'dong-cua-doanh-nghiep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (347, 'đồng tháp', 'dong-thap');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (219, 'đường đi làng cù lần', 'duong-di-lang-cu-lan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (257, 'đường đi thác pongour', 'duong-di-thac-pongour');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (210, 'đường hầm đất sét', 'duong-ham-dat-set');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (209, 'đường hầm điêu khắc', 'duong-ham-dieu-khac');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (490, 'Elementor', 'elementor');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (491, 'Facebook', 'facebook');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (67, 'facebook marketing', 'facebook-marketing');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (197, 'festival hoa đăng cần thơ', 'festival-hoa-dang-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (437, 'Five Forces', 'five-forces');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (262, 'ga đà lạt', 'ga-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (442, 'Giá trị kinh doanh', 'gia-tri-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (221, 'giá vé làng cù lần', 'gia-ve-lang-cu-lan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (228, 'giá vé thung lũng vàng', 'gia-ve-thung-lung-vang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (424, 'Google Doanh Nghiệp', 'google-doanh-nghiep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (423, 'Google Maps', 'google-maps');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (476, 'Google Search', 'google-search');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (279, 'green box coffee', 'green-box-coffee');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (477, 'Hành Trình Khách Hàng', 'hanh-trinh-khach-hang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (167, 'hercules', 'hercules');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (168, 'Herne the Hunter', 'herne-the-hunter');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (170, 'Herne the Hunter là ai', 'herne-the-hunter-la-ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (169, 'Herne the Hunter là gì', 'herne-the-hunter-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (350, 'hình ảnh', 'hinh-anh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (352, 'hồ', 'ho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (198, 'hoa đăng', 'hoa-dang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (54, 'hội an', 'hoi-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (56, 'hội an về đêm', 'hoi-an-ve-dem');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (189, 'hội trại hè', 'hoi-trai-he');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (191, 'hội trại hè phật giáo', 'hoi-trai-he-phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (181, 'hội trại phật giáo', 'hoi-trai-phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (182, 'hội trại tuổi thanh xuân', 'hoi-trai-tuoi-thanh-xuan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (175, 'hội trại tuổi trẻ phật giáo', 'hoi-trai-tuoi-tre-phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (176, 'hội trại tuổi trẻ phật giáo 2018', 'hoi-trai-tuoi-tre-phat-giao-2018');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (178, 'hội trại tuổi trẻ phật giáo lần 13', 'hoi-trai-tuoi-tre-phat-giao-lan-13');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (177, 'hội trại tuổi trẻ phật giáo Phan thiết', 'hoi-trai-tuoi-tre-phat-giao-phan-thiet');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (190, 'hội trại tuổi trẻ phật giáo tuổi thanh xuân', 'hoi-trai-tuoi-tre-phat-giao-tuoi-thanh-xuan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (343, 'homestay', 'homestay');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (305, 'homestay đà lạt', 'homestay-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (188, 'hơn 1000 thanh thiếu niên tham gia hội trại', 'hon-1000-thanh-thieu-nien-tham-gia-hoi-trai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (179, 'htttpg', 'htttpg');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (180, 'htttpg2018', 'htttpg2018');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (59, 'huynh hieu travel', 'huynh-hieu-travel');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (409, 'II Wands', 'ii-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (410, 'III Wands', 'iii-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (60, 'Infographic', 'infographic');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (192, 'infographic chương trình thực tế ở Việt Nam', 'infographic-chuong-trinh-thuc-te-o-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (213, 'infographic cuộc chiến thương mại mỹ trung', 'infographic-cuoc-chien-thuong-mai-my-trung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (61, 'infographic lịch sử việt nam', 'infographic-lich-su-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (243, 'infographic thủy điện việt nam', 'infographic-thuy-dien-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (411, 'IV Wands', 'iv-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (416, 'IX Wands', 'ix-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (404, 'Judgement', 'judgement');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (393, 'Justice', 'justice');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (463, 'Kế hoạch chiến lược', 'ke-hoach-chien-luoc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (462, 'Kế hoạch kế nhiệm', 'ke-hoach-ke-nhiem');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (443, 'Kế hoạch kinh doanh', 'ke-hoach-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (143, 'kelpie', 'kelpie');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (145, 'kelpie là gì', 'kelpie-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (362, 'kênh đào', 'kenh-dao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (119, 'khách sạn azerai', 'khach-san-azerai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (120, 'khách sạn azerai cần thơ', 'khach-san-azerai-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (123, 'khách sạn cần thơ', 'khach-san-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (126, 'khách sạn đẹp', 'khach-san-dep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (195, 'khai mạc lễ hội hoa đăng cần thơ', 'khai-mac-le-hoi-hoa-dang-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (53, 'Khám phá hội an', 'kham-pha-hoi-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (70, 'khóa học facebook', 'khoa-hoc-facebook');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (186, 'khóa tu mùa hè', 'khoa-tu-mua-he');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (185, 'khóa tu mùa hè phật giáo', 'khoa-tu-mua-he-phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (184, 'khóa tu phật giáo', 'khoa-tu-phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (457, 'Khởi nghiệp', 'khoi-nghiep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (342, 'khu du lịch', 'khu-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (241, 'khu du lịch đà lạt', 'khu-du-lich-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (240, 'khu du lịch lá phong', 'khu-du-lich-la-phong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (256, 'khu du lịch thác pongour', 'khu-du-lich-thac-pongour');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (115, 'kiếm tiền với minds', 'kiem-tien-voi-minds');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (76, 'kinh dương vương', 'kinh-duong-vuong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (77, 'kinh dương vương là ai', 'kinh-duong-vuong-la-ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (302, 'kinh nghiệm du lịch', 'kinh-nghiem-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (203, 'kinh nghiệm du lịch đà lạt', 'kinh-nghiem-du-lich-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (108, 'kinh nghiệm đi chợ nổi cái răng', 'kinh-nghiem-di-cho-noi-cai-rang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (217, 'kinh nghiệm đi đỉnh langbiang', 'kinh-nghiem-di-dinh-langbiang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (222, 'kinh nghiệm đi làng cù lần', 'kinh-nghiem-di-lang-cu-lan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (201, 'kinh nghiệm đi tuyệt tình cốc đà lạt', 'kinh-nghiem-di-tuyet-tinh-coc-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (418, 'Knight of Wands', 'knight-of-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (440, 'KPI', 'kpi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (81, 'Lạc long quân', 'lac-long-quan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (82, 'lạc long quân là ai', 'lac-long-quan-la-ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (218, 'làng cù lần', 'lang-cu-lan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (220, 'làng cù lần đà lạt', 'lang-cu-lan-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (259, 'làng hoa đà lạt', 'lang-hoa-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (258, 'lang hoa van thanh', 'lang-hoa-van-thanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (214, 'Langbiang', 'langbiang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (338, 'lễ hội', 'le-hoi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (199, 'lễ hội cần thơ', 'le-hoi-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (196, 'lễ hội hoa đăng cần thơ', 'le-hoi-hoa-dang-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (80, 'lịch sử', 'lich-su');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (118, 'lịch sử bikini', 'lich-su-bikini');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (64, 'lịch sử việt nam', 'lich-su-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (484, 'LLM', 'llm');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (430, 'Lỗi SEO', 'loi-seo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (233, 'lưu trú đà lạt', 'luu-tru-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (174, 'ma quỷ', 'ma-quy');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (249, 'ma rừng lữ quán', 'ma-rung-lu-quan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (94, 'mái ấm thiên ân', 'mai-am-thien-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (136, 'manchester united', 'manchester-united');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (339, 'măng đen', 'mang-den');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (112, 'mạng xã hội', 'mang-xa-hoi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (109, 'mạng xã hội minds', 'mang-xa-hoi-minds');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (114, 'mạng xã hội minds là gì', 'mang-xa-hoi-minds-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (111, 'mạng xã hội mới', 'mang-xa-hoi-moi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (422, 'Marketing', 'marketing');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (461, 'Mẫu Hồ Sơ Nhân Sự', 'mau-ho-so-nhan-su');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (459, 'Mẫu kế hoạch', 'mau-ke-hoach');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (268, 'mê linh cafe', 'me-linh-cafe');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (75, 'mẹo vặt du lịch', 'meo-vat-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (135, 'messi', 'messi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (110, 'minds', 'minds');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (113, 'minds là gì', 'minds-la-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (458, 'Mô hình kinh doanh', 'mo-hinh-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (294, 'nấc thang lên thiên đường', 'nac-thang-len-thien-duong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (448, 'Năng lực kinh doanh', 'nang-luc-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (449, 'Nghiên cứu thị trường', 'nghien-cuu-thi-truong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (472, 'Ngôn ngữ đơn giản', 'ngon-ngu-don-gian');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (146, 'ngựa kelpie', 'ngua-kelpie');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (134, 'người ngoài hành tinh', 'nguoi-ngoai-hanh-tinh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (87, 'nhà nước âu lạc', 'nha-nuoc-au-lac');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (298, 'nhà trẻ cần thơ', 'nha-tre-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (99, 'nhà trẻ mồ côi', 'nha-tre-mo-coi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (93, 'nhà trẻ thiên ân', 'nha-tre-thien-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (101, 'nhà triệu', 'nha-trieu');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (142, 'nhân vật game', 'nhan-vat-game');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (303, 'những điều thú vị', 'nhung-dieu-thu-vi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (345, 'ninh thuận', 'ninh-thuan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (205, 'nông trại black rock garden đà lạt', 'nong-trai-black-rock-garden-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (206, 'nông trại chó cưng', 'nong-trai-cho-cung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (204, 'nông trại thú cưng đà lạt', 'nong-trai-thu-cung-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (439, 'OKR', 'okr');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (156, 'old shuck', 'old-shuck');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (436, 'PESTLE', 'pestle');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (346, 'phan rang', 'phan-rang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (187, 'phật giáo', 'phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (455, 'Phát triển doanh nghiệp', 'phat-trien-doanh-nghiep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (57, 'phố cổ hội an', 'pho-co-hoi-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (282, 'pini coffee', 'pini-coffee');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (487, 'Prompting trong ChatGPT', 'prompting-trong-chatgpt');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (144, 'quái vật', 'quai-vat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (149, 'quái vật Basilisk', 'quai-vat-basilisk');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (157, 'quái vật phương tây', 'quai-vat-phuong-tay');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (357, 'quán cà phê', 'quan-ca-phe');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (360, 'quán cà phê học bài', 'quan-ca-phe-hoc-bai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (358, 'quán cafe cần thơ', 'quan-cafe-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (269, 'quán cafe đà lạt', 'quan-cafe-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (291, 'quán cafe Full House Coffee', 'quan-cafe-full-house-coffee');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (280, 'quán cafe ngon đà lạt', 'quan-cafe-ngon-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (287, 'quán cafe ở đà lạt', 'quan-cafe-o-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (288, 'quán cafe panorama đà lạt', 'quan-cafe-panorama-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (275, 'quán cafe the dreamer đà lạt', 'quan-cafe-the-dreamer-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (286, 'quán của tuổi thanh xuân', 'quan-cua-tuoi-thanh-xuan');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (445, 'Quản lý nhân sự', 'quan-ly-nhan-su');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (451, 'Quản lý rủi ro', 'quan-ly-rui-ro');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (492, 'Quảng cáo', 'quang-cao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (71, 'quảng cáo facebook', 'quang-cao-facebook');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (235, 'quảng trường đà lạt', 'quang-truong-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (234, 'quảng trường lâm viên', 'quang-truong-lam-vien');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (130, 'real madrid', 'real-madrid');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (122, 'resort azerai cần thơ', 'resort-azerai-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (124, 'resort cần thơ', 'resort-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (125, 'resort đẹp cần thơ', 'resort-dep-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (227, 'review thung lũng vàng', 'review-thung-lung-vang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (355, 'review trường học', 'review-truong-hoc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (129, 'ronaldo', 'ronaldo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (447, 'Sale', 'sale');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (432, 'Sáng Tạo', 'sang-tao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (285, 'sense coffee', 'sense-coffee');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (429, 'SEO', 'seo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (428, 'SEO cho người mới', 'seo-cho-nguoi-moi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (50, 'sống trọn vẹn', 'song-tron-ven');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (466, 'Sprint Backlog', 'sprint-backlog');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (391, 'Strength', 'strength');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (239, 'Sự đổi thay của thành phố Cần Thơ theo thời gian', 'su-doi-thay-cua-thanh-pho-can-tho-theo-thoi-gian');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (299, 'sự tích dân gian', 'su-tich-dan-gian');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (91, 'sự tích thành cổ loa', 'su-tich-thanh-co-loa');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (296, 'sunny farm đà lạt', 'sunny-farm-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (224, 'suối vàng', 'suoi-vang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (226, 'suối vàng đà lạt', 'suoi-vang-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (435, 'SWOT', 'swot');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (450, 'Tài chính doanh nghiệp', 'tai-chinh-doanh-nghiep');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (79, 'tại sao vua hùng là thủy tổ việt nam', 'tai-sao-vua-hung-la-thuy-to-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (441, 'Tầm nhìn kinh doanh', 'tam-nhin-kinh-doanh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (69, 'tạo đối tượng từ khách hàng đã xem video trên facebook', 'tao-doi-tuong-tu-khach-hang-da-xem-video-tren-facebook');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (194, 'tất cả chương trình thực tế ở việt nam', 'tat-ca-chuong-trinh-thuc-te-o-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (344, 'tây nguyên', 'tay-nguyen');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (274, 'Tea house đồi chè cầu đất', 'tea-house-doi-che-cau-dat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (396, 'Temperance', 'temperance');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (253, 'thaác pôngur', 'thaac-pongur');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (341, 'thác', 'thac');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (207, 'thác datanla', 'thac-datanla');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (208, 'thác đà lạt', 'thac-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (255, 'thác pongour', 'thac-pongour');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (254, 'thác pôngur', 'thac-pongur');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (247, 'tham quan đà lạt', 'tham-quan-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (55, 'tham quan hội an', 'tham-quan-hoi-an');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (141, 'thần thoại', 'than-thoai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (172, 'thần thoại anh', 'than-thoai-anh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (138, 'thần thoại bắc âu', 'than-thoai-bac-au');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (166, 'thần thoại hy lạp', 'than-thoai-hy-lap');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (90, 'thành cổ loa', 'thanh-co-loa');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (45, 'thành phố hoa', 'thanh-pho-hoa');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (46, 'thành phố sương', 'thanh-pho-suong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (47, 'thành phố thông', 'thanh-pho-thong');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (390, 'The Chariot', 'the-chariot');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (397, 'The Devil', 'the-devil');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (276, 'the dreamer cine coffee tea', 'the-dreamer-cine-coffee-tea');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (387, 'The Emperor', 'the-emperor');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (386, 'The Empress', 'the-empress');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (384, 'The Fool', 'the-fool');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (394, 'The Hanged Man', 'the-hanged-man');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (392, 'The Hermit', 'the-hermit');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (388, 'The Hierophant', 'the-hierophant');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (385, 'The High Priestess', 'the-high-priestess');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (389, 'The Lovers', 'the-lovers');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (383, 'The Magician', 'the-magician');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (399, 'The Moon', 'the-moon');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (398, 'The Star', 'the-star');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (403, 'The Sun', 'the-sun');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (402, 'The Tower', 'the-tower');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (469, 'The Washington Post', 'the-washington-post');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (405, 'The World', 'the-world');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (96, 'thiện nguyện', 'thien-nguyen');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (98, 'thiện nguyện cần thơ', 'thien-nguyen-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (470, 'Thiết kế', 'thiet-ke');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (374, 'Thiết kế Website', 'thiet-ke-website');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (304, 'thông tin cần thơ', 'thong-tin-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (223, 'thung lũng vàng', 'thung-lung-vang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (229, 'thung lũng vàng có gì', 'thung-lung-vang-co-gi');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (225, 'thung lũng vàng đà lạt', 'thung-lung-vang-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (212, 'thương mại mỹ trung 2018', 'thuong-mai-my-trung-2018');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (244, 'thủy điện việt nam', 'thuy-dien-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (83, 'thủy tổ việt nam', 'thuy-to-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (78, 'thủy tổ việt nam là ai', 'thuy-to-viet-nam-la-ai');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (479, 'Thuyết Trình', 'thuyet-trinh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (452, 'Tiếp thị và bán hàng', 'tiep-thi-va-ban-hang');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (74, 'tìm bạn đồng hành khi đi du lịch', 'tim-ban-dong-hanh-khi-di-du-lich');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (49, 'tìm bình yên ở đà lạt', 'tim-binh-yen-o-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (62, 'tìm hiểu lịch sử việt nam', 'tim-hieu-lich-su-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (480, 'Time Management', 'time-management');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (301, 'tôi đi phượt', 'toi-di-phuot');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (63, 'tóm tắt lịch sử việt nam', 'tom-tat-lich-su-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (297, 'trại hè', 'trai-he');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (183, 'trại hè phật giáo', 'trai-he-phat-giao');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (102, 'tranh cãi về triệu đà', 'tranh-cai-ve-trieu-da');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (100, 'triệu đà', 'trieu-da');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (103, 'triệu đà có phải là vua nước việt', 'trieu-da-co-phai-la-vua-nuoc-viet');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (261, 'trường cao đẳng sư phạm đà lạt', 'truong-cao-dang-su-pham-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (173, 'truyền thuyết Anh', 'truyen-thuyet-anh');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (139, 'truyền thuyết bắc âu', 'truyen-thuyet-bac-au');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (300, 'truyền thuyết dân gian', 'truyen-thuyet-dan-gian');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (171, 'truyền thuyết Herne the Hunter', 'truyen-thuyet-herne-the-hunter');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (163, 'truyền thuyết về cerberus', 'truyen-thuyet-ve-cerberus');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (154, 'truyền thuyết về chó đen', 'truyen-thuyet-ve-cho-den');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (89, 'truyền thuyết việt nam', 'truyen-thuyet-viet-nam');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (95, 'từ thiện', 'tu-thien');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (97, 'từ thiện cần thơ', 'tu-thien-can-tho');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (453, 'Tuyển dụng', 'tuyen-dung');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (200, 'tuyệt tình cốc', 'tuyet-tinh-coc');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (486, 'Ứng dụng cơ bản ChatGPT', 'ung-dung-co-ban-chatgpt');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (412, 'V Wands', 'v-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (137, 'Valkyrie', 'valkyrie');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (471, 'Văn bản thay thế', 'van-ban-thay-the');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (140, 'văn học phương tây', 'van-hoc-phuong-tay');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (413, 'VI Wands', 'vi-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (433, 'Viết Email', 'viet-email');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (414, 'VII Wands', 'vii-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (415, 'VIII Wands', 'viii-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (151, 'vua của loài rắn', 'vua-cua-loai-ran');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (85, 'vua hùng và những truyền thuyết', 'vua-hung-va-nhung-truyen-thuyet');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (260, 'vườn hoa đà lạt', 'vuon-hoa-da-lat');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (246, 'Vườn thú Zoodoo', 'vuon-thu-zoodoo');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (401, 'Wheel of Fortune', 'wheel-of-fortune');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (417, 'X Wands', 'x-wands');
INSERT OR IGNORE INTO Tag (id, name, slug) VALUES (379, 'Ý nghĩa lá bài Tarot', 'y-nghia-la-bai-tarot');

-- MEDIA
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13225, 'https://media.huynhhieutravel.com/huynh-hieu-vlog.jpg', '', '', 'Huynh Hieu là Podcast', '2025-09-01 20:13:26');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13223, 'https://media.huynhhieutravel.com/du-an-cua-fit-tour.png', 'Dự án của FIT Tour', 'Dự án của FIT Tour', 'Dự án của FIT Tour', '2025-09-01 20:05:36');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13219, 'https://media.huynhhieutravel.com/Lich-trinh-de-theo-doi.png', 'Lịch trình tour dễ theo dõi theo thời gian', 'Lịch trình tour dễ theo dõi theo thời gian', 'Lịch trình tour dễ theo dõi theo thời gian', '2025-09-01 19:35:39');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13218, 'https://media.huynhhieutravel.com/tour-de-xem-va-filter.png', 'Tour dễ xem và tìm kiếm', 'Tour dễ xem và tìm kiếm', 'Tour dễ xem và tìm kiếm', '2025-09-01 19:35:34');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13217, 'https://media.huynhhieutravel.com/emagazine-de-xem.png', 'Emagazine bên trong dễ xem, thân thiện và chuyên nghiệp như một Chuyên Trang Du Lịch', 'Emagazine bên trong dễ xem, thân thiện và chuyên nghiệp như một Chuyên Trang Du Lịch', 'Emagazine bên trong dễ xem, thân thiện và chuyên nghiệp như một Chuyên Trang Du Lịch', '2025-09-01 19:35:29');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13216, 'https://media.huynhhieutravel.com/so-lieu-vung-manh.png', 'Số liệu bền vững', 'Số liệu bền vững', 'Số liệu bền vững', '2025-09-01 19:35:24');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13215, 'https://media.huynhhieutravel.com/nhieu-emagazine-du-lich.png', 'Nhiều Emagazine du lịch hấp dẫn như case study', 'Nhiều Emagazine du lịch hấp dẫn như case study', 'Nhiều Emagazine du lịch hấp dẫn như case study', '2025-09-01 19:35:19');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13214, 'https://media.huynhhieutravel.com/du-an-du-lich-co-guu-fittour.png', 'Dự án Du lịch có Guu (FIT Tour)', 'Dự án Du lịch có Guu (FIT Tour)', 'Dự án Du lịch có Guu (FIT Tour)', '2025-09-01 19:30:01');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13205, 'https://media.huynhhieutravel.com/check-bai-tap-tren-he-thong.png', 'Xem danh sách bài tập và chấm điểm trên hệ thống', 'Xem danh sách bài tập và chấm điểm trên hệ thống', 'Xem danh sách bài tập và chấm điểm trên hệ thống', '2025-09-01 18:18:56');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13204, 'https://media.huynhhieutravel.com/diem-danh-tren-he-thong.png', 'Điểm danh nhanh chóng trên hệ thống làm việc', 'Điểm danh nhanh chóng trên hệ thống làm việc', 'Điểm danh nhanh chóng trên hệ thống làm việc', '2025-09-01 18:18:51');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13203, 'https://media.huynhhieutravel.com/giao-dien-giao-vien.png', 'Giao diện xem các lớp của Giáo viên và có thông báo', 'Giao diện xem các lớp của Giáo viên và có thông báo', 'Giao diện xem các lớp của Giáo viên và có thông báo', '2025-09-01 18:18:47');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13202, 'https://media.huynhhieutravel.com/sach-co-phong-cach-hien-dai.png', 'Sách có phong cách hiện đại', 'Sách có phong cách hiện đại', 'Sách có phong cách hiện đại', '2025-09-01 17:23:29');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13201, 'https://media.huynhhieutravel.com/lms-de-nhin.png', 'LMS dễ học, dễ theo dõi', 'LMS dễ học, dễ theo dõi', 'LMS dễ học, dễ theo dõi', '2025-09-01 17:19:38');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13200, 'https://media.huynhhieutravel.com/he-thong-website-fme-hien-dai.png', 'Hệ thống Website dễ nhìn, dễ tuỳ chỉnh', 'Hệ thống Website dễ nhìn, dễ tuỳ chỉnh', 'Hệ thống Website dễ nhìn, dễ tuỳ chỉnh', '2025-09-01 17:19:33');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13199, 'https://media.huynhhieutravel.com/he-thong-crm-mini.png', '', '', 'Hệ thống CRM mini chấm điểm và xem lịch', '2025-09-01 17:12:30');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13198, 'https://media.huynhhieutravel.com/he-thong-lms-ung-dung.png', 'Hệ thống LMS ứng dụng', 'Hệ thống LMS ứng dụng', 'Hệ thống LMS ứng dụng', '2025-09-01 17:12:25');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13197, 'https://media.huynhhieutravel.com/he-thong-xay-dung-fme-system.png', '', '', 'Hệ sinh thái FME', '2025-09-01 16:45:32');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13191, 'https://media.huynhhieutravel.com/he-thong-fme.png', '', '', 'Hệ thống FME', '2025-09-01 13:56:14');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13076, 'https://media.huynhhieutravel.com/Trees.png', '', '', '', '2024-09-11 14:13:18');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13075, 'https://media.huynhhieutravel.com/Mountain-3.png', '', '', '', '2024-09-11 14:13:14');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13074, 'https://media.huynhhieutravel.com/Mountain-2.png', '', '', '', '2024-09-11 14:13:10');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13073, 'https://media.huynhhieutravel.com/Mountain-1.png', '', '', '', '2024-09-11 14:13:06');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13072, 'https://media.huynhhieutravel.com/moon.png', '', '', '', '2024-09-11 14:13:02');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13071, 'https://media.huynhhieutravel.com/Final-image.png', '', '', '', '2024-09-11 14:12:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13070, 'https://media.huynhhieutravel.com/Cloud.png', '', '', '', '2024-09-11 14:12:53');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13060, 'https://media.huynhhieutravel.com/15-black_shadow.png', '', '', '', '2024-09-11 09:42:48');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13059, 'https://media.huynhhieutravel.com/14-black_shadow.png', '', '', '', '2024-09-11 09:42:44');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13058, 'https://media.huynhhieutravel.com/13-sun.png', '', '', '', '2024-09-11 09:42:34');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13057, 'https://media.huynhhieutravel.com/12-fog.png', '', '', '', '2024-09-11 09:42:28');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13056, 'https://media.huynhhieutravel.com/11-rock-.png', '', '', '', '2024-09-11 09:42:25');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13055, 'https://media.huynhhieutravel.com/10-rock.png', '', '', '', '2024-09-11 09:42:18');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13054, 'https://media.huynhhieutravel.com/9-fog.png', '', '', '', '2024-09-11 09:42:14');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13053, 'https://media.huynhhieutravel.com/8-Island-reverse.png', '', '', '', '2024-09-11 09:42:07');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13052, 'https://media.huynhhieutravel.com/7-fog.png', '', '', '', '2024-09-11 09:41:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13051, 'https://media.huynhhieutravel.com/6-mountain.png', '', '', '', '2024-09-11 09:41:50');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13050, 'https://media.huynhhieutravel.com/5-Island.png', '', '', '', '2024-09-11 09:41:45');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13049, 'https://media.huynhhieutravel.com/4-fog.png', '', '', '', '2024-09-11 09:41:34');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13048, 'https://media.huynhhieutravel.com/3-fog.png', '', '', '', '2024-09-11 09:41:31');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13047, 'https://media.huynhhieutravel.com/2-Mountain.png', '', '', '', '2024-09-11 09:41:24');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (13046, 'https://media.huynhhieutravel.com/0-Background.png', '', '', '', '2024-09-11 09:41:16');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12986, 'https://media.huynhhieutravel.com/phong-cach-hoc-tap-va-quy-trinh-trai-nghiem-kolb.jpg', '', '', '', '2024-09-07 03:55:48');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12974, 'https://media.huynhhieutravel.com/mau-ke-hoach-hoi-thao.jpg', '', '', '', '2024-09-07 03:55:38');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12971, 'https://media.huynhhieutravel.com/anh-minh-hoa-hoc-kien-thuc-moi.jpg', '', '', '', '2024-09-07 03:55:35');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12964, 'https://media.huynhhieutravel.com/lam-sao-vuot-qua-bay-tu-tin.jpg', 'Làm sao vượt qua bẫy tự tin', 'Làm sao vượt qua bẫy tự tin', 'Làm sao vượt qua bẫy tự tin', '2024-09-06 21:38:38');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12961, 'https://media.huynhhieutravel.com/cold-traffic-la-gi.jpg', 'Cold Traffic là gì?', 'Cold Traffic là gì?', 'Cold Traffic là gì?', '2024-09-06 21:36:10');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12946, 'https://media.huynhhieutravel.com/line.png', '', '', '', '2024-09-06 21:33:47');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12937, 'https://media.huynhhieutravel.com/khi-khong-la-tu-yeu-thich-cua-sep.jpg', 'Khi không là từ yêu thích của sếp', 'Khi không là từ yêu thích của sếp', 'Khi không là từ yêu thích của sếp', '2024-09-06 21:32:28');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12848, 'https://media.huynhhieutravel.com/checklist-audit-onpage-cho-seo.jpg', 'Checklist audit onpage cho SEO', 'Checklist audit onpage cho SEO', 'Checklist audit onpage cho SEO', '2024-09-06 21:08:26');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12843, 'https://media.huynhhieutravel.com/vi-du-ve-trinh-chinh-sua-bang-pivot-google-sheet.jpg', '', '', '', '2024-09-06 20:55:02');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12842, 'https://media.huynhhieutravel.com/vi-du-ve-bang-pivot-cua-google-sheet.jpg', 'Ví dụ về bảng Pivot của Google Sheet', 'Ví dụ về bảng Pivot của Google Sheet', 'Ví dụ về bảng Pivot của Google Sheet', '2024-09-06 20:54:28');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12839, 'https://media.huynhhieutravel.com/vi-du-ham-if-long-nhau.jpg', 'Ví dụ hàm IF lồng nhau', 'Ví dụ hàm IF lồng nhau', 'Ví dụ hàm IF lồng nhau', '2024-09-06 20:52:19');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12838, 'https://media.huynhhieutravel.com/vi-du-ham-if.jpg', 'Ví dụ về hàm IF', 'Ví dụ về hàm IF', 'Ví dụ về hàm IF', '2024-09-06 20:51:52');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12836, 'https://media.huynhhieutravel.com/sap-xep-du-lieu-google-sheet.jpg', 'Sắp xếp dữ liệu từ Google Sheet', 'Sắp xếp dữ liệu từ Google Sheet', 'Sắp xếp dữ liệu từ Google Sheet', '2024-09-06 20:50:23');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12835, 'https://media.huynhhieutravel.com/co-dinh-hang-hoac-cot-google-sheet.jpg', 'Cố định hàng hoặc cột Google Sheet', 'Cố định hàng hoặc cột Google Sheet', 'Cố định hàng hoặc cột Google Sheet', '2024-09-06 20:49:59');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12834, 'https://media.huynhhieutravel.com/dinh-dang-du-lieu-mau-xen-ke-google-sheet.jpg', 'Định dạng màu xen kẽ cho bảng dữ liệu trong Google Sheet', 'Định dạng màu xen kẽ cho bảng dữ liệu trong Google Sheet', 'Định dạng màu xen kẽ cho bảng dữ liệu trong Google Sheet', '2024-09-06 20:49:32');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12833, 'https://media.huynhhieutravel.com/dinh-dang-mau-du-lieu-de-de-nhin-hon.jpg', 'Định dạng màu dữ liệu để dễ nhìn hơn từ Google Sheet', 'Định dạng màu dữ liệu để dễ nhìn hơn từ Google Sheet', 'Định dạng màu dữ liệu để dễ nhìn hơn từ Google Sheet', '2024-09-06 20:48:47');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12832, 'https://media.huynhhieutravel.com/mau-du-lieu-ban-dau.jpg', 'Mẫu dữ liệu bài tập ban đầu (Google Sheet)', 'Mẫu dữ liệu bài tập ban đầu (Google Sheet)', 'Mẫu dữ liệu bài tập ban đầu (Google Sheet)', '2024-09-06 20:48:44');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12831, 'https://media.huynhhieutravel.com/Data-Mau-Bai-Tap.xlsx', 'Data-Mau-Bai-Tap', 'Data-Mau-Bai-Tap', '', '2024-09-06 20:47:21');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12816, 'https://media.huynhhieutravel.com/phan-tich-du-lieu-bang-google-sheet.jpg', 'Phân tích dữ liệu bằng Google Sheet', 'Phân tích dữ liệu bằng Google Sheet', 'Phân tích dữ liệu bằng Google Sheet', '2024-09-06 20:45:03');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12787, 'https://media.huynhhieutravel.com/bieu-do-nuoc-bien-dang.jpg', '', '', '', '2024-09-06 20:00:53');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12786, 'https://media.huynhhieutravel.com/bieu-do-so-sanh-cac-giong-cho.jpg', '', '', '', '2024-09-06 20:00:29');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12780, 'https://media.huynhhieutravel.com/cay-quuyet-dinh-su-dung-bieu-do-truc-quan.jpg', 'Cây quyết định sử dụng biểu đồ trực quan nào', 'Cây quyết định sử dụng biểu đồ trực quan nào', 'Cây quyết định sử dụng biểu đồ trực quan nào', '2024-09-06 19:50:27');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12778, 'https://media.huynhhieutravel.com/vi-du-bieu-do-tron-mo-ta-do-yeu-thich-ca-bo-phim.jpg', '', '', '', '2024-09-06 19:48:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12777, 'https://media.huynhhieutravel.com/vi-du-bieu-do-nhieu-so-luong-chuot-o-cac-thanh-pho.webp', '', '', '', '2024-09-06 19:48:43');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12776, 'https://media.huynhhieutravel.com/bieu-do-bar-so-sanh-2-xe-ban-ra.jpg', '', '', '', '2024-09-06 19:48:29');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12775, 'https://media.huynhhieutravel.com/vi-du-bieu-do-cot-luong-xe-ban.jpg', '', '', '', '2024-09-06 19:48:14');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12774, 'https://media.huynhhieutravel.com/vi-du-bieu-do-duong-ty-le-tot-nghiep.jpg', 'Ví dụ biểu đồ đường tỷ lệ tốt nghiệp', 'Ví dụ biểu đồ đường tỷ lệ tốt nghiệp', 'Ví dụ biểu đồ đường tỷ lệ tốt nghiệp', '2024-09-06 19:47:52');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12770, 'https://media.huynhhieutravel.com/vi-du-bieu-do-map.jpg', '', '', '', '2024-09-06 19:45:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12769, 'https://media.huynhhieutravel.com/vi-du-bieu-do-tron.jpg', '', '', '', '2024-09-06 19:45:43');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12768, 'https://media.huynhhieutravel.com/vi-du-bieu-do-duong.jpg', '', '', '', '2024-09-06 19:45:28');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12766, 'https://media.huynhhieutravel.com/vi-du-bieu-do-thanh.jpg', '', '', '', '2024-09-06 19:42:54');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12746, 'https://media.huynhhieutravel.com/chia-se-du-lieu-bang-nghe-thuat-truc-quan.jpg', 'Chia sẻ dữ liệu bằng nghệ thuật trực quan', 'Chia sẻ dữ liệu bằng nghệ thuật trực quan', 'Chia sẻ dữ liệu bằng nghệ thuật trực quan', '2024-09-06 19:38:16');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12715, 'https://media.huynhhieutravel.com/cay-quyet-dinh-xu-ly-du-lieu-loi.jpg', 'Cây quyết định xử lý dữ liệu lỗi', 'Cây quyết định xử lý dữ liệu lỗi', 'Cây quyết định xử lý dữ liệu lỗi', '2024-09-06 18:59:59');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12695, 'https://media.huynhhieutravel.com/khoa-hoc-xu-ly-va-lam-sach-du-lieu.jpg', 'Khóa học xử lý và làm sạch dữ liệu', 'Khóa học xử lý và làm sạch dữ liệu', 'Khóa học xử lý và làm sạch dữ liệu', '2024-09-06 18:51:19');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12682, 'https://media.huynhhieutravel.com/bang-vi-du-dan-so-cac-quoc-gia-qua-cac-nam.jpg', '', '', '', '2024-09-06 18:06:02');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12680, 'https://media.huynhhieutravel.com/vi-du-toan-tu-boolean.jpg', 'Ví dụ về toán tử Boolean', 'Ví dụ về toán tử Boolean', 'Ví dụ về toán tử Boolean', '2024-09-06 18:05:02');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12674, 'https://media.huynhhieutravel.com/cac-cap-do-mo-hinh-hoa-du-lieu.jpg', 'Các cấp độ mô hình hóa dữ liệu', 'Các cấp độ mô hình hóa dữ liệu', 'Các cấp độ mô hình hóa dữ liệu', '2024-09-06 17:58:05');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12672, 'https://media.huynhhieutravel.com/cac-loai-du-lieu-thong-dung.jpg', 'Các loại dữ liệu thông dụng', 'Các loại dữ liệu thông dụng', 'Các loại dữ liệu thông dụng', '2024-09-06 17:56:50');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12657, 'https://media.huynhhieutravel.com/chuan-bi-du-lieu-de-kham-pha.jpg', 'Khóa học chuẩn bị dữ liệu để khám phá', 'Khóa học chuẩn bị dữ liệu để khám phá', 'Khóa học chuẩn bị dữ liệu để khám phá', '2024-09-06 17:46:26');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12632, 'https://media.huynhhieutravel.com/bang-dieu-khien-phan-tich.jpg', 'Bảng điều phân tích Dashboard', 'Bảng điều phân tích Dashboard', 'Bảng điều phân tích Dashboard', '2024-09-06 16:15:55');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12631, 'https://media.huynhhieutravel.com/bang-dieu-khien-hoat-dong.jpg', 'Bảng điều hoạt động Dashboard', 'Bảng điều hoạt động Dashboard', 'Bảng điều hoạt động Dashboard', '2024-09-06 16:15:19');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12630, 'https://media.huynhhieutravel.com/bang-dieu-khien-chien-luoc-dashboard.jpg', 'Bảng điều khiển chiến lược Dashboard', 'Bảng điều khiển chiến lược Dashboard', 'Bảng điều khiển chiến lược Dashboard', '2024-09-06 16:14:45');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12617, 'https://media.huynhhieutravel.com/6-van-de-danh-cho-nha-phan-tich-du-lieu.jpg', '6 loại vấn đề của nhà phân tích dữ liệu', '6 loại vấn đề của nhà phân tích dữ liệu', '6 loại vấn đề của nhà phân tích dữ liệu', '2024-09-06 15:15:15');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12603, 'https://media.huynhhieutravel.com/dat-cau-hoi-hieu-qua-de-giai-quyet-van-de-dua-vao-du-lieu.jpg', 'Đặt câu hỏi để giải quyết vấn đề dựa vào dữ liệu', 'Đặt câu hỏi để giải quyết vấn đề dựa vào dữ liệu', 'Đặt câu hỏi để giải quyết vấn đề dựa vào dữ liệu', '2024-09-06 15:03:51');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12599, 'https://media.huynhhieutravel.com/8-giai-doan-vong-doi-du-lieu.jpg', '8 giai đoạn vòng đời dữ liệu', '8 giai đoạn vòng đời dữ liệu', '8 giai đoạn vòng đời dữ liệu', '2024-09-06 14:57:07');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12584, 'https://media.huynhhieutravel.com/khoa-hoc-nen-tang-phan-tich-du-lieu.jpg', 'Nền tảng phân tích dữ liệu', 'Nền tảng phân tích dữ liệu', 'Nền tảng phân tích dữ liệu', '2024-09-06 14:52:59');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12575, 'https://media.huynhhieutravel.com/tom-tat-gian-luoc-lich-su-cua-seo.jpg', 'Tóm tắt giản lược lịch sử của SEO', 'Tóm tắt giản lược lịch sử của SEO', 'Tóm tắt giản lược lịch sử của SEO', '2024-09-06 14:16:41');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12571, 'https://media.huynhhieutravel.com/mo-hinh-see-think-do-care.jpg', 'Mô hình See Think Do Care', 'Mô hình See Think Do Care', 'Mô hình See Think Do Care', '2024-09-06 14:13:51');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12568, 'https://media.huynhhieutravel.com/Internet-Archive.jpg', 'Internet Archive', 'Internet Archive', 'Internet Archive', '2024-09-06 14:05:30');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12567, 'https://media.huynhhieutravel.com/aol.jpg', 'AOL', 'AOL', 'AOL', '2024-09-06 14:05:05');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12566, 'https://media.huynhhieutravel.com/ecosia.jpg', 'Ecosia', 'Ecosia', 'Ecosia', '2024-09-06 14:04:46');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12565, 'https://media.huynhhieutravel.com/naver.jpg', 'Naver', 'Naver', 'Naver', '2024-09-06 14:03:46');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12564, 'https://media.huynhhieutravel.com/ask.jpg', 'Ask.com', 'Ask.com', 'Ask.com', '2024-09-06 14:03:24');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12563, 'https://media.huynhhieutravel.com/baidu.jpg', 'Baidu', 'Baidu', 'Baidu', '2024-09-06 14:02:51');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12562, 'https://media.huynhhieutravel.com/duckduckgo.jpg', 'DuckDuckGo', 'DuckDuckGo', 'DuckDuckGo', '2024-09-06 14:02:28');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12561, 'https://media.huynhhieutravel.com/yandex.jpg', 'Yandex', 'Yandex', 'Yandex', '2024-09-06 14:01:43');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12560, 'https://media.huynhhieutravel.com/yahoo.jpg', 'Yahoo', 'Yahoo', 'Yahoo', '2024-09-06 14:01:19');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12559, 'https://media.huynhhieutravel.com/bing.jpg', 'Bing', 'Bing', 'Bing', '2024-09-06 14:00:54');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12558, 'https://media.huynhhieutravel.com/google.jpg', 'Google', 'Google', 'Google', '2024-09-06 14:00:29');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12535, 'https://media.huynhhieutravel.com/trai-nghiem-nguoi-dung-va-thiet-ke-anh-huong-nhu-the-nao-voi-seo.jpg', 'Trải nghiệm người dùng và thiết kế ảnh hưởng như thế nào với SEO', 'Trải nghiệm người dùng và thiết kế ảnh hưởng như thế nào với SEO', 'Trải nghiệm người dùng và thiết kế ảnh hưởng như thế nào với SEO', '2024-09-06 13:34:49');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12534, 'https://media.huynhhieutravel.com/cac-chi-so-chinh-cua-website-ve-trai-nghiem-nguoi-dung.jpg', 'Các chỉ số chính website về trải nghiệm người dùng', 'Các chỉ số chính website về trải nghiệm người dùng', 'Các chỉ số chính website về trải nghiệm người dùng', '2024-09-06 13:32:27');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12532, 'https://media.huynhhieutravel.com/cac-chi-so-do-boi-PageSpeed-Insights.jpg', '', '', '', '2024-09-06 13:31:01');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12531, 'https://media.huynhhieutravel.com/PageSpeed-Insights-de-xuat-cac-giai-phap-cai-thien.jpg', '', '', '', '2024-09-06 13:30:59');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12530, 'https://media.huynhhieutravel.com/PageSpeed-Insights-chan-doan-cac-hieu-suat-cho-web.jpg', '', '', '', '2024-09-06 13:30:56');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12529, 'https://media.huynhhieutravel.com/truy-cap-PageSpeed-Insights-do-toc-do-web.jpg', '', '', '', '2024-09-06 13:26:56');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12528, 'https://media.huynhhieutravel.com/chi-so-cls.jpg', '', '', '', '2024-09-06 13:25:52');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12527, 'https://media.huynhhieutravel.com/chi-so-fid.jpg', '', '', '', '2024-09-06 13:25:50');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12526, 'https://media.huynhhieutravel.com/chi-so-lcp.jpg', '', '', '', '2024-09-06 13:25:49');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12522, 'https://media.huynhhieutravel.com/kiem-tra-url-404-tren-google-console.jpg', 'Kiểm tra URL 404 trên Google Console', 'Kiểm tra URL 404 trên Google Console', 'Kiểm tra URL 404 trên Google Console', '2024-09-06 10:44:06');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12521, 'https://media.huynhhieutravel.com/cach-tim-lien-ket-hong-trang-web-bang-google-console.jpg', '', '', '', '2024-09-06 10:43:49');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12520, 'https://media.huynhhieutravel.com/su-dung-ga4-de-xem-cac-duong-link-bi-hong-cua-website.jpg', '', '', '', '2024-09-06 10:43:31');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12516, 'https://media.huynhhieutravel.com/huong-dan-su-dung-google-console-cho-chuyen-vien-seo.jpg', 'Hướng dẫn sử dụng Google Console cho chuyên viên SEO', 'Hướng dẫn sử dụng Google Console cho chuyên viên SEO', 'Hướng dẫn sử dụng Google Console cho chuyên viên SEO', '2024-09-06 10:39:13');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12515, 'https://media.huynhhieutravel.com/chup-man-hinh-bao-cao-lien-ket-cua-google-console.jpg', '', '', '', '2024-09-06 10:38:24');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12514, 'https://media.huynhhieutravel.com/chup-man-hinh-bao-cao-hieu-suat-google-console.jpg', 'Chụp màn hình báo cáo hiệu suất Google Console', 'Chụp màn hình báo cáo hiệu suất Google Console', 'Chụp màn hình báo cáo hiệu suất Google Console', '2024-09-06 10:37:59');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12513, 'https://media.huynhhieutravel.com/4-loai-tim-kiem-google-console.jpg', '', '', '', '2024-09-06 10:37:41');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12512, 'https://media.huynhhieutravel.com/tim-kiem-cac-trang-thieu-hop-ly-de-su-dung-cho-cau-truc-chan-index.jpg', 'Bạn có thể khám phá ra các trang thiếu hợp lý để chặn nó trong các cấu trúc', 'Bạn có thể khám phá ra các trang thiếu hợp lý để chặn nó trong các cấu trúc', 'Bạn có thể khám phá ra các trang thiếu hợp lý để chặn nó trong các cấu trúc', '2024-09-06 10:37:17');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12511, 'https://media.huynhhieutravel.com/chup-man-hinh-phan-lap-chi-muc-trang-google-console.jpg', 'Chụp màn hình phần lập chỉ mục Trang Google Console', 'Chụp màn hình phần lập chỉ mục Trang Google Console', 'Chụp màn hình phần lập chỉ mục Trang Google Console', '2024-09-06 10:32:09');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12510, 'https://media.huynhhieutravel.com/bang-dieu-khien-console-phan-trang.jpg', '', '', '', '2024-09-06 10:24:02');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12504, 'https://media.huynhhieutravel.com/tim-tu-khoa-an-thit-voi-google-console.jpg', 'Tìm từ khóa ăn thịt với Google Console', 'Tìm từ khóa ăn thịt với Google Console', 'Tìm từ khóa ăn thịt với Google Console', '2024-09-06 10:02:19');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12503, 'https://media.huynhhieutravel.com/vi-du-ve-muc-dich-tim-kiem-google-la-su-hon-hop-cua-nguoi-dung.jpg', 'Ví dụ về mục đích tìm kiếm Google là sự hỗ hợp với người dùng', 'Ví dụ về mục đích tìm kiếm Google là sự hỗ hợp với người dùng', 'Ví dụ về mục đích tìm kiếm Google là sự hỗ hợp với người dùng', '2024-09-06 10:01:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12501, 'https://media.huynhhieutravel.com/su-dung-Answer-The-Public-de-nghien-cuu-tu-khoa.jpg', 'Sử dụng Answer The Public để nghiên cứu từ khóa', 'Sử dụng Answer The Public để nghiên cứu từ khóa', 'Sử dụng Answer The Public để nghiên cứu từ khóa', '2024-09-06 09:58:34');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12498, 'https://media.huynhhieutravel.com/cac-yeu-to-seo-onpage-quan-trong.jpg', 'Các yếu tố SEO Onpage quan trọng', 'Các yếu tố SEO Onpage quan trọng', 'Các yếu tố SEO Onpage quan trọng', '2024-09-06 09:55:25');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12492, 'https://media.huynhhieutravel.com/huong-dan-toan-dien-seo-onpage.jpg', 'Hướng dẫn toàn diện SEO Onpage cho người mới', 'Hướng dẫn toàn diện SEO Onpage cho người mới', 'Hướng dẫn toàn diện SEO Onpage cho người mới', '2024-09-06 09:51:11');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12474, 'https://media.huynhhieutravel.com/huong-dan-viet-blog-chuan-seo.jpg', 'Hướng dẫn viết Blog chuẩn SEO cho người mới bắt đầu', 'Hướng dẫn viết Blog chuẩn SEO cho người mới bắt đầu', 'Hướng dẫn viết Blog chuẩn SEO cho người mới bắt đầu', '2024-09-05 14:53:50');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12463, 'https://media.huynhhieutravel.com/edit-snippet-cua-rankmath.jpg', 'Edit Snippet của Rank Math', 'Edit Snippet của Rank Math', 'Edit Snippet của Rank Math', '2024-09-05 14:40:30');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12462, 'https://media.huynhhieutravel.com/phan-basic-seo-cua-rankmath.jpg', '', '', '', '2024-09-05 14:40:11');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12461, 'https://media.huynhhieutravel.com/ma-mau-chi-tiet-cac-seo-cua-rankmath.jpg', '', '', '', '2024-09-05 14:39:53');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12460, 'https://media.huynhhieutravel.com/anh-man-hinh-cach-dung-rankmath-seo-tu-khoa-buoc-dau-tien.jpg', '', '', '', '2024-09-05 14:39:31');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12458, 'https://media.huynhhieutravel.com/them-tieu-de-trong-wordpress.jpg', '', '', '', '2024-09-05 14:38:32');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12457, 'https://media.huynhhieutravel.com/vi-du-cau-truc-tieu-de-trong-wordpress.jpg', '', '', '', '2024-09-05 14:38:17');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12454, 'https://media.huynhhieutravel.com/tuy-chon-url-wordpress-mac-dinh-cho-bai-viet.jpg', '', '', '', '2024-09-05 14:36:01');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12453, 'https://media.huynhhieutravel.com/cau-truc-url.jpg', 'Cấu trúc URL', 'Cấu trúc URL', 'Cấu trúc URL', '2024-09-05 14:35:16');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12452, 'https://media.huynhhieutravel.com/vi-du-url.jpg', 'Ví dụ về URL', 'Ví dụ về URL', 'Ví dụ về URL', '2024-09-05 14:34:48');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12450, 'https://media.huynhhieutravel.com/the-mo-ta-reuters.jpg', '', '', '', '2024-09-05 14:33:14');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12449, 'https://media.huynhhieutravel.com/the-mo-ta-uber.jpg', '', '', '', '2024-09-05 14:32:53');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12448, 'https://media.huynhhieutravel.com/the-mo-ta-lego.jpg', '', '', '', '2024-09-05 14:32:37');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12447, 'https://media.huynhhieutravel.com/the-mo-ta-cua-airbnb.jpg', '', '', '', '2024-09-05 14:32:01');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12446, 'https://media.huynhhieutravel.com/minh-hoa-the-me-ta-meta-description.jpg', 'Minh họa thẻ Meta Description là gì', 'Minh họa thẻ Meta Description là gì', 'Minh họa thẻ Meta Description là gì', '2024-09-05 14:31:23');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12442, 'https://media.huynhhieutravel.com/chup-man-hinh-doan-trich-noi-bat-tu-khoa-phim-doanh-thu-cao-nhat-ngay-27-thang-9-nam-2023.jpg', 'Chụp màn hình đoạn trích nổi bật từ khóa phim doanh thu cao nhất ngày 27 tháng 9 năm 2023', 'Chụp màn hình đoạn trích nổi bật từ khóa phim doanh thu cao nhất ngày 27 tháng 9 năm 2023', 'Chụp màn hình đoạn trích nổi bật từ khóa phim doanh thu cao nhất ngày 27 tháng 9 năm 2023', '2024-09-05 14:23:33');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12439, 'https://media.huynhhieutravel.com/seo-la-gi.jpg', 'SEO là gì?', 'SEO là gì?', 'SEO là gì?', '2024-09-05 14:17:28');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12438, 'https://media.huynhhieutravel.com/tour-dien-taylor-swift-thanh-cong-nhu-the-nao-ket-qua-ngay-27-thang-9.jpg', 'Ảnh màn hình Tour diễn Taylor Swift thành công như thế nào ngày 27 tháng 9 năm 2023', 'Ảnh màn hình Tour diễn Taylor Swift thành công như thế nào ngày 27 tháng 9 năm 2023', 'Ảnh màn hình Tour diễn Taylor Swift thành công như thế nào ngày 27 tháng 9 năm 2023', '2024-09-05 14:17:25');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12436, 'https://media.huynhhieutravel.com/vung-an-toan-trong-hoc-tap.jpg', 'Vùng an toàn trong học tập', 'Vùng an toàn trong học tập', 'Vùng an toàn trong học tập', '2024-09-05 14:13:41');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12435, 'https://media.huynhhieutravel.com/vi-du-blocking-time-google-lich.jpeg', 'Ví dụ Blocking Time với Google Lịch', 'Ví dụ Blocking Time với Google Lịch', 'Ví dụ Blocking Time với Google Lịch', '2024-09-05 14:13:38');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12418, 'https://media.huynhhieutravel.com/canvas-van-hoa.jpg', 'Canvas văn hóa doanh nghiệp', 'Canvas văn hóa doanh nghiệp', 'Canvas văn hóa doanh nghiệp', '2024-09-05 13:51:32');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12417, 'https://media.huynhhieutravel.com/canvas-xac-dinh-muc-dich-kinh-doanh.jpg', 'Canvas xác định mục đích kinh doanh', 'Canvas xác định mục đích kinh doanh', 'Canvas xác định mục đích kinh doanh', '2024-09-05 13:50:01');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12410, 'https://media.huynhhieutravel.com/mau-team-canvas-mo-rong.jpg', 'Mẫu team canvas mở rộng', 'Mẫu team canvas mở rộng', 'Mẫu team canvas mở rộng', '2024-09-05 13:33:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12409, 'https://media.huynhhieutravel.com/huong-dan-dung-team-canvas.jpg', 'Hướng dẫn sử dụng team Canvas', 'Hướng dẫn sử dụng team Canvas', 'Hướng dẫn sử dụng team Canvas', '2024-09-05 13:33:55');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12408, 'https://media.huynhhieutravel.com/mau-team-canvas-can-ban.jpg', 'Mẫu team Canvas căn bản', 'Mẫu team Canvas căn bản', 'Mẫu team Canvas căn bản', '2024-09-05 13:33:52');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12396, 'https://media.huynhhieutravel.com/ky-thuat-va-phuong-phap-giai-quyet-van-de.jpg', 'Kỹ thuật và phương pháp giải quyết vấn đề', 'Kỹ thuật và phương pháp giải quyết vấn đề', 'Kỹ thuật và phương pháp giải quyết vấn đề', '2024-09-05 13:18:57');
INSERT OR IGNORE INTO Media (id, url, caption, description, altText, createdAt) VALUES (12391, 'https://media.huynhhieutravel.com/phuong-phap-who-what-when-matrix.jpg', 'Phương pháp Who What When matrix', 'Phương pháp Who What When matrix', 'Phương pháp Who What When matrix', '2024-09-05 10:39:19');