INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1438, 'Trải nghiệm tuyệt vời ở Hội trại Tuổi trẻ Phật giáo 2018', 'trai-nghiem-tuyet-voi-o-hoi-trai-tuoi-tre-phat-giao-2018', '<p>Hội trại Tuổi trẻ Phật giáo 2018 là một khóa tu tập được diễn ra vào hè tháng 7 trong 3 ngày. Đặc biệt, tôi đã có một trải nghiệm tuyệt vời ở Hội trại Tuổi trẻ Phật giáo năm 2018 với lần tổ chức thứ 13 này. Tôi cùng với hơn 1000 trại sinh khác đã sinh hoạt, vui chơi và học tập giáo lý Phật giáo đầy ý nghĩa. Chúng tôi đã có những buổi trò chuyện tuyệt vời về chủ đề Tuổi Thanh Xuân của kỳ hội trại năm nay. Nó không hẳn là một chuyến học tập về tôn giáo nữa, mà gần như là một hành trình du lịch tuyệt vời của tôi. Tôi đã được lắng sâu lòng mình trong thiền định, được bùng nổ cùng hơn 1000 bạn thanh thiếu niên từ 14 đến 32 tuổi. Hãy cùng tôi tìm hiểu, hội trại này có gì đặc biệt mà lại thu hút nhiều bạn trẻ tham gia đến vậy?</p>
<h2>Tôi đã tham gia Hội trại Tuổi trẻ Phật giáo lần thứ 13</h2>
<p>Tôi may mắn được đồng hành cùng Hội trại Tuổi trẻ Phật giáo lần thứ 13 này khi là một trong những trại sinh cuối cùng đăng ký. Nó đã kết thúc sớm hơn hạn chót đăng ký vì có quá nhiều đơn nộp online đăng ký. Chi tiết về hội trại:</p>
<blockquote class="wp-embedded-content" data-secret="A62FSal1Gm"><p><a href="https://huynhhieutravel.com/hoi-trai-tuoi-tre-phat-giao/">Hội Trại Tuổi Trẻ Phật Giáo 2018 | Tuổi Thanh Xuân</a></p></blockquote>
<p><iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="position: absolute; clip: rect(1px, 1px, 1px, 1px);" title="&#8220;Hội Trại Tuổi Trẻ Phật Giáo 2018 | Tuổi Thanh Xuân&#8221; &#8212; Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/hoi-trai-tuoi-tre-phat-giao/embed/#?secret=qELR9oCeXD#?secret=A62FSal1Gm" data-secret="A62FSal1Gm" width="600" height="338" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></p>
<h3>Hãy nghỉ lại một đêm ở chùa Vĩnh Nghiêm nếu bạn ở xa</h3>
<p>Hơn 1000 người tham gia sẽ được chia đều thành 4 cụm trại khác nhau với các tên gọi: Thanh Tịnh, Từ Bi, Trí Tuê và Tinh Tấn. Mỗi tiểu trại lại được đánh số từ 1 đến 9 với mỗi trại từ 20 đến hơn 25 trại sinh. Mỗi tiểu trại như vậy sẽ được phân cho một Tiểu trại trưởng để quản lý và kết nối các trại sinh. Tôi may mắn được đồng hành cùng một bạn nữ Tiểu trại trưởng tuyệt vời.</p>
<p><figure id="attachment_1418" aria-describedby="caption-attachment-1418" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1418" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-211.jpg" alt="Cụm Thanh Tịnh ở buổi thuyết giảng" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-211.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-211-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1418" class="wp-caption-text">Cụm Thanh Tịnh</figcaption></figure></p>
<p>Vì nhà tôi cách trung tâm Thành phố Hồ Chí Minh khá xa nên Tiểu trại trưởng khuyên tôi nên ngủ lại chùa 1 đêm để sáng xuất phát sớm. Đó là một quyết định sáng suốt. Với thời gian xuất phát là 3h sáng, bạn cần một đêm nghỉ ngơi đủ giấc cho chuyến đi xa. Nó cũng sẽ an toàn hơn khi bạn không cần di chuyển trong đêm giữa lòng thành phố.</p>
<p>Ngủ ở chùa tuy có hơi gọi là bất tiện. Nhưng tôi đã hoàn toàn bỏ ngoài hết sự bất tiện đó bởi sự nhiệt tình của các bạn trại sinh khác. Bạn đến sớm trước thời gian đóng cổng của chùa là 22h, bạn sẽ có thời gian giao lưu tuyệt vời cùng những trại sinh khác. Đó có thể là những câu chuyện vui, làm quen cùng nhau. Cũng có thể là những trận ma sói khởi đầu cho 3 ngày tiếp theo.</p>
<p><figure id="attachment_1361" aria-describedby="caption-attachment-1361" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1361" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo154.jpg" alt="Các bạn trại sinh ở chùa Vĩnh Nghiêm" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo154.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo154-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1361" class="wp-caption-text">Các bạn trại sinh ở chùa Vĩnh Nghiêm</figcaption></figure></p>
<p>Có thêm một buổi ngắn tìm hiểu trước sẽ giúp bạn thân thiết với trại sinh khác hơn trong hành trình 3 ngày Hội trại tiếp theo. Hãy đừng khép mình lại, hòa đồng và nói chuyện nhiều hơn. Bạn sẽ được những Tiểu trại trưởng giúp đỡ trong việc kết nối các trại sinh lại với nhau.</p>
<p>Sau khi thức giấc và vệ sinh, tôi lên xe, bắt đầu hành trình từ trung tâm Quận 3, TP. Hồ Chí MInh đến TP. Phan Thiết thuộc tỉnh Bình Thuận. Bắt đầu hành trình Hội trại Tuổi trẻ Phật giáo 2018</p>
<h3>Cứ tham quan du lịch địa phương trước đã</h3>
<p>Điểm đầ (TRUNCATED)', 'post', '2023-01-01 00:00:00', '2023-01-01 00:00:00');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1438, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1438, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1438, 187);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1438, 297);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1433, 'Hơn 1000 bạn trẻ tham dự Hội trại Tuổi trẻ Phật Giáo ở Phan Thiết', '1000-ban-tre-du-hoi-trai-tuoi-tre-phat-giao', '<p>Ngày 20 tháng 7 năm 2018, Ban hướng dẫn phật tử tỉnh Bình Thuận phối hợp cùng ban hướng dẫn phật tử Trung ương chính thức khai mạc ngày Hội trại Tuổi trẻ Phật giáo ở Phan Thiết năm 2018 lần thứ 13 với chủ đề &#8220;Tuổi Thanh Xuân&#8221;. Hội trại được tổ chức trong 3 ngày 2 đêm từ ngày 20 đến ngày 23 tháng 7 năm 2018. Ngày hội diễn ra thành công rực rỡ với hơn 1000 bạn thanh thiếu niên tham dự.</p>
<p><figure id="attachment_1241" aria-describedby="caption-attachment-1241" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1241" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo34.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo34.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo34-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1241" class="wp-caption-text">Hơn 1000 trại sinh ở Hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p>Hội trại Tuổi trẻ Phật giáo với sự tham gia của hơn 1000 bạn từ độ tuổi 14 đến 32 tuổi ở đủ mọi miền tổ quốc và cả những trại sinh quốc tế đến từ Singapore, Thái Lan, Hàn Quốc,&#8230; Đây là những thanh thiếu niên nhiệt tình và đầy hoài bão với tuổi trẻ thanh xuân cống hiến cho tổ quốc và làm những điều đẹp đẽ cho cuộc sống.</p>
<p><iframe src="https://www.youtube.com/embed/MxqOo2ui1eg" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>ĐĐ.Thích An Đạt, Phó ban kiêm Chánh Thư ký Ban Tổ chức Hội trại chia sẽ: “Hội trại lần này với mong muốn tuổi trẻ phải trọn vẹn trong từng hơi thở tuổi thanh xuân, tràn đầy yêu thương an vui. Đồng thời tạo một môi trường tham quan và vui chơi trong mùa hè, giúp các bạn giải tỏa stress sau những ngày học tập và làm việc căng thẳng. Bạn sẽ có những phút giây tuyệt vời bên ánh lửa trại đêm khuya với bạn bè bốn phương, sáng sớm ngồi tĩnh lặng nghe sóng vỗ và ngắm mặt trời lên, bước những bước thảnh thơi mà trước mặt là biển cả bao la”.</p>
<p>Chi tiết Thông tin Hội Trại:</p>
<blockquote class="wp-embedded-content" data-secret="nKBOFpLLE9"><p><a href="https://huynhhieutravel.com/hoi-trai-tuoi-tre-phat-giao/">Hội Trại Tuổi Trẻ Phật Giáo 2018 | Tuổi Thanh Xuân</a></p></blockquote>
<p><iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="position: absolute; clip: rect(1px, 1px, 1px, 1px);" title="&#8220;Hội Trại Tuổi Trẻ Phật Giáo 2018 | Tuổi Thanh Xuân&#8221; &#8212; Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/hoi-trai-tuoi-tre-phat-giao/embed/#?secret=CyzSgexJRM#?secret=nKBOFpLLE9" data-secret="nKBOFpLLE9" width="600" height="338" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></p>
<h2>Hướng đến chân, thiện, mỹ trong giáo lý Phật pháp</h2>
<p>Hội trại với nhiều hoạt động nổi bật hướng giới trẻ đến chân, thiện, mỹ. Hội trại tổ chức với nhiều hoạt động ý nghĩa về Phật pháp khác nhau như: Đốt hoa đăng cầu nguyện, buổi thuyết giảng và tụng kinh cầu nguyện, thiền định, thi phật pháp,&#8230;</p>
<p><figure id="attachment_1425" aria-describedby="caption-attachment-1425" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1425" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-218.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-218.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-218-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1425" class="wp-caption-text">Một trại sinh đặt câu hỏi về Phật pháp trong Hội Trại</figcaption></figure></p>
<p>Đặc biệt Hội trại Tuổi trẻ Phật giáo còn đưa ra nhiều hoạt động sinh hoạt tích cực cho giới trẻ. Những trò chơi lớn, nhỏ, tham quan hội trại và sinh hoạt thú vị cùng nhau. Những bạn trẻ sẽ có thời gian lắng động và sôi nổi với tuổi thanh xuân của mình.</p>
<p><figure id="attachment_1263" aria-describedby="caption-attachment-1263" style="width: 987px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1263 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo56.jpg" alt="Hội trại tuổi trẻ phật giáo ở Phan Thiết" width="987" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo56.jpg 987w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo56-768x477.jpg 768w" sizes="(max-width: 987px) 100vw, 987px" /><figcaption id="caption-attachment-1263" class="wp-caption-text">Không khí vui tươi ở Hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p>Những hoạt động vui tươi diễn ra vô cùng náo nhiệt nhưng cũng vô cùng kỷ luật. Các bạn trẻ học tập đức tính tốt từ giáo lý nhà Phật, vừa hòa mình cùng thiên nhiên, vừa sôi nổi cùng tuổi thanh xuân rực rỡ của mình.</p>
<p><figure id="attachment_1395" aria-describedby="caption-attachment-1395" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1395 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo188.jpg" alt="Tình nguyện viên vui vẻ nhảy cùng nhau" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo188.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo188-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1395" class="wp-caption-text">Tình nguyện viên vui vẻ nhảy cùng nhau</figcaption></figure></p>
<p>Tại lễ khai mạc, ban tổ chức đã gửi tặng những quà tặng kỷ niệm đến những tình nguyện viên đã đóng góp công sức của mình cho một kỳ Hội trại thành công.</p>
<p><figure id="attachment_1343" aria-describedby="caption-attachment-1343" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1343 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo136.jpg" alt="Ban quản trại của hội trại tuổi trẻ phật giáo lần thứ 13" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo136.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo136-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1343" class="wp-caption-text">Ban quản trại của hội trại tuổi trẻ phật giáo lần thứ 13</figcaption></figure></p>
<h2>Một kỳ Hội trại tuổi trẻ Phật giáo ở Phan Thiết thành công</h2>
<p>Trước đó một ngày hơn 1000 trại sinh đã hòa mình và lắng đọng với chương trình Đêm Yêu Thương với chủ đề Tuổi Thanh Xuân. Các bạn trẻ đã trải nghiệm, chia sẽ những dòng lưu ký về tuổi thanh xuân của mình. Tuổi thanh xuân với những chuyện gia đình, những lo ưu về tương lai hay những trải nghiệm về một tuổi thơ tuyệt vời.</p>
<p><figure id="attachment_1420" aria-describedby="caption-attachment-1420" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1420 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-213.jpg" alt="Trại sinh viết thư gửi yêu thương với chủ đề tuổi thanh xuân" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-213.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-213-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1420" class="wp-caption-text">Trại sinh viết thư gửi yêu thương với chủ đề tuổi thanh xuân</figcaption></figure></p>
<p>Hội trại sẽ được tiếp tục diễn ra vào năm sau vào thời gian tháng 7, hãy cùng đón chờ kỳ hội trại 14 vào năm 2019 bạn nhé!</p>
<p><iframe src="https://www.youtube.com/embed/6c1puPinnP4" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
', 'Ngày 20 tháng 7 năm 2018, Ban hướng dẫn phật tử tỉnh Bình Thuận phối hợp cùng ban hướng dẫn phật tử Trung ương chính thức khai mạc ngày Hội trại Tuổi trẻ Phật giáo ở Phan Thiết năm 2018 lần thứ 13 với chủ đề &#8220;Tuổi Thanh Xuân&#8221;. Hội trại được tổ chức trong [&hellip;]', 1347, 'post', '2018-08-02 09:51:07', '2023-04-23 12:25:52');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1433, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1433, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1433, 187);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1433, 297);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1430, 'Hội Trại Tuổi Trẻ Phật Giáo 2018 | Tuổi Thanh Xuân', 'hoi-trai-tuoi-tre-phat-giao', '<p>Hội trại tuổi trẻ Phật giáo là một chương trình trại hè tổ chức hằng năm dành cho lứa tuổi thanh thiếu niên. Năm nay với chủ đề Tuổi Thanh Xuân tổ chức ở Phan Thiết là kỳ hội trại thứ 13. Đây là một cơ hội để các bạn trẻ chiêm nghiệm lại và viết tiếp một hành trình thanh xuân của tuổi trẻ. Ngoài là một sân chơi dành cho tuổi trẻ, nơi đây còn là một nơi gieo mầm hạt giống Phật pháp đến cho tuổi trẻ. Nơi đây ngoài các trò chơi vận động, giao lưu với hơn 1000 bạn trẻ. Nó còn là những buổi thiền định, những bài giảng Phật pháp chân thực vào đời sống tuổi trẻ. Bạn sẽ còn được học cách ngồi thiền, hít vào thở ra đúng cách, tái tạo năng lượng và thanh lọc những năng lượng tiêu cực từ cơ thể.</p>
<p><iframe src="https://www.youtube.com/embed/MxqOo2ui1eg" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h2>Nguồn gốc Hội trại tuổi trẻ Phật giáo</h2>
<p>Kỳ hội trại tuổi trẻ Phật giáo đầu tiên được tổ chức tại bãi biển Lộc An, Bà Rịa &#8211; Vũng Tàu. Chủ đề: &#8220;Đến vui về nhớ&#8221;. Ban đầu Hội trại được ban hướng dẫn Phật tử trung ương tổ chức. Sau này được tách ra và kết hợp vào các tỉnh khác nhau để tổ chức ở nhiều địa điểm.</p>
<p>Đến năm 2018, với kỳ Hội trại tuổi trẻ Phật Giáo được tổ chức ở Phan Thiết là kỳ thứ 13 và cũng là 13 năm trải qua hoạt động.</p>
<p align="left">“Sự thành công của hội trại không nằm ở sự điều động của ban tổ chức mà nằm ở sự tự giác, đồng điệu trong tâm hồn các trại sinh. Hãy học tập đức tính tốt được định hình bởi giáo lý đạo Phật, hoà mình với thiên nhiên, kết nối bạn bè khắp nơi để học tập cái hay, cái tốt của nhau” &#8211; HT.Thích Chơn Không gửi gắm đến các bạn trẻ.</p>
<h2>Những chương trình của Hội trại tuổi trẻ Phật giáo</h2>
<p>&#8211; <strong>Hội thi Phật pháp, giảng thuyết về chủ đề</strong>: Bạn sẽ có một hội thi Rung Chuông Chùa vui nhộn. Một bài thuyết giảng khoảng 1 giờ với chủ đề chính từ những vị thầy Đại Đức hoặc Hòa Thượng đáng kính.</p>
<p>&#8211; <strong>Đêm yêu thương</strong>: Đó là giây phút lắng lòng cùng những yêu thương đến cha mẹ, bạn bè. Hoa đăng được thắp lên, truyền lửa từng trại sinh. Mọi người sẽ độc hồi kinh cầu an đến người thân yêu của mình.<br />
<iframe src="https://www.youtube.com/embed/VZiUZsnIDhM" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>&#8211; <strong>Ngày dựng trại và sinh hoạt</strong>: Các bạn sẽ có những khoảnh khắc trang trí trại cùng nhau. Những tiểu trại được trang trí với nhiều màu sắc và hình dáng khác nhau theo từng ý tưởng đặt ra từ chính bạn. Mỗi tiểu trại bao gồm khoảng 20 trại sinh sẽ sinh hoạt cùng một lều tự trang trí.<br />
<iframe src="https://www.youtube.com/embed/jHna-lcA7Eo" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>&#8211; <strong>Trò chơi nhỏ</strong>: Toàn thể hội trại chia ra làm 4 cụm, mỗi cụm sẽ có các tiểu trại với tên gọi: Từ Bi, Tinh Tấn, Trí Tuệ, Thanh Tịnh theo số thứ tự. Trò chơi nhỏ tập họp các trò chơi để tiểu trại ganh đua nhau và &#8220;quẩy&#8221; cùng nhau.<br />
<iframe src="https://www.youtube.com/embed/dFF-kyfrUZk" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>&#8211; <strong>Tham quan địa điểm trại</strong>: Mỗi năm Hội trại tiểu trẻ Phật giáo đều tổ chức ở mỗi địa điểm khác nhau. Các bạn sẽ được tham quan tự do địa điểm. Đó có thể là tắm biển, hoặc leo núi tùy vào địa điểm tham quan.<br />
<iframe src="https://www.youtube.com/embed/qUT5IIlO4u0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>&#8211; <strong>Đêm lửa trại</strong>: Đây là một đêm náo nhiệt nhất. Các bạn sẽ tập họp trình diễn những tiết mục văn nghệ được chọn lọc sau khi thi. Mọi người sẽ được lắng nghe những khách mời là những ca sĩ nổi tiếng trong các cuộc thi The Voice hay Việt Nam Idols. Đặc biệt thực đơn chính là màn đốt lửa trại, mọi người quây quần hát ca. Cùng nhau chơi những trò chơi nhỏ trong lửa trại.<br />
<iframe src="https://www.youtube.com/embed/DVAfig89OCU" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>&#8211; <strong>Thiền định</strong>: Sáng hôm sau mọi người sẽ thức sớm. Những bậc Đại Đức hoặc Hòa Thượng sẽ hướng dẫn các bạn thiền định trong. Thiền định để tâm hồn nhẹ nhàng, tập trung năng lượng và loại bỏ tạp niệm. Các bạn sẽ được đi bộ nhẹ nhàng xung quanh khu đất trại. Đó có thể là chuyến đi dọc bờ biển hoặc đi dọc theo những ngọn đồi tùy địa điểm.<br />
<iframe src="https://www.youtube.com/embed/eBvyONPRdjM" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>&#8211; <strong>Trò chơi lớn</strong>: Các bạn sẽ được chia thành 4 cụm trại và chơi những trò chơi lớn theo team building. Những trò chơi tạo sự đoàn kết và vô cùng gay cấn. Hội Trại hàng năm được tổ chức vào tuần thứ 3 của tháng 7 dương lịch.<br />
<iframe src="https://www.youtube.com/embed/xmo-7k9GvZs" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h3>Những kỳ Hội trại tuổi trẻ Phật giáo từng được tổ chức</h3>
<p>1. Hội trại Tuổi trẻ Phật giáo lần I &#8211; năm 2006 tại bãi biển Lộc An, Bà Rịa &#8211; Vũng Tàu. Chủ đề: &#8220;Đến vui về nhớ&#8221;.</p>
<p>2. Hội trại Tuổi trẻ Phật giáo lần II &#8211; năm 2007 tại Khu du lịch Hồ Tràm, Bà Rịa &#8211; Vũng Tàu. Chủ đề: “Sống trọn niềm vui”.</p>
<p>3. Hội trại Tuổi trẻ Phật giáo lần III &#8211; năm 2008 tại khu du lịch Thác Giang Điền, Đồng Nai. Chủ đề: “Niềm tin cuộc sống”.</p>
<p>4. Hội trại Tuổi trẻ Phật giáo lần IV &#8211; năm 2009 tại khu du lịch Thác Giang Điền, Đồng Nai. Chủ đề: “Mãi mãi một niềm vui”.</p>
<p>5. Hội trại Tuổi trẻ Phật giáo lần V &#8211; năm 2010 tại khu du lịch Minh Trí, Xuyên Mộc, Bà Rịa &#8211; Vũng Tàu. Chủ đề: “Hội tụ khát vọng”.</p>
<p>6. Hội trại Tuổi trẻ Phật giáo lần VI &#8211; năm 2011 tại khu du lịch Vườn Xoài, TP. Biên Hòa, Đồng Nai. Chủ đề: “Tiếp bước an vui”.</p>
<p>7. Hội trại Tuổi trẻ Phật giáo lần VII &#8211; năm 2012 tại khu du lịch Madagui, Lâm Đồng. Chủ đề: “Kết nối yêu thương”.</p>
<p>8. Hội trại Tuổi trẻ Phật giáo lần VIII &#8211; năm 2013 tại khu du lịch Paraside, TP. Vũng Tàu. Chủ đề “Khơi nguồn an lạc”.</p>
<p>9. Hội trại Tuổi trẻ Phật giáo lần IX &#8211; năm 2014 tại KDL Kawasami, Long Hải, tỉnh Bà Rịa Vũng Tàu. Chủ đề “Sáng mãi niềm tin”.</p>
<p>10. Hội trại Tuổi trẻ Phật giáo lần X &#8211; năm 2015 tại KDL Đambri, TP. Bảo Lộc, tỉnh Lâm Đồng với chủ đề &#8220;Khát vọng bay cao&#8221;.</p>
<p>11- Hội trại tuổi trẻ phật giáo lần thứ XI năm 2016 tại Ocean Dunes Resort, TP. Phan Thiết Chủ đề “Khơi nguồn yêu thương”.</p>
<p>12. Hội trại Tuổi trẻ Phật giáo lần XII- 2017 tại khu Zenna Pool Camp, huyện Long Điền và chùa Đại Tòng Lâm, huyện Tân Thành, tỉnh BRVT. Chủ đề “Sống tử tế”.</p>
<p>13 – Hội trại Tuổi trẻ Phật giáo lần thứ XIII năm 2018 tại Chùa Bửu Sơn và Khu du lịch Bồng lai TP Phan Thiết chủ đề “Tuổi thanh xuân”.</p>
<h3>Từ quá trình chuẩn bị kỳ công trước 3 tháng</h3>
<p>Đại đức Thích An Đạt &#8211; Linh hồn của Hội trại hàng năm, là người đứng sau chỉ huy các kỳ hội trại tâm sự:</p>
<p><em>&#8220;Đó là thời gian của việc đi tìm địa điểm, lên kế hoạch, xin phép nhà chức trách, tính toán kinh phí, xin tài trợ bằng những chuyến đi tiền trạm biền biệt, bất kể ngày đêm, nắng mưa của đất trời.</em></p>
<p><em>Đó là thời gian thông báo, tuyển tình nguyên viên, tập huấn, họp hành, phân công nhiệm vụ, giám sát và thảo luận các ý tưởng với anh, chị Ban quản trại.</em></p>
<p><img loading="lazy" decoding="async" class="size-full wp-image-1372" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo165.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo165.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo165-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /></p>
<p>Đại Đức Thích An Đạt phát biểu</p>
<p><em>Đó là thời gian vận động đầu này đầu kia để đủ kinh phí, vật dụng tổ chức, tính toán chuyện xe cộ, an ninh nơi đất trại, các điều kiện cần thiết đảm bảo cho sinh hoạt hàng ngàn người lúc hội ngộ.</em></p>
<p><em>Đó còn là khoảng thời gian giải quyết các vấn đề phát sinh, làm đầu tàu và truyền lửa để những người cộng sự cùng nhìn về một hướng, quyết tâm, chung sức chung lòng làm nên những điều kì diệu nơi đất trại để trại sinh được tận hưởng không khí trại trọn vẹn nhất.&#8221;</em></p>
<p><figure id="attachment_1240" aria-describedby="caption-attachment-1240" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1240" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo33.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo33.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo33-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1240" class="wp-caption-text">Rất nhiều con người đã tạo nên một kỳ hội trại thành công</figcaption></figure></p>
<h4><em><strong>Kỳ hội trại tuổi trẻ Phật giáo được hình thành từ:</strong></em></h4>
<p>Ban quản trại phải chạy đôn chạy đáo tìm những tình nguyện viên, huy động những nguồn lực cho Hội Trại.</p>
<p>Hàng chục tiểu trại trưởng làm việc với những quy trình, quy định nghiệm ngặt. Họ phải trải qua những cuối tuần tập huấn khắc khe từ hội trại. Những việc quản lý trại sinh, cách sinh hoạt cho đến những việc liên quan lịch trình đi hội trại và liên hệ ban tổ chức khi hội trại bắt đầu.</p>
<p><figure id="attachment_1210" aria-describedby="caption-attachment-1210" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1210" src="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo3.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo3.jpg 920w, https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo3-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1210" class="wp-caption-text">Những bạn Tiểu trại trưởng trong hành trình Hội trại tuổi trẻ Phật giáo</figcaption></figure></p>
<p>Những bạn team game phải lên những kế hoạch game khác nhau. Các bạn ấy trải qua những ngày nắng mưa trên đất trại để test game, mang đến niềm vui cho trại sinh trong thời tiết thất thường của tháng 6, tháng 7.</p>
<p>Những bạn team văn nghệ chuẩn bị sân khấu, lên kế hoạch chương trình. Từ khâu âm thanh đến hình ảnh phải là tuyệt vời nhất. Hay đến việc cầm cân nảy mực tuyển ra những tiết mục xuất sắc.</p>
<p><figure id="attachment_1299" aria-describedby="caption-attachment-1299" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1299" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo92.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo92.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo92-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1299" class="wp-caption-text">Những tiết mục văn nghệ được chuẩn bị kỹ lưỡng</figcaption></figure></p>
<p>Những bạn team y tế trực nhất 24/7 để phục vụ trại sinh và những tình nguyện viên.</p>
<p>Những bạn truyền thông phải cật lực làm việc quảng bá hội trại. Truyền tải những tấm hình, những thông điệp tốt nhất đến trại sinh và những bạn chưa phải là trại sinh.</p>
<p>Những bạn hậu cần, những cô chú nấu ăn phải cật lực thức đêm khuya chuẩn bị thức ăn cho hàng ngàn trại sinh. Những bữa ăn phải tự nấu với đầy đủ chuẩn mực về dinh dưỡng.</p>
<p>Những bạn trong ban kỷ lục phải luôn tuân thủ những điều kiện quản lý nghiệm ngặt. Tạo những sự bảo vệ từ bên trong lẫn bên ngoài cho trại sinh. Những bạn hy sinh về mặt hình ảnh phục vụ cho ngày hội trại.</p>
<p><figure id="attachment_1426" aria-describedby="caption-attachment-1426" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1426" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-219.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-219.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-219-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1426" class="wp-caption-text">Đại Đức Thích Trí Chơn nhận huy hiệu logo hội trại.</figcaption></figure></p>
<p>Ngoài ra còn rất nhiều bạn không để tên, làm những việc khác nhau phục vụ hội trại.</p>
<p>Với hơn 3 tháng làm việc cùng hơn 100 con người. Họ đã tạo nên một kỳ hội trại thành công với bao công sức đổ ra. Nhưng thành quả ấy mang lại vô cùng to lớn cho hơn 1000 con người với hạt mầm sống tốt được gieo trồng trong tâm hồn.</p>
<h2>Chủ đề tuyệt vời Tuổi Thanh Xuân với tuổi trẻ</h2>
<p>Tuổi trẻ không phải ai cũng sống với một thanh xuân rực rỡ đúng ý nghĩa. Chủ đề Hội trại năm 2018 với tựa đề Tuổi Thanh Xuân đã thật sự đánh đúng vào thực tại tâm hồn nhiều bạn trẻ. Bạn đã từng trải qua thanh xuân như thế nào hoặc thanh xuân tiếp theo của bạn là gì? Bạn sẽ dành những gì cho thanh xuân. Đây là chủ đề giáo dục giới trẻ và mang nhiều ý nghĩa Phật pháp gửi gắm vào nó.</p>
<p><figure id="attachment_1215" aria-describedby="caption-attachment-1215" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1215 size-full" src="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo8.jpg" alt="Thư gửi yêu thương tuổi thanh xuân" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo8.jpg 920w, https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo8-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1215" class="wp-caption-text">Thư gửi yêu thương tuổi thanh xuân</figcaption></figure></p>
<p><em><strong>Hội trại tuổi trẻ Phật giáo cũng là một phần trong dấu ấn thanh xuân</strong></em> của từng trại sinh. Khi đến với Hội trại các bạn ấy đã được trải qua một đêm yêu thương với những cơn mưa rào, những hoa đăng thắp sáng.</p>
<p><figure id="attachment_1225" aria-describedby="caption-attachment-1225" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1225" src="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo18.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo18.jpg 920w, https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo18-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1225" class="wp-caption-text">Hội Trại Tuổi Trẻ Phật Giáo</figcaption></figure></p>
<p>Những con người ấy đã cùng nhau đọc những bức thư đầy tâm tư và trải qua một đêm văn nghề đầy nụ cười và nước mắt.</p>
<p><figure id="attachment_1226" aria-describedby="caption-attachment-1226" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1226" src="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo19.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo19.jpg 920w, https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo19-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1226" class="wp-caption-text">Hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p>Những con người ấy đã cùng nhau trang trí nên những lều trại cực ngầu, cùng nhau chơi ma sói xuyên đêm. Hoặc là ngủ ngáy khò khò bên cạnh nhau. Sáng thức dậy đôi chân gác lên đầu người khác cũng là một cảm xúc khác lạ.</p>
<p><figure id="attachment_1373" aria-describedby="caption-attachment-1373" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1373 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo166.jpg" alt="Trại sinh hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo166.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo166-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1373" class="wp-caption-text">Trại sinh hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p>Những con người ấy đã trải qua một đêm văn nghệ với những tiết mục tuyệt vời: múa võ nhạc, dân vũ, những bài ca truyền cảm, những điệu nhảy dance tuyệt vời hay hai ca sĩ khách mời Bảo Anh (The Voice) và Phạm Anh Duy (The Voice).</p>
<p><figure id="attachment_1300" aria-describedby="caption-attachment-1300" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1300" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo93.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo93.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo93-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1300" class="wp-caption-text">Bảo Anh ở Hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p>Những con người ấy dù xa lạ hay thân thuộc đã cùng nhau nắm tay, bên nhau trong một đêm lửa trại tuyệt vời.</p>
<p><figure id="attachment_1303" aria-describedby="caption-attachment-1303" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1303 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo96.jpg" alt="Mọi người hân hoan bên lửa trại" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo96.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo96-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1303" class="wp-caption-text">Mọi người hân hoan bên lửa trại</figcaption></figure></p>
<p>Những con người ấy đã ngồi thiền cùng nhau trong cái nắng sớm với sương mai lúc 6h sáng. Họ cùng nhau đi nhẹ nhàng trên những bậc thềm, bãi cát hướng về bãi biển với ánh bình minh ló dạng.</p>
<p><figure id="attachment_1309" aria-describedby="caption-attachment-1309" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1309 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo102.jpg" alt="Trại sinh tập trung ngồi thiền ở hội trại" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo102.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo102-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1309" class="wp-caption-text">Trại sinh tập trung ngồi thiền ở hội trại</figcaption></figure></p>
<p>Họ cùng nhau xây dựng nên những khoảnh khác thanh xuân cùng nhau tuyệt vời.</p>
<h3>Chúng ta học được gì từ Hội trại tuổi trẻ Phật giáo</h3>
<h4><em><strong>Phật pháp nhiệm màu</strong></em></h4>
<p>Chúng ta sẽ được trải lòng với những lời dạy từ bậc Đại đức hay Hòa thượng. Những lý niệm Phật pháp truyền tải đến những bạn trẻ không phải hoàn toàn qua lý niệm. Mà là những buổi nói chuyện sâu sắc cùng nhau. Bạn cũng có thể trao đổi với nhau qua những câu hỏi.</p>
<p><figure id="attachment_1425" aria-describedby="caption-attachment-1425" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1425 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-218.jpg" alt="Một trại sinh hỏi về phật pháp trong hội trại" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-218.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-218-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1425" class="wp-caption-text">Một trại sinh hỏi về phật pháp trong hội trại</figcaption></figure></p>
<p>Bạn sẽ học được qua những buổi thiền định, đi bộ thanh tịnh vào buổi sáng. Học cách xả những năng lượng tiêu cực từ bên trong và hít và những điều tốt đẹp để cơ thể khỏe mạnh hơn.</p>
<h4><em><strong>Bài học tuổi thanh xuân</strong></em></h4>
<p>Bạn sẽ được trải nghiệm một tuổi trẻ rực rỡ và náo động từ những con người trẻ. Hòa mình vào những điều tuyệt vời với một năng lượng tích cực từ thanh xuân của bạn.</p>
<p><figure id="attachment_1412" aria-describedby="caption-attachment-1412" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1412 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-205.jpg" alt="Trại sinh vui vẻ ở Hội trại tuổi trẻ phật giáo phan thiết" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-205.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-205-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1412" class="wp-caption-text">Trại sinh vui vẻ ở Hội trại tuổi trẻ phật giáo phan thiết</figcaption></figure></p>
<p>Bạn được rèn luyện cơ thể với những trò chơi khác nhau từ trí tuệ đến thể xác. Bạn sẽ tập trung những giá trị tinh tế của mình cho những trò chơi lầy lội trong những trò chơi lớn và nhỏ.</p>
<p><figure id="attachment_1400" aria-describedby="caption-attachment-1400" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1400 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo193.jpg" alt="Trò chơi lớn" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo193.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo193-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1400" class="wp-caption-text">Trò chơi lớn</figcaption></figure></p>
<p>Bạn sẽ học được cách giao tiếp với những người xa lạ. Bạn sẽ biết cách đoàn kết để tạo nên một nguồn lực lớn lao hơn. Hãy cùng trại của mình dùng hết sức để đạt những phần thưởng hay đơn giản là được hết mình với tuổi trẻ trong 3 ngày 2 đêm.</p>
<p><figure id="attachment_1349" aria-describedby="caption-attachment-1349" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1349 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo142.jpg" alt="Trại sinh thể hiện sự đoàn kết" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo142.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo142-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1349" class="wp-caption-text">Trại sinh thể hiện sự đoàn kết</figcaption></figure></p>
<h4><em><strong>Cơ hội giao lưu cùng những người bạn cũ lẫn mới</strong></em></h4>
<p>Hội trại tuổi trẻ Phật giáo là những ngày lầy lội cùng hơn 1000 con người khác nhau. Bạn sẽ được ăn ngủ cùng 20 người trong một tiểu trại. Bạn sẽ cùng chơi game cùng hơn 1000 con người trong những cụm trại khác nhau bao gồm Tinh Tấn, Từ Bi, Trí Tuệ và Thanh Tịnh.</p>
<p><figure id="attachment_1347" aria-describedby="caption-attachment-1347" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1347" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo140.jpg" alt="Hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo140.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo140-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1347" class="wp-caption-text">Hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p>Bạn sẽ được nắm tay những người xa lạ, cùng trao những cái ôm nồng cháy tự nguyện. Bạn sẽ được nói nhiều hơn, cùng trò chuyện nhiều hơn cùng những người xa lạ. Đây cũng là cơ hội cho bạn tỏa sáng chính mình sau nhiều năm &#8220;chìm&#8221; đâu đó.</p>
<h4><em><strong>Đảm đang hơn với những &#8220;nghề&#8221; mới</strong></em></h4>
<p>Nói nghề thì hơi phóng đại. Nhưng chắc chắc bạn sẽ được học cách trang trí trại là thế nào: cùng đóng đinh, cột dây thun, thổi bong bóng, thắt chỉ. Hay đơn giản là những chuyện phục vụ ăn uống cho mình như gọt ổi, xoài, bưởi,&#8230; Nó sẽ khơi dậy những sự khéo léo tiềm ẩn trong bạn đã bị ngủ quên trong nhiều năm.</p>
<p><figure id="attachment_1253" aria-describedby="caption-attachment-1253" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1253 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo46.jpg" alt="Chuẩn bị trang trí trại" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo46.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo46-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1253" class="wp-caption-text">Chuẩn bị trang trí trại</figcaption></figure></p>
<h4><em><strong>Nó là một chuyến du lịch thú vị</strong></em></h4>
<p>Tại sao bạn không nghĩ nó là một chuyến du lịch thú vị nhĩ? Bạn được tham quan một địa điểm nổi tiếng. Mỗi năm hội trại sẽ đến những nơi khác nhau. Đó sẽ là một ngôi chùa lớn, một địa điểm tham quan xinh đẹp với biển, núi hay điều gì đó đặc biệt. Bạn sẽ có thời gian tắm biển, leo núi hay cả hai. Hãy cứ thưởng thức chuyến đi một cách tuyệt vời nhất.</p>
<p><figure id="attachment_1286" aria-describedby="caption-attachment-1286" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1286 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo79.jpg" alt="Khung cảnh xinh đẹp của khu cắm trại" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo79.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo79-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1286" class="wp-caption-text">Khung cảnh xinh đẹp của khu cắm trại</figcaption></figure></p>
<h3>Kết thúc không phải là hết mà là bắt đầu kỳ trại 14</h3>
<p>Một kỳ trại kết thúc, chúng ta lại cùng ôm nhau với những nụ cười và nước mặt. Họ phải chia tay những con người 3 ngày trước là xa lạ nhưng 3 ngày sau là thân quen. Họ cùng nhau trải qua hành trình 3 ngày với nhiều ý nghĩa. Nước mắt rơi không là hối tiếc mà là sự trân trọng với tình cảm dành cho nhau.</p>
<p><figure id="attachment_1211" aria-describedby="caption-attachment-1211" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1211 size-full" src="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo4.jpg" alt="Chong Chóng Màu - Vật Dụng Trang Trí Nổi Bật" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo4.jpg 920w, https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo4-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1211" class="wp-caption-text">Chong Chóng Màu &#8211; Vật Dụng Trang Trí Nổi Bật</figcaption></figure></p>
<p>Kỳ hội trại 14 năm sau sẽ vẫn tổ chức vào tháng 7. Các bạn hãy cùng đón chờ thông tin mới về địa điểm và thời gian chính thức bắt đầu nhé! Hãy chờ mong những điều mới từ Hội trại tuổi trẻ phật giáo năm 2019.</p>
<p>Nhìn lại tất cả hoạt động Hội trại tuổi trẻ Phật giáo năm 2018 bạn nhé:<br />
<iframe src="https://www.youtube.com/embed/6c1puPinnP4" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>Những hình ảnh khoảnh khắc đặc biệt trong Hội Trại:</p>
<p><figure id="attachment_1415" aria-describedby="caption-attachment-1415" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1415 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-208.jpg" alt="Mọi người vui vẻ sinh hoạt khóa tu mùa hè" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-208.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-208-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1415" class="wp-caption-text">Mọi người vui vẻ sinh hoạt khóa tu mùa hè</figcaption></figure></p>
<p><figure id="attachment_1408" aria-describedby="caption-attachment-1408" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1408 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-201.jpg" alt="Trại sinh hân hoan chơi trò chơi" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-201.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo-201-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1408" class="wp-caption-text">Trại sinh hân hoan chơi trò chơi</figcaption></figure></p>
<p><figure id="attachment_1404" aria-describedby="caption-attachment-1404" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1404 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo197.jpg" alt="Trại sinh ăn dưa hấu" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo197.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo197-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1404" class="wp-caption-text">Trại sinh ăn dưa hấu</figcaption></figure></p>
<p><figure id="attachment_1401" aria-describedby="caption-attachment-1401" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1401 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo194.jpg" alt="Một trại sinh vui vẻ ở trò chơi lớn" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo194.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo194-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1401" class="wp-caption-text">Một trại sinh vui vẻ ở trò chơi lớn</figcaption></figure></p>
<p><figure id="attachment_1389" aria-describedby="caption-attachment-1389" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1389 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo182.jpg" alt="Đi bộ đón bình minh ở biển" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo182.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo182-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1389" class="wp-caption-text">Đi bộ đón bình minh ở biển</figcaption></figure></p>
<p><figure id="attachment_1385" aria-describedby="caption-attachment-1385" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1385 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo178.jpg" alt="Trò chơi nhỏ" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo178.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo178-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1385" class="wp-caption-text">Trò chơi nhỏ</figcaption></figure></p>
<p><figure id="attachment_1369" aria-describedby="caption-attachment-1369" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1369 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo162.jpg" alt="Trò chơi lăn bao bố" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo162.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo162-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1369" class="wp-caption-text">Trò chơi lăn bao bố</figcaption></figure></p>
<p><figure id="attachment_1351" aria-describedby="caption-attachment-1351" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1351 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo144.jpg" alt="Một bạn trại sinh trẻ tuổi" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo144.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo144-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1351" class="wp-caption-text">Một bạn trại sinh trẻ tuổi</figcaption></figure></p>
<p><figure id="attachment_1341" aria-describedby="caption-attachment-1341" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1341 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo134.jpg" alt="Ngày chia tay đượm buồn" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo134.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo134-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1341" class="wp-caption-text">Ngày chia tay đượm buồn</figcaption></figure></p>
<p><figure id="attachment_1313" aria-describedby="caption-attachment-1313" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1313 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo106.jpg" alt="Đêm lửa trại ở hội trại tuổi trẻ phật giáo" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo106.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo106-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1313" class="wp-caption-text">Đêm lửa trại ở hội trại tuổi trẻ phật giáo</figcaption></figure></p>
<p><figure id="attachment_1259" aria-describedby="caption-attachment-1259" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1259 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo52.jpg" alt="Hình dùng trang trí cụm trại" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo52.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo52-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1259" class="wp-caption-text">Hình dùng trang trí cụm trại</figcaption></figure></p>
<p><figure id="attachment_1234" aria-describedby="caption-attachment-1234" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1234 size-full" src="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo27.jpg" alt="Trại sinh chia sẽ lửa hoa đăng" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo27.jpg 920w, https://media.huynhhieutravel.com/Hội-Trại-Tuổi-Trẻ-Phật-Giáo27-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1234" class="wp-caption-text">Trại sinh chia sẽ lửa hoa đăng</figcaption></figure></p>
<p><figure id="attachment_1224" aria-describedby="caption-attachment-1224" style="width: 920px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1224 size-full" src="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo17.jpg" alt="Hoa đăng cầu nguyện" width="920" height="613" srcset="https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo17.jpg 920w, https://media.huynhhieutravel.com/Hội-trại-tuổi-trẻ-phật-giáo17-768x512.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" /><figcaption id="caption-attachment-1224" class="wp-caption-text">Hoa đăng cầu nguyện</figcaption></figure></p>
', 'Hội trại tuổi trẻ Phật giáo là một chương trình trại hè tổ chức hằng năm dành cho lứa tuổi thanh thiếu niên. Năm nay với chủ đề Tuổi Thanh Xuân tổ chức ở Phan Thiết là kỳ hội trại thứ 13. Đây là một cơ hội để các bạn trẻ chiêm nghiệm lại và [&hellip;]', 1250, 'post', '2018-08-02 09:07:01', '2023-04-23 12:25:53');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1430, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1430, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1430, 187);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1430, 297);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1200, 'Herne The Hunter &#8211; Vị chúa tể của rừng', 'herne-the-hunter', '<p>Herne the Hunter là một nhân vật trong truyền thuyết ở Anh. Herne the Hunter là một con ma cư trú tại Windsor Forest và Great Park ở Anh. Trên đầu của <strong>Herne the Hunter</strong> là một đôi gạc của nai và luôn cưỡi một con ngựa. Herne the Hunter xuất hiện từ vở kịch The Merry Wives of Windsor của William Shakespeare vào năm 1597. Đến giờ vẫn chưa thể biết chính xác rằng Shakespeare đã sáng tạo ra nhân vật Herne the Hunter hay đã đưa một phần Herne the Hunter từ trong truyền thuyết địa phương vào vở kịch.</p>
<h3>Herne the Hunter &#8211; Vụ chúa tể của rừng</h3>
<h4>Nguồn gốc ra đời Herne the Hunter</h4>
<p>Chúng ta có rất ít bằng chứng để tìm hiểu về nguồn gốc của Herne the Hunter. Tài liệu sớm nhất tìm thấy được là từ vở kịch của nhà soạn kịch vĩ đại Shakespeare (Tác phẩm nổi bật nhất của ông là Romeo and Juliet). Trong vở kịch The Merry Wives of Windsor (1597) có đoạn:</p>
<p><strong><em>Sometime a keeper here in Windsor Forest,</em></strong></p>
<p><strong><em>Doth all the winter-time, at still midnight,</em></strong></p>
<p><strong><em>Walk round about an oak, with great ragg&#8217;d horns;</em></strong></p>
<p><strong><em>And there he blasts the tree, and takes the cattle,</em></strong></p>
<p><strong><em>And makes milch-kine yield blood, and shakes a chain</em></strong></p>
<p><strong><em>In a most hideous and dreadful manner.</em></strong></p>
<p><strong><em>You have heard of such a spirit, and well you know</em></strong></p>
<p><strong><em>The superstitious idle-headed eld</em></strong></p>
<p><strong><em>Receiv&#8217;d, and did deliver to our age,</em></strong></p>
<p><strong><em>This tale of Herne the Hunter for a truth.</em></strong></p>
<dl>
<dd>&#8211; William Shakespeare, <i>The Merry Wives của Windsor</i></dd>
</dl>
<p><figure id="attachment_1202" aria-describedby="caption-attachment-1202" style="width: 500px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1202" src="https://media.huynhhieutravel.com/Herne-the-Hunter.jpg" alt="Herne the Hunter" width="500" height="337" /><figcaption id="caption-attachment-1202" class="wp-caption-text">Herne the Hunter</figcaption></figure></p>
<p>Sau này vào năm 1602 cũng có một vài phiên bản khác xuất hiện về Herne the Hunter. Nhưng phiên bản này chủ yếu để dọa những đứa trẻ không ngoan. Nó nói về câu chuyện một con ma tàn bạo đi lại lang thang trong rừng với cái tên Herne the Hunter.</p>
<h4>Herne the Hunter trong thần thoại Anh</h4>
<p>Câu chuyện kể về một thợ săn tên Herne làm việc cho vua Richard II. Một thời gian sau có những người ghen tỵ với anh ta. Họ đã vu oan anh ta săn trộm trên mảnh đất của đức vua. Bị vu oan và những người bạn thân thiết ruồng bỏ. Herne đi lang thang khắp khu rừng và tự sát trên một cây sồi.</p>
<p><figure id="attachment_1205" aria-describedby="caption-attachment-1205" style="width: 500px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1205" src="https://media.huynhhieutravel.com/Herne-the-Hunter4.jpg" alt="Herne the Hunter" width="500" height="353" srcset="https://media.huynhhieutravel.com/Herne-the-Hunter4.jpg 1024w, https://media.huynhhieutravel.com/Herne-the-Hunter4-370x260.jpg 370w, https://media.huynhhieutravel.com/Herne-the-Hunter4-768x542.jpg 768w" sizes="(max-width: 500px) 100vw, 500px" /><figcaption id="caption-attachment-1205" class="wp-caption-text">Herne the Hunter</figcaption></figure></p>
<p>Ngoài ra có một số phiên bản khác. Theo đó Herne đã bị thương nặng khi cứu vua Richard II khỏi một vụ tông xe. Anh được một người xa lạ cứu chữa bằng cách lấy gạc của một con nai đã chết gắn vào trán. Nhưng người lạ đã yêu cầu Herne trả công bằng những kỹ năng của mình. Phát điên vì mất đi những kỹ năng mà anh yêu quý. Herne chạy trốn vào rừng, treo cổ tự sát bên một cây sồi. Tuy vậy, mỗi đêm anh vẫn hiện về dẫn đầu cuộc săn đuổi của mình ở Windsor Forest.</p>
<h4>Vì sao Herne the Hunter là chúa tể của rừng?</h4>
<p>Ngoài việc từng là một thợ săn tuyệt vời khi còn sống. Herne the Hunter còn có một đôi gạc sừng tuyệt vời. Theo quan niệm của người xưa ở phương Tây, chiếc sừng đại diện cho quyền lực của những vị thần cổ xưa. Nó thể hiện sự uy nghiêm và một sức mạnh thiên nhiên tuyệt vời.</p>
<p><figure id="attachment_1203" aria-describedby="caption-attachment-1203" style="width: 500px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1203" src="https://media.huynhhieutravel.com/Herne-the-Hunter2.jpg" alt="Herne the Hunter" width="500" height="414" srcset="https://media.huynhhieutravel.com/Herne-the-Hunter2.jpg 1181w, https://media.huynhhieutravel.com/Herne-the-Hunter2-768x637.jpg 768w" sizes="(max-width: 500px) 100vw, 500px" /><figcaption id="caption-attachment-1203" class="wp-caption-text">Herne the Hunter</figcaption></figure></p>
<p>Herne the Hunter xuất hiện với đôi sừng nai, cưỡi trên lưng một con ngựa đen, đem theo một cây cung bằng gỗ. Và đi cùng anh là những con chó săn bay lượn. Truyền thuyết kể lại nếu một ai đi ngang qua con đường của Herne the Hunter thì họ sẽ bị cuốn lấy và đi theo anh ta mãi mãi.</p>
<p>Sự xuất hiện của Herne the Hunter là một điềm xấu cho Hoàng gia. Herne the Hunter chỉ xuất hiện ở khu rừng Windsor Forest khi cần thiết. Và nó luôn là một thời kỳ khủng hoảng của quốc gia.</p>
', 'Herne the Hunter là một nhân vật trong truyền thuyết ở Anh. Herne the Hunter là một con ma cư trú tại Windsor Forest và Great Park ở Anh. Trên đầu của Herne the Hunter là một đôi gạc của nai và luôn cưỡi một con ngựa. Herne the Hunter xuất hiện từ vở kịch The Merry Wives of Windsor của William [&hellip;]', 1204, 'post', '2018-07-18 11:44:36', '2023-04-23 12:33:45');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1200, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1200, 144);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1186, 'Cerberus &#8211; Chú chó canh giữ địa ngục', 'cerberus', '<p>Cerberus là một quái vật trong thần thoại Hy Lạp. Nó là một con chó nhiều đầu bảo vệ cổng của địa ngục. Nó ngăn người chết rời khỏi và chặn những kẻ xâm nhập bất hợp pháp. Cerberus thường được nhắc đến qua câu chuyện của Heracles.</p>
<h3>Cerberus &#8211; Chú chó canh giữ địa ngục</h3>
<p><figure id="attachment_1190" aria-describedby="caption-attachment-1190" style="width: 400px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1190" src="https://media.huynhhieutravel.com/Cerberus2.jpg" alt="Cerberus" width="400" height="225" srcset="https://media.huynhhieutravel.com/Cerberus2.jpg 1280w, https://media.huynhhieutravel.com/Cerberus2-768x432.jpg 768w" sizes="(max-width: 400px) 100vw, 400px" /><figcaption id="caption-attachment-1190" class="wp-caption-text">Cerberus</figcaption></figure></p>
<p>Cerberus được miêu tả khác nhau với nhiều dị bản. Nhưng điều chắc chắn là hinh dạng của nó giống như một con chó.</p>
<h4>Hình dạng của Cerberus</h4>
<p><img loading="lazy" decoding="async" class="alignnone size-full wp-image-1196" src="https://media.huynhhieutravel.com/Cerberus-title.jpg" alt="" width="851" height="200" srcset="https://media.huynhhieutravel.com/Cerberus-title.jpg 851w, https://media.huynhhieutravel.com/Cerberus-title-768x180.jpg 768w" sizes="(max-width: 851px) 100vw, 851px" /></p>
<p>Thường có nhiều tranh cãi về số đầu của Cerberus. Nhưng đa số đều cho rằng nó có 3 đầu. Nó là kết quả của hai quái vật là Echidna và Typhon (Những quái vật sinh ra để hủy diệt Olympus &#8211; Nữa người nữa rắn với thân trên là người). Ngoài ra một số giả thuyết khác cho rằng sở dĩ nó có ba chiếc đầu là vì mỗi chiếc đầu tượng trưng cho quá khứ, hiện tại và tương lai.</p>
<p><figure id="attachment_1191" aria-describedby="caption-attachment-1191" style="width: 400px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1191 size-full" src="https://media.huynhhieutravel.com/Cerberus3.jpg" alt="Cerberus" width="400" height="300" /><figcaption id="caption-attachment-1191" class="wp-caption-text">Cerberus</figcaption></figure></p>
<p>Trong mô tả sớm nhất của Cerberus, Hesiod&#8217;s Theiodony (Khoảng thế kỷ thứ 8 đến thứ 7 TCN), Cerberus có năm mươi đầu. Trong khi Pindar (khoảng năm 522 &#8211; 443 TCN) cho rằng nó có 100 cái đầu. Tuy nhiên, các nhà văn sau này hầu như đều mô tả nó với ba cái đầu.</p>
<p>Trong nghệ thuật, Cerberus thường được mô tả với hai đầu chó, không bao giờ nhiều hơn ba, nhưng đôi khi chỉ có một. Một trong hai mô tả sớm nhất (Khoảng năm 590–580 TCN), một chiếc cốc Corinth từ Argos, nó được thể hiện như một con chó bình thường. Sự xuất hiện đầu tiên của một con Cerberus ba đầu xảy ra ở giữa thế kỷ thứ 6 TCN.</p>
<p>Ngoài ra con nhiều giả thuyết về số đầu hoặc đầu của Cerberus là đầu rắn. Dựa trên giả thuyết cha mẹ của nó đều là những quái vật mình người thân rắn.</p>
<h4>Câu chuyện về Cerberus</h4>
<p><img loading="lazy" decoding="async" class="alignnone size-full wp-image-1197" src="https://media.huynhhieutravel.com/Cerberus-title2.jpg" alt="" width="851" height="200" srcset="https://media.huynhhieutravel.com/Cerberus-title2.jpg 851w, https://media.huynhhieutravel.com/Cerberus-title2-768x180.jpg 768w" sizes="(max-width: 851px) 100vw, 851px" /></p>
<p>Thần thoại duy nhất về Cerberus liên quan đến việc nó bị bắt bởi Heracles. Eurystheus đưa ra nhiệm vụ thứ 12 &#8211; cũng là nhiệm vụ cuối cùng để Heracles thực hiện. Đây là một nhiệm vụ khó khăn mà Eurystheus nghĩ rằng Heracles sẽ không thể thực hiện được.</p>
<p>Hera mớm lời cho Eurystheus: &#8220;Hãy yêu cầu hắn ta xuống địa ngục mà không đem theo bất cứ một thứ vũ khí nào!&#8221;. Tuy nhiên, Hercules đã xin được mang theo bộ da của con sư tử Némée.</p>
<p>Gần đến Địa ngục, Hercules bắt gặp Theseus và Pirithous bị xích vào một tảng đá. Chàng cứu được Theseus nhưng khi định kéo Pirithous lên thì mặt đất rung chuyển dữ dội. Do Pirithious chính là người chủ mưu bắt cóc nàng Persephone &#8211; vợ của Hades.</p>
<p><figure id="attachment_1192" aria-describedby="caption-attachment-1192" style="width: 400px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1192" src="https://media.huynhhieutravel.com/Cerberus4.jpg" alt="Cerberus" width="400" height="400" srcset="https://media.huynhhieutravel.com/Cerberus4.jpg 425w, https://media.huynhhieutravel.com/Cerberus4-150x150.jpg 150w" sizes="(max-width: 400px) 100vw, 400px" /><figcaption id="caption-attachment-1192" class="wp-caption-text">Cerberus mô hình hoạt họa</figcaption></figure></p>
<p>Trở ngại đầu tiên khi muốn xuống địa phủ là phải vượt qua con sông Styx. Nơi những linh hồn của người vừa chết tụ tập chờ đợi để được qua sông trên chiếc thuyền của Charon. Charon sẽ không đưa bất cứ ai qua sông nếu họ chưa hội đủ hai điều kiện sau. Đầu tiên là phải đưa một khoản lộ phí dưới dạng một đồng tiền hình con dê. Hai là người đó đã chết. Hercules không đáp ứng được điều kiện nào. Một trường hợp làm vấn đề thêm trầm trọng với bản tính cáu kỉnh của Charon. Nhưng Hercules chỉ cần vỗ tay là đủ để Charon ngoan ngoãn đưa chàng vượt sông Styx.</p>
<p>Thử thách lớn hơn chính là con Cerberus, với hàm răng sắc nhọn, ba cái đầu, một con rắn độc ở đằng đuôi. Tất cả nhằm vào Hercules khi con nó bất thình lình lao tới chụp vào cổ chàng. May thay, Hercules khoác tấm da con sư tử chàng đã giết trước đây nên không gì có thể xuyên thủng được ngoại trừ sấm sét của Zeus. Hercules cuối cùng cũng quy phục được con Cerberus và lôi nó tới Tiryns. Nơi chàng được tự do sau nhiệm vụ cuối cùng này.</p>
<p>Sau khi tên Eurystheus hoảng sợ năn nỉ chàng đem con chó trở về Địa ngục. Hercules thả con Cerberus trở về. Nó khiếp sợ nhưng cũng rất căm giận nên đã tự tử.</p>
<h4>Biểu tượng Cerberus</h4>
<p>Biểu tượng Cerberus là một biểu tượng thông dụng trong nghệ thuật Hy Lạp và La Mã cổ đại. Những hình tượng này bắt đầu xuất hiện từ thế kỷ thứ 6 TCN. Hình ảnh Cerberus được vẽ lên một chén Corinth (khoảng 590–580 trước Công nguyên). Trên chén Corinth là những hình vẽ kể về hành trình Hercules xuống địa ngục bắt nó.</p>
<p>Đa phần những biểu tượng Cerberus đều là câu chuyện kể về hành trình của Hercules với nhiều biến thể khác nhau. Chúng được khắc trên những bình gốm hay trên mái của một công trình nào đó.</p>
<p>Trong chòm sao Cerberus được giới thiệu bởi Johannes Hevelius năm 1687, nó được vẽ như một con rắn ba đầu, được giữ trong tay Hercules (trước đây những ngôi sao này đã được mô tả như một nhánh cây mọc trên cây Táo của Hesperides).</p>
<p><figure id="attachment_1189" aria-describedby="caption-attachment-1189" style="width: 400px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="wp-image-1189" src="https://media.huynhhieutravel.com/Cerberus.jpg" alt="Cerberus" width="400" height="244" srcset="https://media.huynhhieutravel.com/Cerberus.jpg 1200w, https://media.huynhhieutravel.com/Cerberus-768x468.jpg 768w" sizes="(max-width: 400px) 100vw, 400px" /><figcaption id="caption-attachment-1189" class="wp-caption-text">Hình tượng Cerberus trong Harry Potter</figcaption></figure></p>
<p>Hình tượng Cerberus còn được nhắc đến đến trong Harry Potter với cái tên Fluffy. Nó là con chó canh giữ cổng đường vào căn hầm giữ Hòn đá Phù thủy.</p>
', 'Cerberus là một quái vật trong thần thoại Hy Lạp. Nó là một con chó nhiều đầu bảo vệ cổng của địa ngục. Nó ngăn người chết rời khỏi và chặn những kẻ xâm nhập bất hợp pháp. Cerberus thường được nhắc đến qua câu chuyện của Heracles. Cerberus &#8211; Chú chó canh giữ địa ngục [&hellip;]', 1190, 'post', '2018-07-18 09:33:18', '2023-04-23 12:33:46');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1186, 431);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1186, 144);