INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1677, 'Khu du lịch Lá Phong', 'khu-du-lich-la-phong', '<p><strong>Khu du lịch Lá Phong</strong> hay <strong>Rừng Lá Phong</strong> là một điểm du lịch nằm gần trung tâm thành phố Đà Lạt. Nơi đây xây dựng theo ý tưởng một <strong>khu vườn lá phong</strong> với những kiến trúc độc đáo. Những kiến trúc mô phỏng theo phong cách <strong>cổ tích</strong> đầy mộng mơ giữa một rừng phong tuyệt vời. Đặc biệt ngôi nhà với <strong>132 &#8216;mái&#8217;</strong> độc đáo, kỳ lạ là điểm nhấn của Khu du lịch Lá Phong.</p>
<p><figure id="attachment_1681" aria-describedby="caption-attachment-1681" style="width: 589px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1681" src="https://media.huynhhieutravel.com/Khu-du-lịch-rừng-lá-phong-đà-lạt4.jpg" alt="Khu du lịch Lá Phong" width="589" height="514"><figcaption id="caption-attachment-1681" class="wp-caption-text">Khu du lịch Lá Phong</figcaption></figure></p>
<h2>Thông tin Khu du lịch Lá Phong</h2>
<p>Nằm trên đường Đặng Thái Thân ở trung tâm thành phố Đà Lạt là một khu du lịch rộng gần <strong>5ha</strong> với những kiến trúc độc đáo. Chủ nhân ở đây muốn xây dựng một điểm nhấn với một khu vườn như trong cổ tích ở Đà Lạt. Nơi đây có một khu vườn xinh đẹp trồng nhiều cây thông, ngôi nhà 132 mái, một hồ nước view đẹp lộng lẫy và rất nhiều điểm nhấn khác để chúng ta khám phá.</p>
<p><strong>Địa chỉ</strong>: 45 Đặng Thái Thân, phường 3, thành phố Đà Lạt, tỉnh Lâm Đồng.</p>
<p><strong>Số điện thoại</strong>:&nbsp;02633597168 hoặc 02633919679</p>
<p><strong>Email</strong>:&nbsp;dalatmaple@gmail.com</p>
<p><strong>Giờ mở cửa</strong>: 8h00-17h00</p>
<p><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3189.1178713214695!2d108.45059777688422!3d11.929358290995362!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3171133e5090ba29%3A0x2be50419c9e40550!2zS2h1IGR1IGzhu4tjaCBMw6EgUGhvbmcgxJDDoCBM4bqhdA!5e0!3m2!1svi!2s!4v1535686916460" width="600" height="450" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h3>Kiến trúc Khu du lịch Lá Phong</h3>
<p>Khu du lịch được chính thức đưa vào hoạt động vào ngày 26/05/2017 với diện tích hơn 5ha với nhiều tiểu cảnh khác nhau.</p>
<p><figure id="attachment_1680" aria-describedby="caption-attachment-1680" style="width: 475px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1680" src="https://media.huynhhieutravel.com/Khu-du-lịch-rừng-lá-phong-đà-lạt3.jpg" alt="Lá phong ở khu du lịch" width="475" height="591"><figcaption id="caption-attachment-1680" class="wp-caption-text">Lá phong ở khu du lịch</figcaption></figure></p>
<h4>Ngôi nhà 132 mái</h4>
<p>Ngôi nhà được xây dựng với 132 mái khác nhau với diện tích hơn 300m2. Số lượng 132 là mô phỏng theo lối kiến trúc của một kim tự tháp. Nó mang lại sự thịnh vượng, may mắn của lá phong kết hợp với năng lượng thần bí đến từ Kim tự tháp Ai Cập. Bên trong ngôi nhà còn treo 80 bức tranh chủ đề Lá phong, 800 chậu hoa và 80 bình gốm sứ khác nhau. Chắc chắn chủ nhân ở nơi đây rất tin vào phong thủy.</p>
<p><figure id="attachment_1682" aria-describedby="caption-attachment-1682" style="width: 591px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1682" src="https://media.huynhhieutravel.com/Khu-du-lịch-rừng-lá-phong-đà-lạt5.jpg" alt="Khu du lịch lá phong đà lạt" width="591" height="338"><figcaption id="caption-attachment-1682" class="wp-caption-text">Khu du lịch lá phong đà lạt</figcaption></figure></p>
<h4>Căn nhà &#8220;Trống&#8221;</h4>
<p>Trống ở đây mang ý nghĩa chiếc Trống của dân tộc Tây Nguyên. Căn nhà được mô phỏng theo hình thù một chiếc trống. Đặc biệt bên trong có 20 mặt kính tượng trưng 20 mặt trống với nhiều hình thù khác nhau. Đặc biệt, khi cường độ sáng bên ngoài thay đổi thì màu sắc của 20 mặt kính này cũng thay đổi khác nhau, nhất là khi hoàng hôn hoặc bình minh.</p>
<p>Căn nhà được thiết kế từ ý tưởng một truyền thuyết của dân tộc Tây Nguyên. Truyền thuyết kể rằng vào thuở hồng hoang, khi loài người còn mông muội. Một cơn Đại hồng thủy được tạo ra bởi cơn giận của những thần linh cuốn trôi tất cả vào hủy diệt. Tuy nhiên, cũng có những vị thần linh hiền từ muốn bảo vệ loài người. Họ đã chỉ dẫn những sinh linh trốn vào trong những chiếc trống bao gồm: một cặp vợ chồng, một cặp chó, một cặp gà, một cặp heo, một cặp trâu,&#8230; Nhờ vậy mà các giống loài được sống sót và duy trì.</p>
<h4>&#8220;Địa đàng trong lòng đất&#8221;</h4>
<p>Đây thật chất là một đường hầm được xây dựng dưới lòng đất với nhiều công trình khác nhau trong đó. Bên trong là khu hostel &#8220;Phố cổ&#8221;, những tượng đất nung, quầy bar,&#8230;</p>
<p><figure id="attachment_1678" aria-describedby="caption-attachment-1678" style="width: 476px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1678" src="https://media.huynhhieutravel.com/Khu-du-lịch-rừng-lá-phong-đà-lạt.jpg" alt="Hồ cá ở khu du lịch lá phong" width="476" height="600"><figcaption id="caption-attachment-1678" class="wp-caption-text">Hồ cá ở khu du lịch</figcaption></figure></p>
<h4>Và nhiều tiểu cảnh độc đáo khác</h4>
<p>Ở đây còn có nhiều tiểu cảnh xinh đẹp có thể tạo nên những khung cảnh tuyệt vời khi lên hình.</p>
<p>Hồ cá với view nhìn ra núi. Bạn sẽ được chụp hình bên một hồ cá Koi với những con cá mập ú nu trong hồ. Bên ngoài là một khung cách nhìn ra đồi núi với những rừng thông trùng điệp. Những ngôi nhà Nấm nhỏ xinh đẹp như trong truyện cổ tích Bạch Tuyết và Bảy chú lùn. Và nhiều tiểu cảnh trong truyện cổ tích khác như: Suối mơ, đường hào hoa,&#8230;</p>
<p><figure id="attachment_1679" aria-describedby="caption-attachment-1679" style="width: 478px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1679" src="https://media.huynhhieutravel.com/Khu-du-lịch-rừng-lá-phong-đà-lạt2.jpg" alt="Khu du lịch rừng lá phong" width="478" height="599"><figcaption id="caption-attachment-1679" class="wp-caption-text">Khu du lịch rừng lá phong</figcaption></figure></p>
<p>Khu du lịch Lá Phong có tổng cộng 2.000 cây phong, 2.000 cây tùy bút với 950 cây có tuổi đời hơn 17 năm dùng để làm bonsai, 500 cây hoa anh đào, 230 con cá Koi và nhiều giống cây trồng khác.</p>
<h2>Đường đi đến Khu du lịch Lá Phong</h2>
<p>Đường đi đến Khu du lịch Lá Phong khá dễ dàng. Nó nằm cách chợ Đà Lạt chỉ gần 3km. Bạn có thể đi bằng xe máy và xe hơi vào.</p>
<p><strong>Lưu ý</strong>: Xe hơi 45 chỗ sẽ không thể vào bên trong được vì đường hơi nhỏ.</p>
<p>Bạn có thể bật tọa độ hoặc điền địa chỉ của mình vào link để nhận chỉ đường: <a href="https://www.google.com/maps/dir//Khu+du+l%E1%BB%8Bch+L%C3%A1+Phong+%C4%90%C3%A0+L%E1%BA%A1t,+%C4%90%E1%BA%B7ng+Th%C3%A1i+Th%C3%A2n,+Ph%C6%B0%E1%BB%9Dng+3,+Th%C3%A0nh+ph%E1%BB%91+%C4%90%C3%A0+L%E1%BA%A1t,+L%C3%A2m+%C4%90%E1%BB%93ng,+Vi%E1%BB%87t+Nam/@10.9711355,106.0037204,8z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3171133e5090ba29:0x2be50419c9e40550!2m2!1d108.4519819!2d11.9283645">Tọa độ và cách đi đến Khu du lịch Lá Phong</a></p>
<h3>Thời điểm thích hợp đi Khu du lịch Lá Phong</h3>
<p>Khu du lịch Lá Phong gần như mở quanh năm, nhưng bạn cũng nên lựa chọn thời điểm thích hợp để đi. Bạn nên đi vào dịp thu đông thì sẽ đẹp hơn. Lúc ấy lá thông sẽ bắt đầu rơi và khung cảnh trở nên thơ mộng hơn. Ngoài ra bạn nên tránh đi vào ngày trưa nắng gắt.</p>
<h4>Giá vé Khu du lịch Lá Phong</h4>
<p>Giá vé vào cổng: 40.000đ/người, 20.000/trẻ em.</p>
<h4>Giá phòng nghỉ ở Khu du lịch Lá Phong</h4>
<p>Giương dorm đơn: 80.000đ/giường</p>
<p>Giường dorm đôi: 180.000đ/giường.</p>
<h2>Review Khu du lịch Lá Phong</h2>
<p>Với những tiểu cảnh độc đáo, Khu du lịch Lá Phong hứa hẹn sẽ là một điểm du lịch độc đáo trong hành trình Đà Lạt của bạn. Tuy nhiên, Khu du lịch vẫn còn một số hạn chế vì không gian chưa thật sự rộng lớn. Nó sẽ hơi nhàm chán nếu bạn quay lại lần hai hoặc sẽ chưa làm hài lòng nhiều du khách khó tính. Đánh giá 6/10 điểm.</p>
<h3>Đánh giá của khách du lịch về Khu du lịch Lá Phong</h3>
<p>Bạn Duy Nguyen truong đánh giá 3/5: &#8220;Cảnh tương đối đẹp nhwgn chưa đủ thu hút khách ghé lại lần 2&#8221;.</p>
<p>Bạn Văn Ãm Nguyễn đánh giá 5/5: &#8220;Nhiều điểm chụp ảnh đẹp. Tuy nhiên rừng lá phong còn nhỏ&#8221;.</p>
<p>Bạn Thanh sơn Nguyễn đánh giá 5/5: &#8220;Khung cảnh thật tuyệt vời&#8221;.</p>
<p><figure id="attachment_1684" aria-describedby="caption-attachment-1684" style="width: 385px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1684" src="https://media.huynhhieutravel.com/Review-Khu-du-lịch-lá-phong.png" alt="Review Khu du lịch Lá Phong" width="385" height="577"><figcaption id="caption-attachment-1684" class="wp-caption-text">Review Khu du lịch Lá Phong</figcaption></figure></p>
<p>Ngoài ra các bạn có thể tham khảo thêm những địa điểm du lịch thú vị khác:</p>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Nông trại thú cưng Đà Lạt – Black Rock Garden” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/nong-trai-thu-cung-da-lat-black-rock-garden/embed/#?secret=ds6wEU8uDw" width="600" height="252" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="ds6wEU8uDw" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Kinh nghiệm đi Tuyệt Tình Cốc Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/kinh-nghiem-di-tuyet-tinh-coc-da-lat/embed/#?secret=68ULRnwutR" width="600" height="252" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="68ULRnwutR" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Thác Datanla Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/thac-datanla-da-lat/embed/#?secret=UML3gOEYTz" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="UML3gOEYTz" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Đường Hầm Điêu Khắc (Đường Hầm Đất Sét) Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/duong-ham-dieu-khac-da-lat/embed/#?secret=66CkpHH1hz" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="66CkpHH1hz" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Đỉnh núi Langbiang Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/dinh-nui-langbiang-da-lat/embed/#?secret=QNwDEd19bh" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="QNwDEd19bh" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Thung Lũng Vàng (Khu du lịch Suối Vàng) Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/thung-lung-vang/embed/#?secret=bOAHoM0E6m" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="bOAHoM0E6m" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Crazy House Đà Lạt (Biệt Thự Hằng Nga)” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/crazy-house/embed/#?secret=nvUvM8WMko" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="nvUvM8WMko" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Quảng trường Lâm Viên Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/quang-truong-lam-vien-da-lat/embed/#?secret=EQNzS0sYdd" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="EQNzS0sYdd" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Khu du lịch Lá Phong” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/khu-du-lich-la-phong/embed/#?secret=WReaBlNo9T" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="WReaBlNo9T" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Đồi Thiên Phúc Đức Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/doi-thien-phuc-duc/embed/#?secret=zU1SnSZNoC" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="zU1SnSZNoC" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Vườn Thú Zoodoo” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/vuon-thu-zoodoo/embed/#?secret=8R0QrehllX" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="8R0QrehllX" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Trường Cao Đẳng Sư Phạm Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/truong-cao-dang-su-pham-da-lat/embed/#?secret=KkPW8Gq0Kr" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="KkPW8Gq0Kr" data-mce-fragment="1"></iframe></p>
</div>
', 'Khu du lịch Lá Phong hay Rừng Lá Phong là một điểm du lịch nằm gần trung tâm thành phố Đà Lạt. Nơi đây xây dựng theo ý tưởng một khu vườn lá phong với những kiến trúc độc đáo. Những kiến trúc mô phỏng theo phong cách cổ tích đầy mộng mơ giữa một [&hellip;]', 1681, 'post', '2018-08-31 06:33:24', '2023-04-23 12:46:53');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1677, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1677, 48);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1671, 'Ảnh Cần Thơ Xưa Và Nay', 'anh-can-tho-xua-va-nay', '<p>Hình ảnh Cần Thơ xưa nay với bao <strong>đổi thay</strong> và dần trở thành một thành phố trực thuộc trung ương hiện đại, tấp nập. Nhưng những <strong>góc phố, con đường và cả con người</strong> dường như vẫn không quá nhiều thay đổi. Hãy cùng nhìn lại những khoảnh khắc <strong>Cần Thơ ngày trước và hiện nay</strong>. Hãy xem những thay đổi của nó có làm bạn bị choáng ngợp và nhận ra Cần Thơ ngày trước không nhé!</p>
<h2>Ảnh Cần Thơ xưa và hiện nay</h2>
<p>Tôi đã cố lục lại những ảnh cũ thuộc về riêng Cần Thơ. Và cố công chạy khắp con phố để <strong>cùng một góc ảnh</strong> trước đây xem nó thay đổi như thế nào? Cần Thơ xưa và nay!</p>
<p>Trường Đại học Cần Thơ trước đây và một phần của nó hiện tại!</p>
<p><figure id="attachment_1647" aria-describedby="caption-attachment-1647" style="width: 640px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1647" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa2.jpg" alt="Đại học Cần Thơ ngày xưa" width="640" height="441"><figcaption id="caption-attachment-1647" class="wp-caption-text">Đại học Cần Thơ ngày xưa</figcaption></figure></p>
<p><figure id="attachment_1643" aria-describedby="caption-attachment-1643" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1643" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay16.jpg" alt="Trung tâm học liệu Đại Học Cần Thơ" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay16.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay16-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1643" class="wp-caption-text">Trung tâm học liệu Đại Học Cần Thơ</figcaption></figure></p>
<p>Bạn có nhận ra đây là đâu?&nbsp;Dường như những không gian ở Đại lộ Hòa Bình vẫn không thay đổi nhiều lắm!</p>
<p><figure id="attachment_1672" aria-describedby="caption-attachment-1672" style="width: 1024px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1672" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa.jpg" alt="Cần Thơ xưa" width="1024" height="666" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa.jpg 1024w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-768x500.jpg 768w" sizes="(max-width: 1024px) 100vw, 1024px" /><figcaption id="caption-attachment-1672" class="wp-caption-text">Cần Thơ xưa</figcaption></figure></p>
<p><figure id="attachment_1673" aria-describedby="caption-attachment-1673" style="width: 5472px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1673" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay2.jpg" alt="Cần Thơ ngày nay" width="5472" height="3648" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay2.jpg 5472w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay2-768x512.jpg 768w" sizes="(max-width: 5472px) 100vw, 5472px" /><figcaption id="caption-attachment-1673" class="wp-caption-text">Cần Thơ ngày nay</figcaption></figure></p>
<p>Bạn có nhận ra một biểu tượng hình ảnh Cần Thơ xưa ở công viên Tao Đàn vẫn còn giữ lại ngày nay không?</p>
<p><figure id="attachment_1655" aria-describedby="caption-attachment-1655" style="width: 638px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1655" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa10.jpg" alt="Công viên Tao Đàn Cần Thơ ngày xưa" width="638" height="481"><figcaption id="caption-attachment-1655" class="wp-caption-text">Công viên Tao Đàn Cần Thơ ngày xưa</figcaption></figure></p>
<p><figure id="attachment_1665" aria-describedby="caption-attachment-1665" style="width: 5472px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1665" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay.jpg" alt="Công viên Tao Đàn hiện nay" width="5472" height="3648" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay.jpg 5472w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay-768x512.jpg 768w" sizes="(max-width: 5472px) 100vw, 5472px" /><figcaption id="caption-attachment-1665" class="wp-caption-text">Công viên Tao Đàn hiện nay</figcaption></figure></p>
<p>Ngôi chùa Khmer ở đường Đại lộ Hòa Bình vẫn không thay đổi nhiều so với hình ảnh nó trước đây!</p>
<p><figure id="attachment_1662" aria-describedby="caption-attachment-1662" style="width: 472px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1662" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa17.jpg" alt="Chùa Khmer ở Đại lộ Hòa Bình trước đây" width="472" height="326"><figcaption id="caption-attachment-1662" class="wp-caption-text">Chùa Khmer ở Đại lộ Hòa Bình trước đây</figcaption></figure></p>
<p><figure id="attachment_1667" aria-describedby="caption-attachment-1667" style="width: 5472px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1667" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay4.jpg" alt="Chùa Khmer hiện nay vẫn không thay đổi" width="5472" height="3648" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay4.jpg 5472w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay4-768x512.jpg 768w" sizes="(max-width: 5472px) 100vw, 5472px" /><figcaption id="caption-attachment-1667" class="wp-caption-text">Chùa Khmer hiện nay vẫn không thay đổi</figcaption></figure></p>
<p>Nhưng ngôi chùa Phật Học đã trở nên bề thế hơn rất rất nhiều. Nó khoác lên mình sự thay đổi hiện đại của hình ảnh Cần Thơ xưa và nay.</p>
<p><figure id="attachment_1651" aria-describedby="caption-attachment-1651" style="width: 550px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1651" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa6.jpg" alt="Chùa Phật Học ngày trước" width="550" height="347"><figcaption id="caption-attachment-1651" class="wp-caption-text">Chùa Phật Học ngày trước</figcaption></figure></p>
<p><figure id="attachment_1668" aria-describedby="caption-attachment-1668" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1668" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay5.jpg" alt="Chùa Phật Học to lớn ngày nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay5.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay5-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1668" class="wp-caption-text">Chùa Phật Học to lớn ngày nay</figcaption></figure></p>
<p>Tòa Hành Chánh trước đây đã đổi thành một chức năng khác hoàn toàn!</p>
<p><figure id="attachment_1661" aria-describedby="caption-attachment-1661" style="width: 637px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1661" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa16.jpg" alt="Tòa Hành Chính Cần Thơ xưa" width="637" height="421"><figcaption id="caption-attachment-1661" class="wp-caption-text">Tòa Hành Chánh Cần Thơ xưa</figcaption></figure></p>
<p><figure id="attachment_1635" aria-describedby="caption-attachment-1635" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1635" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay8.jpg" alt="Thư viện thành phố Cần Thơ" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay8.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay8-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1635" class="wp-caption-text">Thư viện thành phố Cần Thơ</figcaption></figure></p>
<p>Vòng xoay ở Đại lộ Hòa Bình trước đây!</p>
<p><figure id="attachment_1650" aria-describedby="caption-attachment-1650" style="width: 550px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1650" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa5.jpg" alt="Cần Thơ xưa" width="550" height="253"><figcaption id="caption-attachment-1650" class="wp-caption-text">Cần Thơ xưa</figcaption></figure></p>
<p><figure id="attachment_1636" aria-describedby="caption-attachment-1636" style="width: 1280px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1636" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay9.jpg" alt="Vòng xoay Đại lộ Hòa Bình" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay9.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay9-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1636" class="wp-caption-text">Vòng xoay Đại lộ Hòa Bình</figcaption></figure></p>
<p>Hãy cùng tìm hiểu về bến Ninh Kiều ngày trước năm 1975. Thì ra trước đây cũng có dịch vụ du thuyền từ lâu. Hiện nay bến Ninh Kiều là nơi thu hút rất nhiều khách du lịch và là điểm văn hóa đặc trưng của Cần Thơ. Dường như khi đến Cần Thơ chúng ta đều phải đến Bến Ninh Kiều dạo chơi cho biết. Nơi đây cũng được xem là một công viên đi bộ khá thú vị của người dân Cần Thơ.</p>
<p>Đặc biệt, gần đây bến Ninh Kiều còn khánh thành cầu đi bộ hay còn gọi là cầu tình yêu nối dài bến Ninh Kiều cùng bờ kè sông Hậu. Về đêm, những cây cầu và cả bến Ninh Kiều tỏa sáng rực rỡ lung linh.</p>
<p><figure id="attachment_1648" aria-describedby="caption-attachment-1648" style="width: 550px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1648" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa3.jpg" alt="Bến tàu du thuyền bến Ninh Kiều ngày xưa" width="550" height="365"><figcaption id="caption-attachment-1648" class="wp-caption-text">Bến tàu du thuyền bến Ninh Kiều ngày xưa</figcaption></figure></p>
<p><figure id="attachment_1669" aria-describedby="caption-attachment-1669" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1669" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay6.jpg" alt="Bến tàu du thuyền ngày nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay6.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay6-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1669" class="wp-caption-text">Bến tàu du thuyền ngày nay</figcaption></figure></p>
<p>Ngân hàng nhà nước thì dường như chỉ thay đổi cái tên mà thôi!</p>
<p><figure id="attachment_1664" aria-describedby="caption-attachment-1664" style="width: 550px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1664" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa19.jpg" alt="Ngân hàng nhà nước Việt Nam thời xưa" width="550" height="376"><figcaption id="caption-attachment-1664" class="wp-caption-text">Ngân hàng nhà nước Việt Nam thời xưa</figcaption></figure></p>
<p><figure id="attachment_1670" aria-describedby="caption-attachment-1670" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1670" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay7.jpg" alt="Cần Thơ xưa và nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay7.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay7-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1670" class="wp-caption-text">Cần Thơ xưa và nay</figcaption></figure></p>
<p>Con đường Hai Bà Trưng ngày trước.</p>
<p><figure id="attachment_1663" aria-describedby="caption-attachment-1663" style="width: 550px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1663" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa18.jpg" alt="Một góc đường bến Ninh Kiều xưa" width="550" height="377"><figcaption id="caption-attachment-1663" class="wp-caption-text">Một góc đường bến Ninh Kiều xưa</figcaption></figure></p>
<p><figure id="attachment_1646" aria-describedby="caption-attachment-1646" style="width: 1280px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1646" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay19.jpg" alt="Cần Thơ xưa và nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay19.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay19-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1646" class="wp-caption-text">Cần Thơ xưa và nay</figcaption></figure></p>
<p><strong>Chùa Ông</strong> là ngôi chùa lịch sử lâu đời mà vẫn chưa thay đổi và trùng tu lớn về kiến trúc! Nó là ngôi chùa lịch sử lâu đời và còn vẹn nguyên như thuở ban đầu hiếm hoi của Cần Thơ. Lịch sử của nó đến hiện nay lên đến hơn 120 năm. Năm 1993, chùa Ông còn được cấp chứng chỉ di tích lịch sử cấp Quốc gia.</p>
<p><figure id="attachment_1660" aria-describedby="caption-attachment-1660" style="width: 641px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1660" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa15.jpg" alt="Chùa Ông ngày trước" width="641" height="416"><figcaption id="caption-attachment-1660" class="wp-caption-text">Chùa Ông ngày trước</figcaption></figure></p>
<p><figure id="attachment_1645" aria-describedby="caption-attachment-1645" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1645" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay18.jpg" alt="Chùa Ông ngày nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay18.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay18-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1645" class="wp-caption-text">Chùa Ông ngày nay</figcaption></figure></p>
<p>Dãy nhà phố nhộn nhịp ngày xưa giờ đã khang trang hơn nhưng dường như cũng vắng vẻ hơn rất nhiều!</p>
<p><figure id="attachment_1659" aria-describedby="caption-attachment-1659" style="width: 637px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1659" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa14.jpg" alt="Một góc phố ở bến Ninh Kiều xưa" width="637" height="428"><figcaption id="caption-attachment-1659" class="wp-caption-text">Một góc phố ở bến Ninh Kiều xưa</figcaption></figure></p>
<p><figure id="attachment_1642" aria-describedby="caption-attachment-1642" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1642" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay15.jpg" alt="Dãy nhà cổ ngày xưa đã bị thay thế bằng nhà lầu hiện đại" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay15.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay15-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1642" class="wp-caption-text">Dãy nhà cổ ngày xưa đã bị thay thế bằng nhà lầu hiện đại</figcaption></figure></p>
<p>Bạn có nhận ra kiến trúc nào vẫn chưa thay đổi? Có những thứ hàng trăm năm vẫn giữ nguyên vẹn một giá trị!</p>
<p><figure id="attachment_1656" aria-describedby="caption-attachment-1656" style="width: 639px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1656" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa11.jpg" alt="Một góc đường nhộn nhịp ngày xưa" width="639" height="438"><figcaption id="caption-attachment-1656" class="wp-caption-text">Một góc đường nhộn nhịp ngày xưa</figcaption></figure></p>
<p><figure id="attachment_1641" aria-describedby="caption-attachment-1641" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1641" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay14.jpg" alt="Một góc đường Cần Thơ" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay14.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay14-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1641" class="wp-caption-text">Một góc đường Cần Thơ</figcaption></figure></p>
<p>Những chiếc áo dài thướt tha trước đây giờ đã khó bắt gặp ở ngoài hơn.</p>
<p><figure id="attachment_1654" aria-describedby="caption-attachment-1654" style="width: 640px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1654" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa9.jpg" alt="Áo dài Việt Nam ngày xưa" width="640" height="456"><figcaption id="caption-attachment-1654" class="wp-caption-text">Áo dài Việt Nam ở đường Phan Đình Phùng ngày xưa</figcaption></figure></p>
<p><figure id="attachment_1640" aria-describedby="caption-attachment-1640" style="width: 1280px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1640" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay13.jpg" alt="Đường Phan Đình Phùng ngày nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay13.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay13-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1640" class="wp-caption-text">Đường Phan Đình Phùng ngày nay</figcaption></figure></p>
<p>Xe lôi ở Cần Thơ dường như giờ đã không còn. Mà giờ chỉ thấy xe hơi.</p>
<p><figure id="attachment_1653" aria-describedby="caption-attachment-1653" style="width: 525px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1653" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa8.jpg" alt="Góc phố Cần Thơ trước năm 1975" width="525" height="351"><figcaption id="caption-attachment-1653" class="wp-caption-text">Góc phố Cần Thơ trước năm 1975</figcaption></figure></p>
<p><figure id="attachment_1637" aria-describedby="caption-attachment-1637" style="width: 5472px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1637" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay10.jpg" alt="Một góc phố Cần Thơ ngày nay" width="5472" height="3648" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay10.jpg 5472w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay10-768x512.jpg 768w" sizes="(max-width: 5472px) 100vw, 5472px" /><figcaption id="caption-attachment-1637" class="wp-caption-text">Một góc phố Cần Thơ ngày nay</figcaption></figure></p>
<p>Có những ngôi trường tồn tại hàng trăm năm. Kiến trúc vẫn như cũ chỉ có cái tên là thay đổi&#8230;!!! Điển hình là trường trung học Phan Thanh Giản với lịch sử lâu đời từ năm 1917 đến nay. Nó đã có hơn 100 năm lịch sử. Tuy nhiên năm 1985 nó đã được đổi tên thành trường Trung học phổ thông Châu Văn Liêm và hiện nay đang đóng cửa để tu sửa lại.</p>
<p><figure id="attachment_1658" aria-describedby="caption-attachment-1658" style="width: 637px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1658" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa13.jpg" alt="Trường trung học Phan Thanh Giản" width="637" height="462"><figcaption id="caption-attachment-1658" class="wp-caption-text">Trường trung học Phan Thanh Giản</figcaption></figure></p>
<p><figure id="attachment_1666" aria-describedby="caption-attachment-1666" style="width: 5472px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1666" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay3.jpg" alt="Trường THPT Phan Thanh Giản đã đổi tên thành Trường Châu Văn Liêm" width="5472" height="3648" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay3.jpg 5472w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay3-768x512.jpg 768w" sizes="(max-width: 5472px) 100vw, 5472px" /><figcaption id="caption-attachment-1666" class="wp-caption-text">Trường THPT Phan Thanh Giản đã đổi tên thành Trường Châu Văn Liêm</figcaption></figure></p>
<p>Nhà thờ Chánh Tòa dường như không bị lão hóa theo thời gian! Nó được khởi công từ năm 1899 đến nay là gần 120 năm lịch sử. Một nhà thờ có lịch sử khá lâu đời ở Việt Nam.</p>
<p><figure id="attachment_1657" aria-describedby="caption-attachment-1657" style="width: 604px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1657" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa12.jpg" alt="Nhà thờ Chánh Tòa ngày xưa" width="604" height="371"><figcaption id="caption-attachment-1657" class="wp-caption-text">Nhà thờ Chánh Tòa ngày xưa</figcaption></figure></p>
<p><figure id="attachment_1644" aria-describedby="caption-attachment-1644" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1644" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay17.jpg" alt="Nhà thờ Chánh Tòa hiện nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay17.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay17-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1644" class="wp-caption-text">Nhà thờ Chánh Tòa hiện nay</figcaption></figure></p>
<p>Tôi thích style bảng hiệu ngày trước nhiều hơn.</p>
<p><figure id="attachment_1652" aria-describedby="caption-attachment-1652" style="width: 550px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1652" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa7.jpg" alt="Một ngôi nhà Cần Thơ xưa" width="550" height="402"><figcaption id="caption-attachment-1652" class="wp-caption-text">Một ngôi nhà Cần Thơ xưa</figcaption></figure></p>
<p><figure id="attachment_1638" aria-describedby="caption-attachment-1638" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1638" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay11.jpg" alt="Ngôi nhà có địa chỉ 40 Hùng Vương hiện nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay11.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay11-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1638" class="wp-caption-text">Ngôi nhà có địa chỉ 40 Hùng Vương hiện nay</figcaption></figure></p>
<p>Những tòa nhà cũ trên một góc đường Trần Phú vẫn giường như không thay đổi!</p>
<p><figure id="attachment_1649" aria-describedby="caption-attachment-1649" style="width: 550px" class="wp-caption alignleft"><img loading="lazy" decoding="async" class="size-full wp-image-1649" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa4.jpg" alt="Một góc đường Trần Phú Cần Thơ xưa" width="550" height="357"><figcaption id="caption-attachment-1649" class="wp-caption-text">Một góc đường Trần Phú Cần Thơ xưa</figcaption></figure></p>
<p><figure id="attachment_1639" aria-describedby="caption-attachment-1639" style="width: 1280px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1639" src="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay12.jpg" alt="Đường Trần Phú ngày nay" width="1280" height="853" srcset="https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay12.jpg 1280w, https://media.huynhhieutravel.com/Cần-Thơ-xưa-và-nay12-768x512.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" /><figcaption id="caption-attachment-1639" class="wp-caption-text">Đường Trần Phú ngày nay</figcaption></figure></p>
<p>Đôi khi lật lại ký ức, ta dường như không muốn nó đổi thay. Nhiều người vẫn muốn nó là thành phố Cần Thơ của ngày hôm qua. Nhưng theo quy luật phát triển, Cần Thơ sẽ ngày càng thay đổi nhiều hơn. Hy vọng chúng ta sẽ tiếp tục nhìn về phía trước nhưng vẫn gìn giữ những giá trị di sản để mai sau nó vẫn còn hiện hữu cho con cháu chiêm ngưỡng.</p>
', 'Hình ảnh Cần Thơ xưa nay với bao đổi thay và dần trở thành một thành phố trực thuộc trung ương hiện đại, tấp nập. Nhưng những góc phố, con đường và cả con người dường như vẫn không quá nhiều thay đổi. Hãy cùng nhìn lại những khoảnh khắc Cần Thơ ngày trước và [&hellip;]', 1647, 'post', '2018-08-26 08:30:06', '2023-04-23 12:47:36');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1671, 431);
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1671, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1671, 304);
INSERT OR IGNORE INTO Post (id, title, slug, content, excerpt, featuredImage, type, createdAt, updatedAt) VALUES (1631, 'Quảng trường Lâm Viên Đà Lạt', 'quang-truong-lam-vien-da-lat', '<p><strong>Quảng trường Lâm Viên</strong> là một quần thể kiến trúc độc đáo và xinh đẹp của Đà Lạt. Nó có vị trí khá đẹp với view nhìn ra Hồ Xuân Hương. Đặc biệt ở quảng trường Lâm Viên có hai biểu tượng khổng lồ của Đà Lạt là <strong>nụ hoa atiso</strong> và <strong>bông hoa cúc quỳ</strong>. Nơi đây thường diễn ra nhiều sự kiến lớn và lễ hội của Đà Lạt.</p>
<p><figure id="attachment_1626" aria-describedby="caption-attachment-1626" style="width: 720px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1626" src="https://media.huynhhieutravel.com/Quảng-Trường-Lâm-Viên.jpg" alt="Quảng trường Lâm Viên" width="720" height="960"><figcaption id="caption-attachment-1626" class="wp-caption-text">Quảng trường Lâm Viên</figcaption></figure></p>
<h2>Thông tin Quảng trường Lâm Viên</h2>
<p><strong>Quảng trường Lâm Viên</strong> được xây dựng từ năm <strong>2009</strong> và phải mất đến <strong>6 năm</strong> mới hoàn thành. Nó có diện tích khoảng <strong>72.000m2</strong>. Đặc biệt với hai biểu tượng khổng lồ là nụ hoa atiso và bông hoa cúc quỳ. Nụ hoa atiso có chiều cao 15m và diện tích 1.500m2. Bông hoa cúc quỳ có chiều cao 18m và diện tích 1.200m2. Nơi đây như một công viên, nơi tập trung vui chơi giải trí của nhiều người dân Đà Lạt, cũng như khách du lịch.</p>
<p><strong>Địa chỉ</strong>:&nbsp;Trần Quốc Toản, Phường 1, Thành phố Đà Lạt, Lâm Đồng, Việt Nam</p>
<p><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3903.5147733817666!2d108.4428464140572!3d11.938818939927968!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31711324a3fe0629%3A0x66eb8ed37afe5989!2zUXXhuqNuZyB0csaw4budbmcgTMOibSBWacOqbg!5e0!3m2!1svi!2s!4v1535189778358" width="600" height="450" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h3>Lịch sử&nbsp;Quảng trường Lâm Viên</h3>
<p>Quảng trường Lâm Viên được xây dựng từ năm <strong>2009</strong> đến năm <strong>2016</strong> thì hoàn thành với kinh phí lên đến <strong>681</strong> tỷ đồng. Diện tích <strong>72.000m2</strong> nằm ở vị trí đắc địa của Đà Lạt bên mạn phải Hồ Xuân Hương.</p>
<h3>Kiến trúc Quảng trường Lâm Viên</h3>
<p>Quảng trường Lâm Viên có kiến trúc rộng lớn với hai biểu tượng đặc trưng của Đà Lạt là bông hoa cúc quỳ và nụ hoa Atiso. Ngoài ra bên ngoài khuôn viên có trồng nhiều loài hoa tươi khác nhau để làm không gian trở nên xinh đẹp hơn. Bên dưới quảng trường là siêu thị Big C.</p>
<h4>Nụ hoa Atiso</h4>
<p><strong>Chiều cao</strong>: 15m2, <strong>diện tích</strong>: 1.500m2. Thiết kế hình dáng giống như một nụ hoa atiso &#8211; một biểu tượng đặc trưng của Đà Lạt. Nó là một món ăn đặc sản ở xứ sở nghìn hoa. Đặc biệt là món thịt heo hầm bông atiso tươi luôn được du khách mê mẩn khi thưởng thức. Bao quanh bông atiso là lớp kính cường lực màu xanh chạy thành hình xoắn ốc từ dưới lên trên. Bên trong là một quán cafe phục vụ du khách.</p>
<p><figure id="attachment_1627" aria-describedby="caption-attachment-1627" style="width: 599px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1627" src="https://media.huynhhieutravel.com/Quảng-Trường-Lâm-Viên2.jpg" alt="Biểu tượng bông atiso Đà Lạt" width="599" height="566"><figcaption id="caption-attachment-1627" class="wp-caption-text">Biểu tượng bông atiso Đà Lạt</figcaption></figure></p>
<h4>Bông hoa Cúc quỳ (Dã quỳ)</h4>
<p><strong>Chiều cao</strong>: 18m2, <strong>diện tích</strong>: 12.000m2. Thiết kế hình dáng giống như một bông hoa cúc quỳ &#8211; cũng là một biểu tượng đặc trưng khác của Đà Lạt. Mỗi khi mùa mưa về, những bông hoa cúc quỳ này lại nở rộ. Đặc biệt khắp trên đường bạn sẽ thấy một sắc vàng của hoa cúc quỳ này khắp nơi.</p>
<p>Theo thiết kế, các cánh hoa được lắp kính vàng sẽ ôm sát theo hình vòm, còn nhụy hoa nghiêng 1 góc vừa đủ để du khách có thể nhìn thấy toàn bộ hình ảnh một bông hoa cúc quỳ nở giữa khuôn viên của quảng trường.&nbsp;Phần còn lại của công trình được lắp kính màu xanh.</p>
<p>Người thiết kế nên những công trình này là kiến trúc sư Trần Văn Dũng.</p>
<p><figure id="attachment_1628" aria-describedby="caption-attachment-1628" style="width: 473px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1628" src="https://media.huynhhieutravel.com/Quảng-Trường-Lâm-Viên3.jpg" alt="Biểu tượng hoa cúc quỳ" width="473" height="594"><figcaption id="caption-attachment-1628" class="wp-caption-text">Biểu tượng hoa cúc quỳ</figcaption></figure></p>
<h2>Đường đi đến Quảng trường Lâm Viên</h2>
<p>Đường đi đến Quảng trường Lâm Viên khá dễ dàng. Nó nằm cách chợ Đà Lạt chỉ gần <strong>2km</strong>. Bạn có thể đi bằng xe máy và gửi xe ở Big C và đi bộ lên.</p>
<p>Bạn có thể điền tọa độ của bạn vào link này để tìm đường đi: <a href="https://www.google.com/maps/dir//Qu%E1%BA%A3ng+tr%C6%B0%E1%BB%9Dng+L%C3%A2m+Vi%C3%AAn,+Tr%E1%BA%A7n+Qu%E1%BB%91c+To%E1%BA%A3n,+Ph%C6%B0%E1%BB%9Dng+1,+Th%C3%A0nh+ph%E1%BB%91+%C4%90%C3%A0+L%E1%BA%A1t,+L%C3%A2m+%C4%90%E1%BB%93ng,+Vi%E1%BB%87t+Nam/@11.9388955,108.4100153,13z/data=!4m8!4m7!1m0!1m5!1m1!1s0x31711324a3fe0629:0x66eb8ed37afe5989!2m2!1d108.4450351!2d11.9388137">Tọa độ và đường đi đến Quảng trường Lâm Viên</a></p>
<h2>Quảng trường Lâm Viên có gì chơi?</h2>
<ul>
<li><strong>Chụp hình</strong> tuyệt đẹp với những biểu tượng khổng lồ của Đà Lạt là nụ hoa atiso và bông hoa cúc quỳ.</li>
<li>Thưởng thức những món <strong>ăn vặt</strong> ngon lành bán ở gần đó: xắp xắp, bánh tráng nướng, sữa đậu nành,&#8230;</li>
<li><strong>Tham quan</strong> không khí trong lành với cây xanh, hoa tươi và cả Hồ Xuân Hương tĩnh lặng ở cạnh bên.</li>
<li>Những <strong>trò chơi</strong> nhớ về một thời tuổi thơ: Xe điện, thả diều, trượt patin,&#8230;</li>
<li>Đi <strong>siêu thị</strong> gần bên: Siêu thị Big C nằm gần Quảng trường Lâm Viên.</li>
</ul>
<p><figure id="attachment_1629" aria-describedby="caption-attachment-1629" style="width: 477px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1629" src="https://media.huynhhieutravel.com/Quảng-Trường-Lâm-Viên4.jpg" alt="Khách du lịch ở Quảng trường Lâm Viên" width="477" height="598"><figcaption id="caption-attachment-1629" class="wp-caption-text">Khách du lịch ở Quảng trường Lâm Viên</figcaption></figure></p>
<h2>Kinh nghiệm đi Quảng trường Lâm Viên</h2>
<ul>
<li>Bạn có thể gửi xe ở dưới hầm của siêu thị Big C và đi bộ lên đây.</li>
<li>Bạn nên tham khảo những kiểu chụp hình với quảng trường trước khi đến đây qua Facebook, Instagram,&#8230;</li>
<li>Bạn cũng nên chuẩn bị phụ kiện để chụp hình cho đẹp và độc đáo hơn.</li>
</ul>
<h3>Thời điểm thích hợp đi Quảng trường Lâm Viên</h3>
<p>Quảng trường Lâm Viên gần như mở quanh năm, nhưng bạn cũng nên lựa chọn thời điểm thích hợp để đi. Bạn nên tránh dịp lễ tết ra vì sẽ khá đông du khách đến đây và bạn sẽ mệt mỏi rất nhiều khi chen lấn giữa dòng người đông đúc.</p>
<p>Quảng trường Lâm Viên có cảnh quan khá độc đáo vì thế hãy mang bộ đồ thích hợp cho phong cách. Ngoài ra bạn nên đi vào lúc thời tiết nắng đẹp để chụp những bức hình tuyệt đẹp. Đừng đi vào lúc mưa hay trời tối.</p>
<p><figure id="attachment_1630" aria-describedby="caption-attachment-1630" style="width: 599px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" class="size-full wp-image-1630" src="https://media.huynhhieutravel.com/Quảng-Trường-Lâm-Viên5.jpg" alt="View nhìn ra Hồ Xuân Hương Đà Lạt" width="599" height="449"><figcaption id="caption-attachment-1630" class="wp-caption-text">View nhìn ra Hồ Xuân Hương Đà Lạt</figcaption></figure></p>
<h2>Review Quảng trường Lâm Viên</h2>
<p>Cảnh quan ở đây khá trong lành và mát mẻ vì cây xanh, hoa tươi và cả Hồ Xuân Hương gần bên. Bạn có thể phối đồ thời trang năng động để chụp hình với hai biểu tượng khổng lồ của Đà Lạt ở đây. Điêm tham quan này lại hoàn toàn miễn phí, vậy thì tại sao không thử đến?</p>
<p><em><strong>Đánh giá</strong></em>: 9/10.</p>
<h3>Đánh giá của khách du lịch về làng Cù Lần</h3>
<ul>
<li>Bạn Thanh Hoàng đánh giá 5/5: &#8220;Quảng trường Lâm Viên gây ấn tượng với nhiều người bằng vẻ đẹp hiện đại,khỏe khắn của một thành phố du lịch vốn nổi tiếng với sự lãng mạn, thơ mộng. Công tình biểu tượng dã quỳ và nụ hoa nằm cách nhau khoảng 80m,&#8230;&#8221;</li>
</ul>
<p>Quả thật Quảng trường Lâm Viên với các hoạt động vui chơi thể thao như patin, đi bộ, thể dục,&#8230; Dần trở thành một nơi năng động cho các bạn trẻ đến tham quan và du lịch</p>
<ul>
<li>Bạn Hảo Huỳnh đánh giá 4/5: &#8220;Quảng trường Lâm Viên &#8211; Điểm đến mới thu hút giới trẻ ở Đà Lạt. Đà Lạt &#8211; Thành phố ngàn hoa đang trở thành điểm đến không thể thiếu của các bạn trẻ từ khắp nơi,&#8230;&#8221;</li>
</ul>
<p>Với mình, Đà Lạt không chỉ thu hút các bạn trẻ mà nó thu hút tất cả mọi người đến đây du lịch. Từ không gian, khí hậu đến con người, tất cả đều rất tuyệt vời.</p>
<p><figure id="attachment_1633" aria-describedby="caption-attachment-1633" style="width: 383px" class="wp-caption alignnone"><img loading="lazy" decoding="async" class="size-full wp-image-1633" src="https://media.huynhhieutravel.com/review-quảng-trường-lâm-viên.png" alt="Review Quảng trường Lâm Viên" width="383" height="520"><figcaption id="caption-attachment-1633" class="wp-caption-text">Review Quảng trường Lâm Viên</figcaption></figure></p>
<p>Bài viết gần như tổng hợp tất cả những hiểu biết của mình về Quảng trường Lâm Viên Đà Lạt. Nếu có thêm thông tin gì khác hãy cùng chia sẽ bạn nhé!</p>
<p>Email:&nbsp;<em><strong>huynhtronghieu1911@gmail.com</strong></em></p>
<p>Ngoài ra các bạn có thể tham khảo thêm những địa điểm du lịch thú vị khác:</p>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Nông trại thú cưng Đà Lạt – Black Rock Garden” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/nong-trai-thu-cung-da-lat-black-rock-garden/embed/#?secret=ds6wEU8uDw" width="600" height="252" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="ds6wEU8uDw" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Kinh nghiệm đi Tuyệt Tình Cốc Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/kinh-nghiem-di-tuyet-tinh-coc-da-lat/embed/#?secret=68ULRnwutR" width="600" height="252" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="68ULRnwutR" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Thác Datanla Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/thac-datanla-da-lat/embed/#?secret=UML3gOEYTz" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="UML3gOEYTz" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Đường Hầm Điêu Khắc (Đường Hầm Đất Sét) Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/duong-ham-dieu-khac-da-lat/embed/#?secret=66CkpHH1hz" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="66CkpHH1hz" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Đỉnh núi Langbiang Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/dinh-nui-langbiang-da-lat/embed/#?secret=QNwDEd19bh" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="QNwDEd19bh" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Thung Lũng Vàng (Khu du lịch Suối Vàng) Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/thung-lung-vang/embed/#?secret=bOAHoM0E6m" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="bOAHoM0E6m" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Crazy House Đà Lạt (Biệt Thự Hằng Nga)” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/crazy-house/embed/#?secret=nvUvM8WMko" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="nvUvM8WMko" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Quảng trường Lâm Viên Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/quang-truong-lam-vien-da-lat/embed/#?secret=EQNzS0sYdd" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="EQNzS0sYdd" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Khu du lịch Lá Phong” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/khu-du-lich-la-phong/embed/#?secret=WReaBlNo9T" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="WReaBlNo9T" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Đồi Thiên Phúc Đức Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/doi-thien-phuc-duc/embed/#?secret=zU1SnSZNoC" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="zU1SnSZNoC" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Vườn Thú Zoodoo” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/vuon-thu-zoodoo/embed/#?secret=8R0QrehllX" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="8R0QrehllX" data-mce-fragment="1"></iframe></p>
</div>
<div class="video-container">
<p><iframe class="wp-embedded-content" title="“Trường Cao Đẳng Sư Phạm Đà Lạt” — Huỳnh Hiếu Travel" src="https://huynhhieutravel.com/truong-cao-dang-su-pham-da-lat/embed/#?secret=KkPW8Gq0Kr" width="600" height="260" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-scripts" data-secret="KkPW8Gq0Kr" data-mce-fragment="1"></iframe></p>
</div>
', 'Quảng trường Lâm Viên là một quần thể kiến trúc độc đáo và xinh đẹp của Đà Lạt. Nó có vị trí khá đẹp với view nhìn ra Hồ Xuân Hương. Đặc biệt ở quảng trường Lâm Viên có hai biểu tượng khổng lồ của Đà Lạt là nụ hoa atiso và bông hoa cúc [&hellip;]', 1626, 'post', '2018-08-25 10:10:37', '2023-04-23 12:46:54');
INSERT OR IGNORE INTO PostCategory (postId, categoryId) VALUES (1631, 34);
INSERT OR IGNORE INTO PostTag (postId, tagId) VALUES (1631, 48);