ALTER TABLE Post ADD COLUMN seoTitle TEXT;
ALTER TABLE Post ADD COLUMN seoDescription TEXT;
ALTER TABLE Post ADD COLUMN ogImage TEXT;
ALTER TABLE Post ADD COLUMN schemaEnabled INTEGER DEFAULT 1;
ALTER TABLE Post ADD COLUMN schemaUpdatedAt TEXT;
ALTER TABLE Post ADD COLUMN schemaUpdatedBy TEXT;
